### ISSUE TITLE
[bug] Отключение bootstrap на фронте

### ISSUE THREAD

**Issue by opotemkin** [yupe/yupe#1137]
Добрый день!
Это скорее вопрос, потому как для fronted использую сторонний css-фреймворк, и нет необходимости подключать bootstrap (в частности, "bootstrap-combined.no-icons.min.css" из файла booster/components/packages.php).

По умолчанию он загружается в assets. Не понимаю как безболезненно отключить его на фронте, и оставить включенным на backend.

Спасибо!

**Comment by 4502040** [comment]
как отключить бутстрапа на 0.9.8 версии ? уже достал.

**Comment by DarkCs** [comment]
закоментируйте в своей теме https://github.com/yupe/yupe/blob/master/themes/default/bootstrap.php#L5 и не используйте виджеты из yiibooster

**Comment by 4502040** [comment]
Спасибо за ответ, я уже пробовал так делать, вылезла ошибка что ./clevertech/booster/widgets/TbListView не может найти Booster

**Comment by 4502040** [comment]
хотя у меня чистый, хтмл шаблон, никакого элемента booster-a нет

**Comment by 4502040** [comment]
понял, юпи подключает мне listView элемент, по идеи не должно было. как убрать, не скажете ?
заранее спасибо.

**Comment by 4502040** [comment]
все нашел, у меня был включен модуль homepage. все заработало. спасибо
