### ISSUE TITLE
Не добавляет комментарий от анонима

### ISSUE THREAD

**Issue by Grimfri** [yupe/yupe#1735]
При попытке добавить комментарий, появляется окошко "Запись не добавлена". С зарегистрированным пользователем - работает.

log:

```
2014/11/19 01:24:14 [error] [comment] exception 'CDbException' with message 'Error append comment to root!' in /home/grimfri-serv/lampp/yupe/protected/modules/comment/components/CommentManager.php:70
Stack trace:
#0 /home/grimfri-serv/lampp/yupe/protected/modules/comment/controllers/CommentController.php(79): CommentManager->create(Array, Object(CommentModule), Object(YWebUser), Object(yupe\components\HttpRequest))
#1 /home/grimfri-serv/lampp/yupe/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(49): CommentController->actionAdd()
#2 /home/grimfri-serv/lampp/yupe/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#3 /home/grimfri-serv/lampp/yupe/vendor/yiisoft/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#4 /home/grimfri-serv/lampp/yupe/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 /home/grimfri-serv/lampp/yupe/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('add')
#6 /home/grimfri-serv/lampp/yupe/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('comment/comment...')
#7 /home/grimfri-serv/lampp/yupe/vendor/yiisoft/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#8 /home/grimfri-serv/lampp/yupe/public/index.php(35): CApplication->run()
#9 {main}
in /home/grimfri-serv/lampp/yupe/protected/modules/comment/components/CommentManager.php (81)
in /home/grimfri-serv/lampp/yupe/protected/modules/comment/controllers/CommentController.php (79)
in /home/grimfri-serv/lampp/yupe/public/index.php (35)
2014/11/19 01:24:14 [trace] [system.CModule] Loading "ajax" application component
in /home/grimfri-serv/lampp/yupe/protected/modules/comment/controllers/CommentController.php (107)
in /home/grimfri-serv/lampp/yupe/public/index.php (35)

```

**Comment by vv3d0x** [comment]
не срабатывает защита от спама потому что
```
$(document).ready(function(){
        $(document).on('click', '#Comment_text', function(){
           $('#<?= $spamNode; ?>').val('<?= $spamNodeValue; ?>');
        })
    });
```
мы можем и через таб переключатся на поле, тогда click не работает, лучше так
```
$(function() {
        $('#Comment_text').on('focus', function(e) {
           $('#<?= $spamNode; ?>').val('<?= $spamNodeValue; ?>');
        });
    });
```

**Comment by mfilin** [comment]
а как для анонимного пользователя разрешить комментировать?

**Comment by mfilin** [comment]
\protected\modules\image\widgets\colorbox\ColorBoxWidget.php в методе init() используется DIRECTORY_SEPARATOR. У меня локалка на win стоит, и пути корежатся /public/assets/1125a04d%5Cjs%5Cjquery.colorbox-min.js"...не критично, но непонятно, чего надо то :)

**Comment by sabian** [comment]
Несколько мыслей:

1. Очень не хватает сообщений о валидации. Выскакивает надпись "Запись не добавлена", а почему не понятно, может эмейл неправильный или забыли его ввести. 

2. Заметил такую фигню: вводим все правильно, нажимаем и видим "Запись не добавлена", затем обновляем капчу, вводим ее заново и все добавляется. И такое было  у меня много раз. Возможно это только у меня, проверьте кто-нибудь. Может дело в капче, а не в чем-то другом.

3. @vv3d0x прав. Если не кликнуть по полю комментария, то сообщение не отправится, как ни бейся.

**Comment by chemezov** [comment]
2. Частично подтвержу. Были проблемы с капча при логине. Вводились правильные реквизиты (копипастой), вводилась правильно капча (не с первой попытки), и логин не удавался, но после обновления страницы или только капчи всё проходило. Не отследил когда эта бага появилась и есть ли она сейчас.

**Comment by mfilin** [comment]
вообще, в практике были баги с капчей еще с ранних версий YII, приходилось ставить JS на загрузку страницы, аля click(button#yw1) :DD

по теме, еще потестирую модуль, постараюсь прислать коммит

**Comment by DarkCs** [comment]
так все правильно - неправильный ввод - новая капча, просто её надо обновлять при ошибках, у нас пока этого нет

**Comment by mfilin** [comment]
эти два коммита решают проблему бага
https://github.com/mfilin/yupe/commit/1b546efca9f03c604eb1f759a6e1585e77e11b62
https://github.com/mfilin/yupe/commit/cb34d4faa1f767b2f59ec8bd04989c2d9410c831

в первом, при добавлении коммента не нужно ничего проверять (валидация идет на уровне дерева, то есть не самих параметров Имейл Имя)
второй, решает проблему указания переменной $spamField(в первых постах обсуждалось)

и третье, валидация имени и почтаря для анонимуса никак не валидируется, в таблицу просто уходят пробелы-пусто (не NULL)...возможно так задумал создатель этого модуля
(проверял во всех браузерах, зеленая полоса есть :D)

**Comment by sabian** [comment]
Ваш первый коммит ничего не решает, Вы просто отключили валидацию и получается, что капча там просто для вида.

**Comment by mfilin** [comment]
да, Вы правы. последние коммиты решают наши проблемы
