### ISSUE TITLE
Создание большой карты сайта

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1742]
Проблема в этой строке:
https://github.com/yupe/yupe/blob/master/protected/modules/sitemap/controllers/SitemapController.php#L18

Устанавливается лимит на выполнение 120 сек. Если страниц слишком много, то этого времени не хватает. Предлагаю полностью убрать изменение лимита, и оставить установку этого параметра разработчику в php.ini или ещё как-то.

**Comment by chemezov** [comment]
@DarkCs может имеет смысл генерить карту в файл? В любом случае, если она генерится даже 10 сек, это много. А экшн на генерирование перенести на команду и повесить её на крон.

**Comment by DarkCs** [comment]
да, было бы неплохо

**Comment by yupe** [comment]
Генерится все теперь через модуль от @samdark  https://github.com/samdark/sitemap

**Comment by samdark** [comment]
О, крутяк :)
