### ISSUE TITLE
Фронт контроллеры

### ISSUE THREAD

**Issue by mikspark** [yupe/yupe#1755]
Фронт контроллеры в модулях должны наследоваться от https://github.com/yupe/yupe/blob/master/protected/components/Controller.php

**Comment by chemezov** [comment]
@yupe т.е. сейчас от application\components\Controller расширяется только SiteController?

А FrontController и BackController расширяются от yupe\components\controllers\Controller?

**Comment by yupe** [comment]
@chemezov нет +) Это мой косяк +) Конечно же  FrontController и BackController должны расширяться от application\components\Controller

**Comment by chemezov** [comment]
@yupe а зачем вообще FrontController и BackController наследовать от application\components\Controller? Всё равно же не удастся переопределить init. Может наследовать их от yupe\components\controllers\Controller, но добавить событие и всё? А то странная выгода какая-то получается.

**Comment by yupe** [comment]
@chemezov по задумке application\components\Controller может быть отредактирован пользователем, например, можно добавить какое-то новое свойство или метод, а затем использовать их во вьюхах.

**Comment by chemezov** [comment]
@yupe Тогда может имеет смысл FrontController вынести в application\components?

**Comment by yupe** [comment]
@chemezov а для чего ?

**Comment by chemezov** [comment]
@yupe сейчас получается что какой-то функционал добавить в application\components\Controller мы можем, но не можем его переопределить, там есть init, на который повлиять мы не можем. Есть смысл сделать BaseFrontController в yupe, а сам FrontController вынести в application\components чтобы наследование было полным, а не где-то посередине.
