### ISSUE TITLE
Мультиязычность

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1758]
http://yupe.ru/talk/viewtopic.php?id=766

**Comment by yupe** [comment]
http://yupe.ru/post/language-switcher-works-incorrectly.html

**Comment by switchy** [comment]
Подтверждаю, действительно есть такой баг. Всплывает в случае, когда в $url для Yii::app()->createAbsoluteUrl($url) передается route в котором уже в качестве префикса присутсвует язык.
Мое решение:
yupe/componenes/urlManager/LangUrlManager.php
public function createUrl($route, $params = array(), $ampersand = '&')
...
        // Если язык не указан - берем текущий
        if (!isset($params[$this->langParam])) {
            $do_params = true;
            if (!empty($this->languages)){
                foreach($this->languages as $lang){
                    if (strpos($route, '/'.$lang.'/')==0){
                        $do_params = false;
                        break;
                    }
                }
            }
            if ($do_params) $params[$this->langParam] = Yii::app()->language;
        }
