### ISSUE TITLE
После сохранения модели пропадают картинки

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1795]
Полагаю что это связано с обновлением yii, а именно:
> - Bug https://github.com/yiisoft/yii/issues/1257: CFileValidator is no longer unsafe by default to prevent setting arbitrary values. Instead, when no file is uploaded attribute is set to null (marcovtwout)

**Comment by yupe** [comment]
А как можно воспроизвести ?

**Comment by chemezov** [comment]
Например, загрузить картинку к новости, потом зайти в редактирование и опять сохранить. Картинка пропадёт. В базе будет null.

**Comment by DarkCs** [comment]
надо вернуть пока на 1.1.15, до решения проблемы

**Comment by DarkCs** [comment]
поправил
