### ISSUE TITLE
Gii 404

### ISSUE THREAD

**Issue by teplenjov** [yupe/yupe#1798]
Не открывается gii (раскомментировал в конфиге).
 
2015/01/11 14:32:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "gii/default/login".' in /var/www/sitename.ru/vendor/yiisoft/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/sitename.ru/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 /var/www/sitename.ru/vendor/yiisoft/yii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#2 /var/www/sitename.ru/public/index.php(35): CApplication->run()
#3 {main}
REQUEST_URI=/gii/default/login

**Comment by DarkCs** [comment]
попробуйте удалить файлик /runtime/cached_settings.php

**Comment by teplenjov** [comment]
Да, сброс кэш настроек помог.
