### ISSUE TITLE
Social, google

### ISSUE THREAD

**Issue by teplenjov** [yupe/yupe#1799]
Модуль social: добавил данные от своего приложения Google API, пытаюсь авторизироваться через Гугл - вылетает "Не определено свойство "application\modules\social\components\services\Google.email".  В качестве redirect_uri в настройках приложения в гугле указал "http://%mysite.ru%/social/login/service/google". Гугл вроде бы корректно обработал этот запрос, в /social/login/service/google?code= возвращён код-токен доступа.

**Comment by yupe** [comment]
Аналогичгая штука для FaceBook

**Comment by DoroninVic** [comment]
решил проблему вот так: 

в файле:
\vendor\nodge\yii-eauth\services\GoogleOAuthService.php

необходимо поправить список запрашиваемых данных 

`protected $scope = 'https://www.googleapis.com/auth/userinfo.profile';`
на 
`protected $scope = 'https://www.googleapis.com/auth/userinfo.email';`

а также в метод fetchAttributes() необходимо добавить: 
`$this->attributes['email'] = $info['email'];`
