### ISSUE TITLE
Вывод списка записей. Парамерт "цитата"

### ISSUE THREAD

**Issue by ApexWire** [yupe/yupe#1803]
Действительно ли тут: https://github.com/yupe/yupe/blob/master/themes/default/views/homepage/hp/_view.php#L15
- нужна функция strip_tags??

**Comment by ApexWire** [comment]
наверное стоит перенести куда нить сюда: https://github.com/yupe/yupe/blob/master/protected/modules/blog/models/Post.php#L545

**Comment by yupe** [comment]
Будет не совсем правильно. Вырезать или не вырезать теги лучше оставить на совесть представления (вьюхи). Так как могут быть разные варианты.
