### ISSUE TITLE
Убрать обязательное поле "контент" у блоков контента

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1815]
Бывает так, что контент временно не нужен, и сейчас скрыть его невозможно, не выпилив сам блок.

**Comment by mikspark** [comment]
Может лучше статус вкл/выкл?

**Comment by yupe** [comment]
Описание блока контента сейчас можно не заполнять.

**Comment by DarkCs** [comment]
скорее ошибка в заголовке

**Comment by chemezov** [comment]
@yupe, @DarkCs да, ошибся в заголовке.

@mikspark лучше сделать и статус, и необязательное поле "контент". Статус поможет временно отключить блок. А пустое поле контент нужно иногда, когда предполагаешь где-то выводить какой-то контент, но ещё не знаешь какой, и просто создаёшь блок, на будущее.
