### ISSUE TITLE
Магазин. Удаление полей с картинками

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#1816]
При добавлении товара, во вкладке "Изображения", если надобавлять пустых полей, а потом нажимать на кнопку удаления, то удаляется только кнопка.
Как вариант, вот здесь https://github.com/yupe/yupe/blob/dev/protected/modules/store/views/productBackend/_form.php#L461 написать:
```javascript
$(this).closest('.product-image').remove();
```

**Comment by yupe** [comment]
Спасибо! Пофиксили.
