### ISSUE TITLE
Поправить переводы

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1822]
Сейчас в верхнем и правом меню надписи имеют разные формы:
- Товары - управление
- Управление новостями

![Картинка](http://clip2net.com/clip/m335995/0fa6e-clip-3kb.png?nocache=1)

Пункты в верхнем меню и правом иногда одинаковые, а иногда разные, хотя ведут на одну и ту же страницу.

Написаны в разном времени:
- Редактирован**ие** новости
- Просмотре**ть** новость

![Картинка](http://clip2net.com/clip/m335995/d53d9-clip-5kb.png?nocache=1)

Если опечатки, типа
- Управление способами доставка

**Comment by chemezov** [comment]
В модуле «Блоки» на одних страницах отображается «Добавить блок контента», на других «Добавить новый блок контента».

**Comment by sabian** [comment]
Сделаю.

**Comment by sabian** [comment]
Наверное стоит привести все к единому виду, а то пишут и так 
```php 
Yii::t('StoreModule.type', 'Добавить')
``` 
и так 
```php 
Yii::t('StoreModule.store', 'Creating')
```
Если да, то какой вариант делать?
Или это не принципиально и править как есть?

**Comment by yupe** [comment]
Более правильно изначально на английском, а перевод уже на русский. Как в других модулях.

**Comment by sabian** [comment]
Выкладываю список того, что сделано, вдруг кто-то захочет подключиться.

- [ ] blog
- [ ] cart
- [ ] category
- [ ] comment
- [ ] contentblock
- [x] coupon
- [x] devivery
- [ ] dictionary
- [ ] docs
- [ ] feedback
- [ ] gallery
- [ ] homepage
- [ ] image
- [ ] install
- [ ] mail
- [ ] menu
- [ ] news
- [x] notify
- [x] order
- [x] page
- [x] payment
- [ ] queue
- [ ] rbac
- [ ] robokassa
- [ ] sitemap
- [ ] social
- [x] store
- [x] update
- [ ] user
- [x] yandexmarket
- [ ] yupe
- [x] zendsearch
