### ISSUE TITLE
HttpRequest и noCsrfValidationRoutes

### ISSUE THREAD

**Issue by vv3d0x** [yupe/yupe#1826]
Не могу понять почему, но этот код не работает с роутами, и это правило не срабатывает
```php
if ($this->enableCsrfValidation) {
            foreach ($this->noCsrfValidationRoutes as $route) {
                if (strpos($this->pathInfo, $route) === 0) {
                    Yii::app()->detachEventHandler('onBeginRequest', [$this, 'validateCsrfToken']);
                }
            }
        }
```

зато если заменить на 
```php
if ($this->enableCsrfValidation) {
            // for fixing csrf validation disabling
            $url = Yii::app()->getUrlManager()->parseUrl($this);
            foreach ($this->noCsrfValidationRoutes as $route) {
               if (strpos($url, $route) === 0) {
                    Yii::app()->detachEventHandler('onBeginRequest', [$this, 'validateCsrfToken']);
               }
            }
        }
```

все отлично работает, что-то не так с `strpos($this->pathInfo, $route)` - оно не находит роуты, у меня в моей конфигурации, всего лишь один дополнительный роут для ексклюда
```php
'noCsrfValidationRoutes' => [
				'site/reviews', //custom
				'backend/AjaxImageUpload',
				'backend/AjaxFileUpload'
			],
```

**Comment by chemezov** [comment]
У меня нормально отработало. Какая конфигурация сервера? Где лежит сайт? На относительных путях или абсолютных? Т.е. типа `http://yupe.local/site/reviews` или `http://localhost/yupe/public/site/reviews`?

**Comment by vv3d0x** [comment]
В `urlManager` в поле `rules` у меня правило: 
`'/reviews' =>'site/reviews'`, а в `noCsrfValidationRoutes` есть запись: `'site/reviews'`, а в `$this->pathInfo` у меня попадает только `reviews`, причем не /reviews или site/reviews.

выходит что выполняется код: `strpos('reviews', 'site/reviews')`, а надо что бы аргументы свапнулись. Может это зависитот конфинурации веб-сервера ?

**Comment by DarkCs** [comment]
в noCsrfValidationRoutes надо добавлять не роуты, а url, то есть не site/reviews, а reviews

**Comment by vv3d0x** [comment]
название `noCsrfValidationRoutes` говорит как бы все за себя :)
иначе путаница

**Comment by chemezov** [comment]
@vv3d0x не очевидная штука, да.

Может есть смысл вообще выпилить возможность noCsrfValidation? Оно у нас используется только для загрузки изображений в redactor, и было временным решением. Сейчас можно передавать csrf параметры в redactor'е (https://github.com/yupe/yupe/issues/1825).

**Comment by DarkCs** [comment]
выпиливать нельзя, потому что надо иметь возможность принимать пост запросы от внешних сервисов, сделать так, чтобы можно было указывать роуты было бы неплохо

**Comment by chemezov** [comment]
Создал тикет https://github.com/yupe/yupe/issues/1827, этот, думаю, можно закрыть.
