### ISSUE TITLE
Конфликт модулей «Магазин» и «Каталог»

### ISSUE THREAD

**Issue by hello-omny** [yupe/yupe#1830]
Возникает при установке модулей одновременно. Второй уровень каталога и продукты работают, а первый уровень — 404. 

Проблема в урлах оба модуля используют /catalog/path-to-something.
Исправил так:
1. yupe/protected/modules/store/models/StoreCategory.php > getUrl() заменил /catalog/ на /store/.
2. 'rules' к модулю вместо /catalog/ я прописал /store/ везде.

Возможно это не баг, а частный случай, поправьте менять тогда.

**Comment by yupe** [comment]
Да, есть такое. Для чего Вам потребовалось иметь одновременно и catalog и store ? Просто отключите catalog и все будет отлично. Или в Вашем случае необходимы именно два эти модуля сразу ?

**Comment by hello-omny** [comment]
Разобраться с этим я сумел, но не быстро. Дело в том, что конфликт есть, избавиться от него не так тяжело, и профит есть. Предлагаю исправить :)

Да я хотел использовать магазин для товаров, а каталог для других материалов, типа карточек предприятий.

**Comment by yupe** [comment]
Понятно, поправим в 0.9.2, спасибо!

**Comment by yupe** [comment]
Поправили.
