### ISSUE TITLE
Модули на месте главной страницы

### ISSUE THREAD

**Issue by hello-omny** [yupe/yupe#1831]
Почему бы не дать возможность модулям быть главной страницей? Модуль блогов же так делает. А например, магазин или каталог почему нет?

Возможно добавить какую-то опцию в модуль, чтобы давать возможность выбрать его в качестве главной страницы?

**Comment by yupe** [comment]
Вы имеете ввиду, чтобы в модуле "hp" можно было выбрать "Каталог товаров" ? Или чтобы при заходе в корень сайта открывался каталог ?

**Comment by hello-omny** [comment]
Да, сейчас в настройках Главной можно выбрать «что отображать»:
1. Страница.
2. Посты.
А мне, сейчас, например, полезно выводить главную магазина, а через некоторое время главную каталога, и быстро между этими модулями переключаться. Я понимаю, что можно заверстать все шаблонами и переключать их, но выгоднее для таких монстров как магазин и каталог добавить опцию быть главной и в пару кликов переключаться.

**Comment by chemezov** [comment]
На самом деле вот этот модуль главной страницы хорош для текстовых страниц. Надо заменить главную на какой-то произвольный текст - используй. Надо вывести какой-то пост из блога - пожалуйста. Но переключать между модулями, это уже вопрос спорный. Лучше и проще всего это делать через роуты. Т.е. основной роут "/" переопределить на нужный модуль и всё. Со страницами так не прокатит, ибо изменится алиас у страницы и всё, будет 404.

Давно уже напрашивается функционал сбора вообще всех возможных страниц на сайте. Чтобы модуль мог чётко сказать какие страницы у него есть (на фронте, естественно). Такое отчасти было реализовано в модуле sitemap. Такой функционал пригодился бы как раз для модуля homepage, возможно, можно было бы использовать в модулей СЕО (в будущем), и просто мега полезно было бы использовать в модуле Меню. Ибо сейчас туда либо прописываешь роут (который знает только программист), либо просто копирует ссылку со строки браузера (что вообще не тру). Т.о. было бы удобно переделать модуль homepage под отображение не каких-то специальных модулей и страниц, а вообще под любую страницу на сайте. Т.е. модуль homepage просто подменял бы каким-то образом роут "/".

**Comment by hello-omny** [comment]
Да, вот если HP это будет уметь— именно то что нужно. Меню с выбором страниц — вообще шик, блеск, красота!

PS: Я не как программист с системой знакомлюсь, а как дизайнер, тяжеловато было в первый раз, особенно с правами на доступ, меню — цветочки еще.

**Comment by yupe** [comment]
Думаю, что пока есть смысл просто добавить возможность вывода главной страницы каталога. Так модули для магазина используются часто. Универсальную штуку можно написать позже, продумав и сформулировав требования.

**Comment by yupe** [comment]
Базовая поддержка магазина добавлена.
