### ISSUE TITLE
pressing 'Создать заказ и перейти к оплате' gives error

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#1834]
Argument 1 passed to Product::getPrice() must be of the type array, null given, called in /var/www/vhost/testdrive/yupe-project/protected/modules/order/models/Order.php on line 468 and defined

**Comment by yupe** [comment]
Исправлено см #1833

**Comment by fazliddin** [comment]
I am using latest version, 0.9.2. But still experiencing the problem.

**Comment by chemezov** [comment]
@fazliddin it's fixed after 0.9.2. released. Look at this commit https://github.com/yupe/yupe/commit/5a3bf73c9b869963c8de743c7486c6d3df7c03cf

**Comment by fazliddin** [comment]
When I use `git pull`, it says `origin/dev -> dev: you are up-to-date`. But `git status` says `you are on master branch`. I am a little confused. I installed by `git clone` and `composer install`

**Comment by yupe** [comment]
git checkout dev - switch you to "dev" branch. Version 0.9.3 with fixed bug you can download here https://github.com/yupe/yupe/releases/tag/v0.9.3
