### ISSUE TITLE
Вложенные транзакции

### ISSUE THREAD

**Issue by Pimentero** [yupe/yupe#1838]
В версии 0.9.2 в классе [Store/Product](https://github.com/yupe/yupe/blob/master/protected/modules/store/models/Product.php) появились вложенные транзакции, которые yii не может обработать.

https://github.com/yupe/yupe/blob/master/protected/modules/store/models/Product.php#L479
https://github.com/yupe/yupe/blob/master/protected/modules/store/models/Product.php#L398
https://github.com/yupe/yupe/blob/master/protected/modules/store/models/Product.php#L479

**Comment by DarkCs** [comment]
видимо у вас установка производилась еще до того, как это было исправлено, поэтому в файле config/db.php нет строки ` 'pdoClass' => 'yupe\\extensions\\NestedPDO',`
для исправления просто добавьте эту строку

**Comment by yupe** [comment]
Закрываем ?
