### ISSUE TITLE
Удаление коментария из админки.

### ISSUE THREAD

**Issue by vv3d0x** [yupe/yupe#1844]
Не работает удаление коментариев из админки..... Используются NestedSets и проблеми при проверке isLeaf мы всегда пытаемся удалить Leaf и там получается зацыкливание.

**Comment by yupe** [comment]
Ммм получается это проблема расширения ?

**Comment by vv3d0x** [comment]
Скорее всего что да.... или не правильно добавляются ноды

**Comment by vv3d0x** [comment]
нашел причину почему не работает удаление, все блин банально, зачем в модель засунули метод
public function delete() ? его нужно удалить из-за него происходит рекусивное зацыкливание.
суть в том что наш NestedSetBehavior который приверчен к модели Comment у него тоже есть метод delete, и когда мы дергаем delete для модели получается так что внутри эта функция для Листка вместо того что бы вызвать delete из ActiveRecord вызывает delete из NestedSetBehavior ну и получается рекурсивный фейл :) А в контроллере все правильно сделано $model->deleteNode();

Если бы в этом NestedSetBehavior небыло бы beforeSave or beforeDelete каторый все обьясняет почему нельзя делать CActiveRecord::delete() я бы наверное и не догадался почему здесь

if($owner->isLeaf())
            {
                $this->_ignoreEvent=true;
                $result=$owner->delete();
                $this->_ignoreEvent=false;
            }
->delete() не тот что нужен
