### ISSUE TITLE
Интерация Yii-Commentator

### ISSUE THREAD

**Issue by vv3d0x** [yupe/yupe#1845]
Предлагаю вместо модуля коментарии использовать модуль Yii-Commentator
https://github.com/PendalF89/yii-commentator
куда более функциональный и нормально работает, есть минимальные нароботки по интегации

**Comment by ApexWire** [comment]
да, неплохой модуль.
как вариант для начала можно сделать отдельный модуль для Юпи и разместить его тут: https://github.com/yupe/yupe-ext/ 
а уже когда будет нормально работающий модуль, то можно будет и заменить.

**Comment by yupe** [comment]
А что не работает в нашем модуле ? Соглашусь с @ApexWire можно интегрировать его в виде доп. модуля.

**Comment by vv3d0x** [comment]
не работает NestedSets, удаление например. да и нету некоторых плюшек

**Comment by yupe** [comment]
@vv3d0x хм, у меня с удалением все в порядке. Как можно воспроизвести баг ?

**Comment by vv3d0x** [comment]
@yupe у меня в админке не работает, версия из ветки dev. используются МногоКорней.
у меня например так можна увидеть: нажимаем на редактировать комментарий, патом справа в сайдбаре нажимаем удалить. я получаю вот такое:
http://screencast.com/t/Ox06RetE
как я выяснил, проблемма в НестедСетсБихейвор в методе delete
он проверяет или мы удаляем листок и там рекурсия и в конце получаем вот-такое

**Comment by yupe** [comment]
@vv3d0x спасибо, обязательно проверим. Если будут наработки по интеграции Yii-Commentator в виде доп. модуля - присылайте, с удовольствием включим.

**Comment by vv3d0x** [comment]
До понидельника закончу :)

**Comment by chemezov** [comment]
Там есть лайки, это круто, этого не хватает. Но весь crud придётся перегенерировать. Настройки тоже переносить. Может есть смысл просто отрефакторить текущий модуль комментариев?

**Comment by vv3d0x** [comment]
нашел причину почему не работает удаление, все блин банально, зачем в модель засунули метод
`public function delete()` ? его нужно удалить из-за него происходит рекусивное зацыкливание.
суть в том что наш NestedSetBehavior который приверчен к модели `Comment` у него тоже есть метод delete, и когда мы дергаем delete для модели получается так что внутри эта функция для Листка вместо того что бы вызвать delete из ActiveRecord вызывает delete из NestedSetBehavior ну и получается рекурсивный фейл :) А в контроллере все правильно сделано ` $model->deleteNode();`

**Comment by vv3d0x** [comment]
Если бы в этом `NestedSetBehavior` небыло бы `beforeSave` or `beforeDelete` каторый все обьясняет почему нельзя делать `CActiveRecord::delete()` я бы наверное и не догадался почему здесь
```
if($owner->isLeaf())
			{
				$this->_ignoreEvent=true;
				$result=$owner->delete();
				$this->_ignoreEvent=false;
			}
```
`->delete()` не тот что нужен

**Comment by chemezov** [comment]
@vv3d0x насколько помню это я прописал этот метод. Он был сделан как раз из-за того что была ошибка при удалении комментариев.

Вот PR: https://github.com/yupe/yupe/pull/1718.

У нас было массовое удаление, но сразу из БД, минуя `afterDelete()`. Из-за этого могли не происходить нужные действия, не удалялись картинки, файлы, связанные с этими моделями.
Я перевёл на удаление через `$model->delete()`, но тогда отвалилось удаление комментариев. Потом, с помощью магии, удалось подружить этот способ с удалением комментариев.

Если из `Comment` убрать метод `delete()`, то при массовом удалении будет выводиться ошибка что удалять нужно через `deleteNode()`.

Посмотрю что можно сделать. Я правильно понял, что ошибка проявляется после редактирования комментария и последующее его удаление? Удаление именно этого комментария или массовое удаление?

**Comment by sabian** [comment]
У меня вообще удаление не работает, ни массовое, ни конкретного комментария

**Comment by mfilin** [comment]
аналогично...надо смотреть

**Comment by yupe** [comment]
Как вариант для модуля комментариев переопределить логику (экшн) для массового удаления.

**Comment by yupe** [comment]
Наш модуль комментариев стал лучше, а в 0.9.5 станет еще лучше.  Интеграцию Yii-Commentator можно разместить вот здесь http://yupe.ru/marketplace если кто-то напишет такой модуль.
@vv3d0x не закончили модуль ?

**Comment by vv3d0x** [comment]
@yupe Модуль то я сделал, но он сильно заточен под котректный проект с нестандартными фишками. Нужно время что бы запихнуть обычный

**Comment by yupe** [comment]
Ясно, тогда тикет закрываю. Если допилите - присылайте сюда http://yupe.ru/marketplace
