### ISSUE TITLE
Магазин. Дополнительные категории в списке товаров.

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#1852]
Сейчас в списке товаров отображается только основная категория. 
Мне кажется это неудобно, нужно заходить в каждый товар и смотреть в каких он категориях.

**Comment by sabian** [comment]
Правда совершенно не знаю как лучше это сделать, ведь если выводить дополнительные категории, то в списке будет каша. У одного товара их может быть много.
Может быть что-то вроде этого: "Какая-то категория + 3 дополнительных", чтобы просто показать, что товар не в одной категории.

**Comment by yupe** [comment]
Мне кажется в yiibooster в гридах было что-то для показа связанных объектов. Можно поискать.

**Comment by chemezov** [comment]
@yupe там было TbRelationalColumn (http://yiibooster.clevertech.biz/extendedGridView#groupgridview), но это не совсем то.

**Comment by chemezov** [comment]
@sabian приведи пример, когда у товара может быть много категорий. Хотя бы больше 3.

**Comment by sabian** [comment]
@chemezov Реальных примеров с большим количеством нет, максимум 2-3. 
Я просто предположил. Если это будет нормально отображать все категории, то почему бы и нет!?

**Comment by DarkCs** [comment]
просто для товаров должны быть совмещены категории и список товаров, тогда все будет удобно и понятно ![](http://i.imgur.com/IlrNdO0.png)

**Comment by chemezov** [comment]
@sabian я вот потому и спросил, сам не смог вспомнить примеров.

@DarkCs как-то обосновывал почему товарам нужны несколько категорий. Ссылку не дам, не помню, но суть: может быть категория "Распродажа 2013", а товар так то принадлежит категории "Телефоны", к примеру, но чтобы не делать отдельный функционал распродаж, можно поместить в такую категорию все товары.
Из чего можно сделать вывод, что если категории и выводить, то можно выводить сразу все и не париться, если их будет много.
