### ISSUE TITLE
Округление стоимости товара

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1855]

**Comment by tmsk70** [comment]
Цитата клиента: 
Выявилась проблема. Когда вводишь цену на товар не целыми рублями а допустим 2,5 на фронтэнде отражается лишь целое число до запятой - а копейки не выводятся. Получается покупатель видит цену 2 руб вместо 2,5 (идет округление цены).

Нужно сделать возможность дописывать дробные (копейки/центы).

**Comment by yupe** [comment]
@sabian поправил у меня все корректно отображается теперь. Дело было не в методе подсчета цены, а в округлении уже на фронте (в теме). @tmsk70 но если проверишь и подтвердишь, что все ок - будем признательны =)

**Comment by tmsk70** [comment]
Супер, все гуд!
