### ISSUE TITLE
Магазин. Стоимость товара в списке

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#1858]
В админке, в списке товаров отображается базовая цена на товар, а не итоговая со скидками.

**Comment by DarkCs** [comment]
логично же?

**Comment by sabian** [comment]
Это немного логично, если введена скидка в процентах. Мы можем из списка изменить цену и она изменится на сайте с учетом скидки. Но если указана фиксированная цена скидки, то основную хоть меняй, хоть не меняй, ничего не происходит. И думаю бестолковому владельцу магазина будет не понятно почему у него цена не меняется.

**Comment by DarkCs** [comment]
мне кажется, в админке нужно показывать информацию базовую, и лучше просто добавить столбец со скидочной ценой и скидкой

**Comment by sabian** [comment]
Можно и так. Над вариантами я не думал и не говорил, что базовую цену надо совсем убрать.

**Comment by yupe** [comment]
Добавил два столбца в грид. Так оставим ?

**Comment by sabian** [comment]
Да. Отлично.
