### ISSUE TITLE
404

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1871]
http://yupe.ru/adfsdfsdfsdf  что-то случилось со страничкой ошибок

**Comment by chemezov** [comment]
@yupe похоже локальная проблема 
![3d6bc-clip-76kb 1](https://cloud.githubusercontent.com/assets/2368902/6402531/19e30ade-be2a-11e4-9faa-b0b544e50841.png)

**Comment by mfilin** [comment]
подтверждаю, на локальном такая же картинка как у @chemezov

**Comment by yupe** [comment]
Согласен, локально было.
