### ISSUE TITLE
Статусы заказа

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1875]
Необходимо иметь возможность добавлять новые статусы для заказа - сделать справочник вместо имеющегося списка.

**Comment by sabian** [comment]
Ни кто над этой задачей не работает, а то я возьмусь?

**Comment by yupe** [comment]
Я не против. Я вот так себе это представлял:
1 Табличка order_order_status: id, name, is_system
2 Заполнить ее статусами, которые есть сейчас (is_system = 1  у них будет)
3 Поле status в Order переименовать в status_id  и сделать FK на новую таблицу статусов
4 Сделать КРУД для статусов (статусы с is_system = 1  нельзя ни удалить ни модифицировать, у новых статусов нельзя поставить is_system)
5 Модифицировать методы Order::getStatusList() и Order::getStatusTitle() 
6 Проверить корректность работы: установка всей системы с нуля, накат новых миграций на имеющиеся заказы (можно сделать несколько тестовых).

Если есть какие-то замечания-предложения - давайте обсуждать.

**Comment by DarkCs** [comment]
а для чего вообще нужны новые статусы? можно пример того, что хотели бы добавить?

**Comment by yupe** [comment]
У каждого ИМ свои процессы, например, "Заказ передан курьеру", "Заказ доставлен", "Клиент отказался" и т.д.

**Comment by yupe** [comment]
@DarkCs кстати хорошая мысль. Посмотрел демку симплы. @sabian что думаешь ?

**Comment by sabian** [comment]
Там заказы разбиты по своим табам, поэтому метки кажутся логичными и удобными. А у нас все в одной сетке. Не будет-ли перегруза информации?
Я не был владельцем магазина, поэтому если честно, то не очень понимаю чем отличается статус заказа от метки. В чем будет разница для владельца между статусом "Перезвонить" и статусом "Принят" с меткой "Перезвонить"?

**Comment by sabian** [comment]
Не знаю как сделано сейчас, но если при изменении статуса заказчику отправляется письмо, то безусловно метки будут полезными.

**Comment by chemezov** [comment]
Если в симпле заказы разбиты по табам, то мы можем делать это фильтрами, а фильтры вынести в правое меню, со счётчиком кол-ва товаров.

С первого взгляда у симплы выглядит логичней, ибо если смешать системные статусы и списковые, то обязательно возникнет потребность как-то реагировать на не системные статусы (например, при изменении статуса на "в доставке" отправлять письмо в магазин или на склад), и система может обрастать этими костылями. А при чётком разделении сущностей на статусы и метки этого можно избежать. Плюс метки (теги) позволят поставить несколько на 1 заказ (допустим, "клиент ждёт звонка" и "ожидает доставки").

**Comment by yupe** [comment]
Посмотрел другие движки. Там только статусы. Думаю, что сделать только статусы без меток. Статус у заказа только один может быть. Чтобы пользователя не путать и было меньше проблем с нотификациями при смене статуса. Если позже будет явная необходимость - добавим произвольные метки (как в постах блога). Как  считаете ?

**Comment by chemezov** [comment]
@yupe а что на счёт примера, который я привёл выше? Допустим, у заказа есть какой-то статус (в доставка, ожидает поступления, в обработке, новый, не важно), но к заказу нужно прицепить некий ярлык, типа "перезвонить клиенту", "ожидает оплаты" и пр. Т.е. типа дополнительные теги, только для заказов.

Есть инет-магзины, которые требуют предоплату, если товар доставляется в регионы, или предоплату за товар, который стоит дороже n-суммы. Статус у такого заказа всегда будет "Новый", но дополнительно можно прицепить теги. Связок может быть много, "новый" и "ожидает подтверждения от клиента", "новый" и "одидает предоплаты" и всё в таком роде. Разруливать это только статусами может быть не очень удобно, т.к. условий перехода из одного в другой может быть очень много.

Аналогия с гитхабом. Issue может быть открыт или закрыт, но для него вешаются разные метки, типа "ожидает проверки", "в обсуждении" и пр.

В любом случае, можно сделать эти метки, вместе с редактируемыми статусами, хуже не будет. Если метки не будут нужны - ими просто можно не пользоваться.

**Comment by sabian** [comment]
Присоединюсь к @yupe 
Есть куча запланированных задач, которые надо решить. Метки можно поставить в очередь на будущее.

**Comment by chemezov** [comment]
@sabian никто ж не говорит делать их прямо сейчас. Вопрос в том, нужны они вообще или хватит статусов.

**Comment by sabian** [comment]
> Вопрос в том, нужны они вообще или хватит статусов.

А вот этого я не знаю. С одной стороны вроде бы как и есть в них смысл, а с другой кажутся лишними.
Вспоминая свои заказы в различных магазинах (как крупных так и не очень) могу сказать, что мне всегда приходили оповещения о смене статуса заказа. Что-то вроде "Заказ оформлен ждем оплаты", "Оплата получена, заказ комплектуется", "Заказ передан в службу доставки". 
Т.е. получается, что если поставить статус "Комплектация заказа" значит по логике он уже оплачен и метка "Ожидает предоплаты" здесь лишняя.
Добавлю, что мне, как покупателю удобней и спокойней получить лишнее письмо со статусом заказа, чтобы знать, что с моим заказом что-то происходит, а не надеяться, что оплата получена и там кто-то поставил метку.
Но и полностью отрицать полезность меток я не могу. Может кто-то ими и будет пользоваться.

**Comment by yupe** [comment]
Давайте делать просто статусы. По меткам сделаем задачку позже если возникнет потребность.

**Comment by sabian** [comment]
> Давайте делать просто статусы.

Согласен. Мы опять сильно отклонились от курса. 
Начинаю делать статусы. С метками позже разберемся.

**Comment by ApexWire** [comment]
Я против возможности добавления статусов заказов, но за добавление меток к заказам.

Из за того что появиться возможность добавлять статусы заказов, то возникнут проблемы с:
* добавлением класса для статуса ( https://github.com/yupe/yupe/blob/master/protected/modules/order/views/orderBackend/index.php#L56 )
* возможностью завязать функционал на статусы заказов. Например выводить бухгалтеру только выполненные заказы

**Comment by yupe** [comment]
Системные статусы так и останутся, только вместо 0 будет 1. Внешне грид с заказами не изменится. Если нужно - позже добавим при добавлении статуса возможность указать цвет (так сделано в 90 % движках). Какие проблемы с отображением бухгалтеру ?
