### ISSUE TITLE
Генерация урл

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1879]
*Элиас в урл прописывает Й как ĭ а это запрещенный символ в результате чего появляется ошибка в url вида: site.ru/page/angliĭskiĭ, так же сюда попадают скобки, которые тоже вызывают ошибку: site.ru/salon-(kabina)

*все элиасы которые автоматом заполняются, когда вводим название страницы/товара

**Comment by yupe** [comment]
https://dl.dropboxusercontent.com/u/11188392/screenshots/yupe/store/1_issue_store__attr1.png

**Comment by chemezov** [comment]
Так же ещё может 2 символа идущих подряд заменить на дефис и в итоге в урле останется 2 дефиса.

Я давно писал код, для конвертации русского текста в латиницу, он чуть больше, чем сейчас в Юпи, могу попробовать перенести.

Для клиентской валидации лучше отказаться от этого плагина, т.к. в любом случае клиентсткая генерация и серверная может отличаться. По идее лучше забирать алиас аяксом с сервера. Но как это лучше сделать (в какой контроллер воткнуть) я не знаю.

**Comment by yupe** [comment]
@chemezov можно воткнуть в BackendController такой экшн, например

**Comment by chemezov** [comment]
Ок, берусь.

**Comment by yupe** [comment]
http://php.net/manual/en/class.transliterator.php

**Comment by chemezov** [comment]
@yupe я так понял для этого транслитератора ещё нужно расширение intl для php. По крайней мере у меня без него не завелось.

Нашёл ещё вот такую штуку https://github.com/2amigos/transliteration-helper. Выглядит интересно.

Что из них лучше использовать?

**Comment by yupe** [comment]
А наш  https://github.com/yupe/yupe/blob/master/protected/modules/yupe/helpers/YText.php#L26 чем не подходит ? Может допилить его слегка и все ?

**Comment by chemezov** [comment]
@yupe наш не фильтрует вообще ничего, пропускает скобки, двойные тире, и умеет транслит только с русского. Решение по ссылке, как я понял, с любого языка.

**Comment by yupe** [comment]
@chemezov ну так если есть ошибки - их стоит просто исправить. Или заменить реализацию нашего YText::translit, да хоть на вызов вот этого хелпера.

**Comment by mikspark** [comment]
еще тут можно почерпнуть https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseInflector.php#L443

**Comment by DarkCs** [comment]
на странице продукта в магазине не генерируется адрес, https://github.com/yupe/yupe/commit/08bb081561d597b16ed1a7e6982077281c7580b6 затерлись изменения этим коммитом

**Comment by yupe** [comment]
@DarkCs это я там чего-то поломал ?

**Comment by DarkCs** [comment]
вот в этом коммите хоть и не отображается, но в нем старая разметка влезла https://github.com/yupe/yupe/commit/08bb081561d597b16ed1a7e6982077281c7580b6

**Comment by yupe** [comment]
@DarkCs я не очень понял =0

**Comment by DarkCs** [comment]
на гитхабе почему-то не отображаются эти изменения, хотя дело было так:
![](http://i.imgur.com/vWvJ30U.png)
