### ISSUE TITLE
Не работает массовое удаление товаров (multiaction) не под админом

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#1881]
Если зайти в панель управления не под админом, отметить несколько товаров и попытаться их массово удалить, то получаем ошибку. 
В консоли браузера пишет про site.ru/backend/store/product/multiaction 403 (Forbidden)

http://youtu.be/gcNAQS9txJA

**Comment by sabian** [comment]
@yupe Проблема не только в каталоге. Сколько модулей посмотрел, ни где в правилах не указан multiaction.
Берусь.

**Comment by yupe** [comment]
@sabian ты имеешь ввиду multiaction не прописан в правилах для rbac ?

**Comment by sabian** [comment]
Да

**Comment by yupe** [comment]
Хорошо! Отлично!
