### ISSUE TITLE
Некорректная фильтрация спец.символов в title

### ISSUE THREAD

**Issue by git407** [yupe/yupe#1888]
При веб установке yupe 0.9.3 проставил кавычки в названии сайта - "Тест".
Вот результат на фронтенде:
`<title>&amp;quot;Тест&amp;quot;</title>`

**Comment by yupe** [comment]
http://php.net/manual/en/class.transliterator.php

**Comment by yupe** [comment]
https://github.com/yupe/yupe/issues/1879
