### ISSUE TITLE
Переключение языка в админке

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1891]
После переключения языка в админке по какой-то причине всегда редиректит на /backend/catalog/catalog (возможно мой локальный баг)

**Comment by sabian** [comment]
У меня тоже такое было, только перекидывало почему-то в управлением модулями.

**Comment by DarkCs** [comment]
меню кешируется, поэтому в ссылке на переключение языке остается та страница, которая была во время переключения языка в первый раз
