### ISSUE TITLE
Модуль "Страниц" тип "text" маловато будет..

### ISSUE THREAD

**Issue by i-coder** [yupe/yupe#1894]
Если сохранить такой текст в базе http://minexpert.marchenkosergey.ru/pages/regl то он сохранится частично.

**Comment by tmsk70** [comment]
Я давно исправил в таблице кажись на longtext, а то тоже резало

**Comment by i-coder** [comment]
Ну в версии 0.9.1 режет, я тоже уже исправил у себя.

**Comment by yupe** [comment]
Поправим, спасибо!
