### ISSUE TITLE
При установке модуля сделать "mb_strtolower" на имя модуля c папки install/

### ISSUE THREAD

**Issue by i-coder** [yupe/yupe#1898]
С толкнулся с проблемой при установке модуля (неизвестная ошибка), потратил 1 час на ликвидацию, оказалось что просто модуль был с Большой буквы http://joxi.ru/nAyLXXyI3EM72Z
(просто как предложение, у себя сделаю) работаю на OS X

**Comment by yupe** [comment]
Угу, каталог модуля и файл конфигурации модуля должны быть только в нижнем регистре.
