### ISSUE TITLE
Редактироввание постов

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1899]
При инлайн редактировании в админке (/backend/blog/post) записи блога (любого параметра, кроме тегов) слетают прикрепленные к ней теги. У себя пофиксил это старым "дедовским" способом:
 1. В модели Post добавил атрибут: public $_saveTags = false; Изменил немного метод beforeSave() Добавил в него:
```
 if (!$this->tags && !$this->_saveTags) { $this->removeAllTags(); } elseif ($this->tags && !$this->_saveTags) { $this->setTags($this->tags); } Вместо: if (!$this->tags) { $this->removeAllTags(); } else { $this->setTags($this->tags); } 2. И в YInLineEditAction в run() добавил: if ($this->model == 'Post' && $name != 'tags') $model->_saveTags = true;```

**Comment by mikspark** [comment]
еще кэш тегов бы сбрасывать при изменении статуса 
https://github.com/yupe/yupe/issues/1901
