### ISSUE TITLE
Упростить процедуру подключения комментариев

### ISSUE THREAD

**Issue by DarkCs** [yupe/yupe#1904]
Сейчас требуется слишком много действий, чтобы добавить комментарии на страницу.
Предлагаю:

1. Убрать реализацию интерфейса ICommentable у моделей https://github.com/yupe/yupe/blob/dev/protected/modules/blog/models/Post.php#L54
2. Убрать из relation подключение связей для комментариев https://github.com/yupe/yupe/blob/dev/protected/modules/blog/models/Post.php#L185-L205
3. В виджете подключения комментариев  передавать только модель (строкой) и id. Пара модель/ид будет полностью определять какие комментарии выводить.

**Comment by yupe** [comment]
@mikspark ты забил на задачку ? =)
