### ISSUE TITLE
Баги в комментариях

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1905]
### Перестали удаляться комментарии в мультиэкшене

Выделяю все, нажимаю "удалить", в ответе от сервера приходит "Удалено 1 записей!", но ни один коммент не удаляется. По одному удаляется нормально.

Попробовал удалить вообще весь код мультиэкшенов для комментов, всё заработало, но перестал сбрасываться кэш.

### После удаления комментариев остаётся 1 пустой

Воспроизвести можно, если удалить корневой коммент. Иногда такой коммент показывается на фронте, иногда нет. Не понял от чего зависит. (смотреть надо в БД, а не в админке)

### Через раз не даёт отправить комментарий

Чаще всего если не перезагружать страницу, и отправить коммент, к нему в ответ отправить ещё, сначала пишет "Не удалось добавить запись", после повторного нажатия всё отправляется. Бывает, что вообще никак не отправляется, только после перезагрузки страницы.

Ещё не совсем понял, почему в базе есть и parent_id и поля для nested sets?

**Comment by chemezov** [comment]
Первое, кажется, нашёл :)

https://github.com/yupe/yupe/commit/1ece5f255288054a581b061c25ac6fe932111736

**Comment by sabian** [comment]
Да, мой косяк. Хотел как лучше и не везде проверил. Сегодня сделаю как было.

**Comment by sabian** [comment]
Изменения откатил на всякий случай https://github.com/yupe/yupe/pull/1907, но на комментариях это ни как не могло сказаться, т.к. там свой multiaction https://github.com/yupe/yupe/blob/dev/protected/modules/comment/controllers/CommentBackendController.php#L203

**Comment by yupe** [comment]
Немного порефакторил. Базовый multiaction вернул к тму виду как сделал @sabian  (мне кажется так боллее логично). Удаление комментариев немного изменил. @chemezov должно теперь работать.

**Comment by chemezov** [comment]
@yupe, зачем? Я же специально делал #1718, чтобы отрабатывал afterDelete. Без него не будут, как минимум, удаляться картинки. Как максимум, там могут быть другие действия после удаления.

**Comment by yupe** [comment]
@chemezov какие картинки ? Имхо, но завязывать что-то серьезное на after* как-то плохо.

**Comment by sabian** [comment]
@yupe файлы изображений с диска не удаляются

**Comment by yupe** [comment]
@sabian каких изображений ?

**Comment by DarkCs** [comment]
если удалять модели без их загрузки, то не сработают подключенные поведения, а картинки, загруженные в модели у нас удаляются самим поведением для загрузки

**Comment by sabian** [comment]
@yupe в галерее например.

**Comment by yupe** [comment]
Понял, не подумал про это. Откатимс =)

**Comment by yupe** [comment]
После обновления:
1 Не работает ответ на комментарий  (если используется редактор)
2 Не работает добавление картинки в комментарий

**Comment by ApexWire** [comment]
у меня ответ на коммент пашет, не работает ответ когда изображение загружаешь

**Comment by chemezov** [comment]
у меня тоже ответ на коммент работает, но описанные в тикете проблемы остались, кроме первой.

Плюс не добавляются ни картинки, ни ссылки, если добавлять через Redactor. Т.е. всё добавляется, когда редактируешь, но при отправке всё режется.

**Comment by ApexWire** [comment]
> Плюс не добавляются ни картинки, ни ссылки, если добавлять через Redactor. Т.е. всё добавляется, когда редактируешь, но при отправке всё режется.

Нужно проверить параметр allowedTags. Может он в таблице settings прописан как пустой.
По умолчанию прописано: https://github.com/yupe/yupe/blob/dev/protected/modules/comment/CommentModule.php#L29

**Comment by chemezov** [comment]
Нет, с ним всё ок, но параметр "Удалять теги при выводе комментария, используя strip_tags() ?" стоит в "Да", и трёт всё. Я думал он учитывает параметр разрешённых тегов.

**Comment by chemezov** [comment]
Плюс по CTRL + Enter не отправляется коммент, раньше отправлялся, и сейчас хотелось бы. Сейчас это нажатие перехватывает redactor.

**Comment by ApexWire** [comment]
Обновил коммент выше)

> Я думал он учитывает параметр разрешённых тегов.

Нет. Разрешенные теги учитываются при валидации ( https://github.com/yupe/yupe/blob/dev/protected/modules/comment/models/Comment.php#L87 )

**Comment by ApexWire** [comment]
> Плюс по CTRL + Enter не отправляется коммент, раньше отправлялся, и сейчас хотелось бы. Сейчас это нажатие перехватывает redactor.

Записал в список "хотелок". Позже попробую реализовать. Сейчас предлагаю на этом не заострять внимание

**Comment by chemezov** [comment]
Надо бы чтобы учитывались, а то вообще не очевидно выходит :(

Я вижу это так: 
1) Параметр "резать теги" убрать и резать теги всегда. Или сделать его по-умолчанию включённым, т.к. вдруг всё таки кому-то понадобится.
2) Резать теги всегда с учётом параметра "разрешённые теги".
3) Делать всё это при сохранении, а не при показывании комментария. (как минимум потому что всё это сохраняется, но этого не видно, мало ли кто каких ссылок понапихал в комменты, как макимум пример: я запрещал ссылки, теперь решил разрешить и включил премодерацию комментариев. Получается, все старые ссылки у меня вылезут).

**Comment by ApexWire** [comment]
Так же записал с список "хотелок". Сейчас предлагаю на этом не заострять внимание. Так как данный вопрос не относиться к описанию задачи

**Comment by sabian** [comment]
У меня тоже не работает ответ на комментарий. Пишет "Комментарий пуст =(". Такое только с включенным редактором, с textarea такой проблемы нет.

**Comment by yupe** [comment]
Угу, подтверждаю слова @sabian точно такая же ошибка у меня в Chrome

**Comment by sabian** [comment]
Проблема в самом редакторе, его надо не копировать, а заново запускать, тогда все работает.
