### ISSUE TITLE
Изменение алгоритма ресайза изображений

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1906]
Давно уже перестал устраивать наш Thumbnailer, в виду ограниченности своего функционала, неправильного ресайза, доходящего до [абсурда](http://clip2net.com/s/3ecSrYu). К тому же нет возможности ресайзить картинку только по 1 стороне, что бывает необходимо на некоторых дизайнах (например pinterest-вёрстка).

Переписал функцию ресайза в Thumbnailer, заодно сделал сравнение текущего Thumbnailer с Imagine, CImage из Коханы (мы его раньше использовали), и нового метода.

![screencapture-localhost-yupe-public-site-test](https://cloud.githubusercontent.com/assets/2368902/6654711/9bf24ca4-caf7-11e4-8a84-6bc4e1be327c.png)

По сути изменения коснулись только апсэмплинга, и добавилась возможность указать только 1 из сторон. Остальное так или иначе почти всегда совпадает с Imagine (outbound mode).

Кто что думает? Если новый метод устраивает, буду готовить ПР.

**Comment by chemezov** [comment]
По ссылке с "абсурдом" я пытался ресайзить картинку до разрешения 200х200, но исхдник был чуть меньше, итоговый вариант получился 142х200, и через css был применён border-radius: 100%, в итоге получилось вот это, не совсем приятное изображение.

Проблема в том, что ресайзер воспринимает переданную ширину и высоту как максимально допустимые. И если одна из сторон меньше необходимой, то ресайза по этой стороне не будет. Из-за этого часто либо едет вёрстка, либо контент в этой вёрстке выглядит неадекватно (белые полосы от Imagine).

**Comment by yupe** [comment]
Предлагаю перенести на 0.9.5 В текущем релизе уже очень много изменений.
