### ISSUE TITLE
Модуль Каталог

### ISSUE THREAD

**Issue by dmitrychel** [yupe/yupe#1908]
При создании нового товара во вкладке Атрибуты нет полей для заполнения.
Во вкладке варианты некорректно отображаются поля, которые должны быть в Атрибутах

![image](https://cloud.githubusercontent.com/assets/11056918/6656746/ecf8a786-cb44-11e4-88ba-d991a3775876.png)

**Comment by sabian** [comment]
Нужно создать тип товара и ему присвоить нужные атрибуты, затем у товара во вкладке "Общие" выбираете нужный тип и у вас появятся атрибуты и варианты.

**Comment by sabian** [comment]
Задача все еще актуальна или вы разобрались?
