### ISSUE TITLE
конфигурационные файлы модулей

### ISSUE THREAD

**Issue by dmitrychel** [yupe/yupe#1909]
при добавлении новый правил роутинга они не распознаются системой
при попытке очистки кэша настроек через панель управления, в ответ приходит сообщение "Файл кеша-настроек не найден"

В чем может быть причина ?

**Comment by yupe** [comment]
Файл кеша настроек не создается при включенном YII_DEBUG. Отключите дебаг, когда сгенерится файл кеша, посмотрите есть ли там Ваши новые правила ?

**Comment by sabian** [comment]
А еще на главной странице на кнопке модуля появляется такая иконка
![refresh](https://cloud.githubusercontent.com/assets/434141/6683863/7f1ecf48-cc9c-11e4-93a5-da6d83e4fa01.png)
Надо по ней кликнуть

**Comment by dmitrychel** [comment]
Обновил, кликом по иконке.
Но созданное мной правило исчезло из конфига.

**Comment by yupe** [comment]
Вы смотрите в /protected/config/modules ? В какой файл Вы вносили изменения ?

**Comment by dmitrychel** [comment]
да, 
protected\config\modules\store.php

**Comment by sabian** [comment]
А надо modules/store/install/store.php

**Comment by dmitrychel** [comment]
Спасибо за помощь. 
Разобрался.
