### ISSUE TITLE
Галерея. Ошибка загрузки изображений

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#1918]
Перестала работать загрузка изображений. 
В массовой загрузке показывает процесс, а после появляется это
![gallery](https://cloud.githubusercontent.com/assets/434141/6769136/10e42cd2-d0a0-11e4-93e2-4079e9d53e84.png)
В одиночной загрузке пишет
```
Необходимо заполнить поле «Файл».
```

В ветке master все нормально.

PS.: Виноват этот ПР https://github.com/yupe/yupe/pull/1916. Если его откатить, то все работает, с ним нет.

**Comment by yupe** [comment]
Могу предположить, что это связанно с изменениями в работе с ресайзами картинок. Может @chemezov точнее скажет

**Comment by chemezov** [comment]
Какая-то странная ошибка. FileUploadBehavior добавляет required валидатор к полю "file". И раньше добавлял, и сейчас. Но при обычной загрузке и при массовой, это поле всегда пустое, т.к. данные приходят не в $_POST, а в $_FILES. Убрал добавление required валидатора, и перенёс проверку в file валидатор, надо проверить. Проверил на галереях и загрузке картинок, всё норм, обязательность поля валидируется, но "*" пропала из названия поля, т.к. required валидатора больше нет.
