### ISSUE TITLE
Привести к единому виду названия экшенов и вьюх

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1920]
Сейчас в некоторых модулях (catalog, news, gallery, page, возможно ещё) есть экшены, типа show, list и т.д., которые на самом деле view и index.

В Yii принято все CRUD операции и вьюхи называть как index/create/update/view/delete. Не стоит отходить от таких стандартов.

**Comment by serieznyi** [comment]
Если нет возражений, то готов этим заняться

**Comment by yupe** [comment]
@serieznyi оки!

**Comment by sabian** [comment]
@serieznyi От этой задачи вы тоже отказываетесь или уже делаете?

**Comment by serieznyi** [comment]
@sabian отказываюсь. Боюсь я поторопился.
