### ISSUE TITLE
Привести к единому виду названия полей

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1922]
Сейчас в разных модулях по-разному называются поля, типа create_time, update_time, publish_time, created_at, create_date, creation_date, change_date и подобные. Так же поля типа slug и alias.

Предлагаю привести их все к единому виду.

Для дат я обычно называю поля так:
- Если это DATETIME, то create_time, update_time, publish_time
- Если это DATE, то create_date, update_date, publish_date.

Можно выбрать такой вариант, можно придумать другой.

Для slug и alias предлагаю оставить slug.

**Comment by DarkCs** [comment]
тоже за create_time и update_time, CTimestampBehavior использует их по умолчанию
