### ISSUE TITLE
EAV в Юпи

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#1925]
Есть замечательный компонент https://github.com/yiiext/eav-behavior. Но для его работы нужно создать таблицу, подключить, указать нужные поля в safe (чтобы он их автоматом загружал и сохранял) и, насколько я знаю, по этим полям потом нельзя искать (только если присоединить табличку руками).

Нужен более простой компонент, который бы позволял:
1) Просто подключить поведение к любой модели, без создания отдельной миграции/таблицы.
2) Позволял бы нативно обращаться к полям модели, без использования доп. функций. Т.е. доп. поля должны сами загружаться в модель и сами сохраняться, пусть даже нужно будет их указывать в настройке поведения.
3) Должна быть возможность искать по ним, в методе search().
4) Должна быть возможность как-то их валидировать.

**Comment by graid2030** [comment]
Извините что врываюсь, но тут либо EAV либо не реляционная модель.

**Comment by yupe** [comment]
В модуле "Магазин", хранение атрибутов переделали, в универсальном расширении пока не вижу необходимости.
