### ISSUE TITLE
Убрать язык из URL

### ISSUE THREAD

**Issue by DarkCs** [yupe/yupe#1927]
Показ языка в адресе + убирание языка по умолчанию из него добавляет много проблем при генерации адресов. Убрав язык можно будет значительно упростить LangUrlManager.
Переопределение роутов (дописывание к ним параметров с языками) так же не позволяет использовать свои url rules (http://www.yiiframework.com/doc/guide/1.1/ru/topics.url#sec-9).

Переключение языков оставить на уровне cookies.

**Comment by chemezov** [comment]
Подозреваю, что это нужно больше для seo. Плюс поисковики вряд ли хранят куки, и для них сайт будет выглядеть как на одном языке.

Вариант "не убирать язык по умолчанию из урл", упростит задачу? Видел на многих сайтах, при заходе сразу перебрасывает на язык пользователя, типа http://example.com/ru/

**Comment by chemezov** [comment]
Вообще мультиязычность у нас получается странная. С одной стороны она не даёт возможность сделать разные сайты на разных языках, в рамках 1 системы. Т.е. чтобы и контент был на нужном языке, и шаблон и всё прочее. Только те модули, которые поддерживают мультиязычность. Но допустим, часто бывает, что и логотип у сайта на разных языках, должен выглядеть по разному, и хедер и футер и шаблоны и блоки контента и всё прочее. Есть cms-ки, где можно прямо создать "новый сайт", переключиться на него в админ панели и наполнять его контентом на нужном языке. Он будет иметь либо отдельный поддомен, либо поддиректорию, свои шаблоны, свои лэйауты (в yii это темы). У нас получается это всё можно реализовать только с помощью Yii:t().

Вообще, мне ещё не доводилось делать сайт с разными языками на Юпи, но кажется, что это проще реализовать отдельными поддоменами или поддиректориями на уровне веб сервера, и несколькими БД. Т.е. ставим 2 экземпляра Юпи, создаём 3 БД. 1 БД общая, для пользователей, настроек, ещё каких-то общих вещей, 2 другие для контента на разных языках. И разруливать это всё, с помощью dbConnection.

Нужен опыт людей, которые с этим сталкивались, именно на Юпи, какие проблемы были, как решали и т.п.

**Comment by DarkCs** [comment]
мне кажется, что 99% процентов (статистика не проверена) проектов вообще не используют многоязычность, а если уж проекту реально нужна такая вещь, то поддомены для разных языков были бы лучшим выбором (например, так сделано на http://www.engadget.com/). Ведь переключение языка это же просто замена надписей в меню (что, кстати, у нас все равно не работает), а замена контента. 

В итоге из плюсов присутствия языка в url - это то, что поисковик может сразу найти эту ссылку.
Из минусов - усложнение urlmanager, невозможность писать свои url rules (например, нельзя сделать доступными страницы модуля page по адресам вида /test.html).

Мне кажется, что слишком много костылей для фичи, которая слабо используется. Те, кому действительно нужен мультиязычный сайт смогут сделать и en.site.com, и site.com/en настройками вебсервера или переделываем под свои нужны url менеджера. Тем, у кого сайт работает преимущественно с одним языком, будет достаточно для пользователей и простого переключения языка на уровне приложения без указания языка в url.

**Comment by mikspark** [comment]
Поддержу. Фичу никогда не использовали, проще сделать на другом домене.

**Comment by fazliddin** [comment]
It is bad idea to store language only in cookie
