### ISSUE TITLE
Перенос на реальный web сервер

### ISSUE THREAD

**Issue by dmitrychel** [yupe/yupe#1947]
После переноса проекта путем копирования, в админке загружается меню, но вместо контента возникает ошибка 500
Use of undefined constant php - assumed 'php'

**Comment by yupe** [comment]
Что-то у вас с настройкой пхп. Попробуйте полностью почистить каталог runtime.

**Comment by mikspark** [comment]
там же в runtime есть application.log

**Comment by chemezov** [comment]
скорее всего где-то стоит `<? php` (с пробелом)
