### ISSUE TITLE
Виджет меню

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1948]
Здравтсвуйте! В общем вроде как нашел ошибку неприятную. Судя по описанию виджета темизовать его можно с помощью htmlOptions (вот пример из исходного кода):

```
Подключение виджета:
<?php
$this->widget('application.modules.menu.widgets.MenuWidget', array(
    'name' => 'top-menu',
    'params' => array('hideEmptyItems' => true),
    'layoutParams' => array('htmlOptions' => array(
        'class' => 'jqueryslidemenu',
        'id' => 'myslidemenu',
     )),
));
?>
```
На деле же ничего с ним не происходит. Даже если скопировать один в один этот пример. Не добавляется ни класс, на id... В общем вроде как баг.

http://yupe.ru/talk/viewtopic.php?f=2&t=856

**Comment by chemezov** [comment]
От себя добавлю, тоже столкнулся с подобной проблемой. Не мог добавить класс к ссылкам программно, он переписывается, вроде как в классе Menu.
