### ISSUE TITLE
Необходимо заполнить поле «Комментарий». 

### ISSUE THREAD

**Issue by ApexWire** [yupe/yupe#1950]
Нашел одну особенность комментариев
1) нажимаем на поле комментария. оставляем его пустым
2) нажимает на "Ответить"
3) поле "Комментарий" подсвечивается красным и выводиться сообщение "Необходимо заполнить поле «Комментарий»."

**Comment by sabian** [comment]
Что-то я не понял, а в чем странность?

**Comment by ApexWire** [comment]
Я не нажимал кнопку отправки комментария. Значит валидация формы не должна запускаться

**Comment by sabian** [comment]
А, я подумал "Ответить" обозначает отправку.

**Comment by mikspark** [comment]
Продублирую, с кнопкой ответить это никак не связано, это связано с потерей фокуса на поле - запускается клиентская валидация. 

Два варианта
1. отключить клиентскую валидацию
2. при клике по ссылке ответить вместе с очищением форму очищать ее от ошибок
