### ISSUE TITLE
Ссылка в документации

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1952]
Если перейти в раздел Документация и затем нажать "На сайт", то перебрасывает на /site/index, где нас поздравляют с установкой Юпи!

**Comment by sabian** [comment]
Добавлю, что мы попадаем не туда при включенном модуле "Главная".
И думаю 'target' => '_blank' здесь не нужно.

**Comment by yupe** [comment]
Исправлю.

**Comment by sabian** [comment]
Про сhangelog забыл
