### ISSUE TITLE
Название сайта

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#1957]
Заходим в админку и в настройках сайта пишем название, описание и ключевики. Переходим на страницу /site/index и видим, что описание и ключевики на месте, а вот вместо нашего названия - Yupe! - Site
Проверял на 0.9.4. Установка свежая, кроме настроек в админке изменений не было.

**Comment by yupe** [comment]
Исправлю

**Comment by chemezov** [comment]
Тайты прописываются в `$this->title`, а не в `$this->pageTitle`.

**Comment by yupe** [comment]
@chemezov как тогда оно работает ? Там два свойства ?

**Comment by chemezov** [comment]
@yupe ага, title используется в поведении, а pageTitle это стандартный тайтл. В принципе фолбэк на pageTitle есть, так что можно и так, но лучше в `title`.

**Comment by yupe** [comment]
Понял
