### ISSUE TITLE
Реализация фильтра каталога

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1960]
Реализовать фильтр для каталога товаров. По атрибутам, по стоимости и т.д.

**Comment by mustafo** [comment]
Есть какие-то продвижения?

**Comment by sabian** [comment]
Конечно есть, посмотрите выше, там 6 коммитов. В 0.9.8 можете посмотреть в магазине или здесь http://demo.yupe.ru/store

**Comment by yupe** [comment]
Да, сейчас фильтры работают, но не так как хотелось бы. 
После вот этой задачи https://github.com/yupe/yupe/issues/2105 фильтры тоже будем переделывать.
