### ISSUE TITLE
Проблема с авторизацией

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1971]
http://yupe.ru/talk/viewtopic.php?f=2&t=866

**Comment by EvanLoik** [comment]
Да, в этом смысле еще есть кое-какие недочеты.
Во-первых:
В MenuWidget, в файле main.php вызывается виджет "bootstrap.widgets.TbNavbar", где параметр brandUrl указан так:
```php
Yii::app()->hasModule('homepage') ? ['/homepage/hp/index'] : ['site/index']
```
Нужно указать вот так:
```php
Yii::app()->hasModule('homepage') ? ['/homepage/hp/index'] : ['/site/index']
```
То есть нужно поставить слеш вначале для того, игнорировать текущий модуль. Сейчас, например, попробуйте перейти по ссылке "редактировать профиль", а потом нажать на логотип. Он будет иметь такой url: /user/site/index

Так же, по умолчанию в модуле "меню", в пункте "главная" указан такой адрес: / (слеш)
Соответственно, получается такой массив для генерации url:
```php
["/"]
```
В связи с чем, возникают небольшие огрехи. Увидеть их можно, опять же, перейдя в редактирование профиля, и там пункт "главная" будет иметь такой url: /profile
Это потому, что этот массив ведет на текущую страницу.

Нужно, чтобы по умолчанию в пункте "главная" тоже стояло "/site/index".
Соответственно, массив получится такой:
```php
["/site/index"]
```

**Comment by sabian** [comment]
> Нужно, чтобы по умолчанию в пункте "главная" тоже стояло "/site/index".

Просто поставьте галочку "Обычная ссылка" и все будет нормально.

**На последней версии системы (0.9.6) воспроизвести ошибку не удалось.**
