### ISSUE TITLE
Смена аватарки

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#1977]
Смена аватарки. Если стоит галочка gravatar и загрузить аватар, тогда аватарка не подтянется. При загрузке необходимо снимать галочку gravatar. Это логическая ошибка, думаю стоит при загрузке автоматом снимать, если загружена аватарка.

**Comment by chemezov** [comment]
Может вообще имеет смысл убрать эту галочку? И автоматом, если нет загруженной аватарки, показывать gravatar?

**Comment by yupe** [comment]
Граватара может не быть у пользователя.

**Comment by chemezov** [comment]
@yupe ну его так и так не будет у него, если он не загрузил аватарку. А в граватар можно передать урл на дефолтную аватарку, если у пользователя нет аватара.

**Comment by yupe** [comment]
Если не загрузил аватарку и не поставил галочку "граватар" - отобразится дефолтная же.

**Comment by chemezov** [comment]
Если не загрузил и поставил голочку, тоже должна отобразиться дефолтная с сайта. Если её нет, отобразится дефолтная граватара. Или нет?
