### ISSUE TITLE
Все тот же rbac, не грузятся файлы (документы), если заходить не под админом

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2001]
Собственно из заголовка проблема ясна: в редакторе imperavi (redactor) пытаюсь добавить файл (doc/rar), но добавление происходит только под главным админом, под другими пользователями не получается.

**Comment by yupe** [comment]
Видимо для картинок исправили, для простых файлов нет - поправим.

**Comment by tmsk70** [comment]
Если для файлов сделать по аналогии с картинками, проканает, или там несколько иначе нужно?

**Comment by sabian** [comment]
Я добавлял доступы для картинок и для файлов. https://github.com/sabian/yupe/commit/670af56bbe0d6e765e51c8b4c9d7d46f71b7a761
Видимо это что-то другое.

**Comment by sabian** [comment]
`Ошибка 400! Невозможно определить CSRF.`

**Comment by yupe** [comment]
@sabian спасибо! Поправим!

**Comment by tmsk70** [comment]
после внесения этих правок:
https://github.com/yupe/yupe/pull/2010/files
в Redactor.php
видим вот такую картину при редактировании страницы: https://www.dropbox.com/s/p476tk55m7nr0s3/editorbag.jpg?dl=0

а если оставить запятую после скобки, в 51й строке, то еще и про csfr какая-то ошибка вовремя захода в админку.

**Comment by sabian** [comment]
Странно. У меня все нормально.
Спасибо, что сообщили. Проверю все еще раз.

**Comment by DarkCs** [comment]
@tmsk70, вы просто неправильно внесли эти правки, проверьте, или скобку не закрыли, или еще что-то

**Comment by tmsk70** [comment]
DarkCs, да вроде нет, просто копирую код.. посмотрите:
https://youtu.be/iGGY-BJhfzI

А у вас все получилось?

**Comment by sabian** [comment]
Вы вставляете код со занаками "+" вначале строки. Поэтому у Вас ничего и не работает.

**Comment by tmsk70** [comment]
Действительно.. смотрел только на код.. спасибо за помощь
А вот не знаете как удалить загруженные файлы, просто с ftp из public/files?

**Comment by sabian** [comment]
Если ничего не меняли, то public/uploads/files

**Comment by tmsk70** [comment]
Все понятно, спасибо за помощь
