### ISSUE TITLE
Проверить платежи

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2013]
http://yupe.ru/talk/viewtopic.php?f=11&t=883&p=3960#p3955

**Comment by sabian** [comment]
Добавлю сюда, чтобы не плодить похожие тикеты:
Создаем способ оплаты, например "Наличными курьеру", платежная система "Обработка вручную". При оформлении заказа мы выбираем этот способ и при клике на кнопку "Оплатить" ничего не происходит.
