### ISSUE TITLE
Редактирование роли в rbac

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#2015]
Если урл админки изменён с /backend на любой другой, то не будет работать редактирование роли в модуле rbac из-за вот такой строки в настройках:

```
    'rules'     => [
        '/backend/rbac/<controller:\w+>/<action:\w+>/<id:[\w._-]+>' => 'rbac/<controller>Backend/<action>',
    ],
```

Предлагаю убрать эту строчку и глобально разрешить передавать id не только как число, но и как строку с символами подчёркивания, тире, может ещё что-нибудь. Primary key вообще не всегда число, и не всегда даже строка a-z.

**Comment by DarkCs** [comment]
для переопределения пути необходимо еще дописать:
```
'/backend/rbac/<controller:\w+>/<action:\w+>/<id:[\w._-]+>' => false,
'/admin/rbac/<controller:\w+>/<action:\w+>/<id:[\w._-]+>' => 'rbac/<controller>Backend/<action>',
```
