### ISSUE TITLE
Не удовлетворительная composer зависимость для v0.9.5

### ISSUE THREAD

**Issue by serieznyi** [yupe/yupe#2035]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yupe/yupe v0.9.5 -> satisfiable by yupe/yupe[v0.9.5].
    - yupe/yupe v0.9.5 requires yiiext/taggable-behavior 1.5.* -> no matching package found.
```

Я так понимаю автор удалил этот пакет с getcomposer.org
Я не совсем понимаю как можно установить yupe v0.9.5 из composer при наличии этой проблемы

**Comment by yupe** [comment]
Этого пакета, насколько я помню, в Packagist никогда не было. Именно по этой причине добавлено вот это - https://github.com/yupe/yupe/blob/master/composer.json#L74

**Comment by yupe** [comment]
Только сейчас сделал clone проекта + composer install - все прошло корректно. Возможно, был какой-то "глюк" в composer или github.

**Comment by serieznyi** [comment]
Моя ошибка. Не просмотрел полностью файл composer.json. 
Видимо проблема у меня
