### ISSUE TITLE
Неправильная стоимость при просмотре заказа

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#2041]
При просмотре заказа к итоговой стоимости, в которой уже учтена стоимость доставки, прибавляется еще раз стоимость доставки.
![cart](https://cloud.githubusercontent.com/assets/434141/7609907/b6ea7a6a-f980-11e4-9c78-d28483740942.png)

**Comment by yupe** [comment]
Ага, видел этот баг тоже. Вообще у нас вот тут https://github.com/yupe/yupe/blob/master/protected/modules/order/models/Order.php#L566 Явный костыль. Не очень понятно для чего вычитать, когда в заказе можно хранить отдельно сумму заказанных товаров и сумму доставки. У нас поля для этого есть, но в "сумме заказа" у нас хранится сумма товаров + доставка =(
