### ISSUE TITLE
Кол-во и варианты

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2062]
Небольшое замечание по организации продаж. Параметр "Количество" должен быть определен в вариантах, потому что на складах списание номенклатуры идет именно по товарному предложению

**Comment by StWings** [comment]
А еще и может зависить от других атрибутов
например тип обуви:
Цвет: красный, белый, черный
Размеры: 35, 36, 37

Красные могут быть только 35 размера
а белый - 36 и 37 размеров
черный - 35, 36 и 37

ну и разумеется количество тоже должно быть

**Comment by StWings** [comment]
А еще и может зависить от других атрибутов
например тип обуви:
Цвет: красный, белый, черный
Размеры: 35, 36, 37

Красные могут быть только 35 размера
а белый - 36 и 37 размеров
черный - 35, 36 и 37

ну и разумеется количество тоже должно быть

**Comment by StWings** [comment]
А еще и может зависить от других атрибутов
например тип обуви:
Цвет: красный, белый, черный
Размеры: 35, 36, 37

Красные могут быть только 35 размера
а белый - 36 и 37 размеров
черный - 35, 36 и 37

ну и разумеется количество тоже должно быть

**Comment by yupe** [comment]
@StWings думаю, что настолько продвинутыми вариации мы делать не будем. Если нужны такие сочетания опций и отдельный учет - не проще ли завести такие позиции каталога отдельными товарами ?

**Comment by StWings** [comment]
можно отдельными, тогда смысл в вариантах пропадает, если можно выбрать только по 1 атрибуту

**Comment by yupe** [comment]
Варианты сделаны для самых простых случаев, хотя может и имеет смысл сделать их чуть лучше.

**Comment by yupe** [comment]
Будет реализовано через "дочерние" товары.
