### ISSUE TITLE
yii-seo

### ISSUE THREAD

**Issue by mikspark** [yupe/yupe#2065]
https://github.com/chemezov/yii-seo/blob/master/widgets/SeoHead.php#L51 тут всегда что-то будет, даже если не указать pageTitle для контроллера. 

https://github.com/yiisoft/yii/blob/master/framework/web/CController.php#L992

**Comment by yupe** [comment]
cc @chemezov

**Comment by chemezov** [comment]
Понял, посмотрю

**Comment by yupe** [comment]
@chemezov ну что там ?

**Comment by chemezov** [comment]
Поправил, https://github.com/chemezov/yii-seo/releases/tag/v1.0.4
