### ISSUE TITLE
Баг в проверке прав в YWebUser.php

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#2081]
Место: https://github.com/yupe/yupe/blob/master/protected/modules/user/components/YWebUser.php#L303-L320

Баг обнаружился, при попытке подключить модуль rbac и указать bizRule для одного из правил. Вылетала странная ошибка (array to string conversion), хотя всё было сделано под копирку из мануалов. Рытьём логов вышел на эти строчки. Ошибка заключается в том, что в оригинальном CWebUser в checkAccess передаётся 2 параметра: name, params. У нас передаётся name, userId, params. Из-за этого функция accessRules в любом контроллере передавала данные для bizRule как userId, из-за этого массив стал преобразовываться в строку при попытке запроса к БД.

Собственно, вопрос: зачем была унаследована эта функция и используется ли она где-то?

Как решение надо выпиливать эту функцию из YWebUser или переносить в другое место.

**Comment by yupe** [comment]
Как думаешь фиксить ?

**Comment by chemezov** [comment]
@yupe надо просто выпилить эту функцию. У себя в проекте выпилил, вроде ничего не поламалось. Я так понял создавалась она для модуля rbac (могу ошибаться, но так кажется), он работает тоже нормально, ещё посмотрю, проект запустим, если всё будет ок, то выпилю тут.
