### ISSUE TITLE
Оплата

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2092]
Добавлю сюда, чтобы не плодить похожие тикеты:
Создаем способ оплаты, например "Наличными курьеру", платежная система "Обработка вручную". При оформлении заказа мы выбираем этот способ и при клике на кнопку "Оплатить" ничего не происходит.

**Comment by StApostol** [comment]
Данную проверку (https://github.com/yupe/yupe/blob/master/themes/default/views/order/order/view.php#L215) можно убрать в данной теме, потому что она же вызывается в условие на уровень выше (https://github.com/yupe/yupe/blob/master/themes/default/views/order/order/view.php#L191)

**Comment by PushingUp** [comment]
Так а чего закрыли? Проблема-то осталась. К примеру создаем 2 способа оплаты "Наличными" и "Квитанция" с обработкой вручную. Создаем способ доставки и привязываем к нему оба способа оплаты.

**Comment by yupe** [comment]
@PushingUp обновитесь и пересохраните в админке все способы оплаты с ручной обработкой

**Comment by PushingUp** [comment]
Да, спасибо, теперь способы стали сохраняться. Единственно, стоит допилить в темах шаг после выбора способа оплаты. Потому что сейчас выбираем при оформлении способ оплаты и попадем на туже страницу без каких либо успешных сообщений для пользователя и запоминания выбранного способа оплаты (хотя в админке сохранится).

Думаю, ожидаемое поведение после выбора способа оплата - это зафиксировать способ оплаты без возможности дальнейшего переключения и скрыть кнопку оплатить + сообщение для пользователя, что заказ будет обработан вручную и с ним свяжутся менеджеры.

**Comment by yupe** [comment]
@PushingUp попробуем.
