### ISSUE TITLE
Кнопки фильтра товаров при отсутствии атрибутов

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#2093]
Кнопки фильтра товаров отображаются даже если нет атрибутов

![catalog](https://cloud.githubusercontent.com/assets/434141/8302640/c4d84a40-19a0-11e5-8b40-4056e357fab2.png)

**Comment by sabian** [comment]
Возможно этой задачей можно пренебречь, т.к. я добавлял только товары, а в реальных магазинах  как минимум будут категории и производители, так что там все время что-то будет отображаться. 
Слишком уж много проверок придется сделать, чтобы не показывать кнопки лишь в редких случаях.

**Comment by yupe** [comment]
Согласен.
