### ISSUE TITLE
Криво отображается пагинатор в магазине

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#2094]
**Главная магазина:**

![pager](https://cloud.githubusercontent.com/assets/434141/8315051/61537d22-19f6-11e5-98b5-57ccd42f43b1.png)

**Внутри категории:**

![pager_2](https://cloud.githubusercontent.com/assets/434141/8315058/70069048-19f6-11e5-8da5-33427c032b1a.png)

**Comment by yupe** [comment]
Хм http://demo.yupe-project.ru/store/ Как можно повторить ?

**Comment by sabian** [comment]
Пока не знаю. Кеш несколько раз почистил, у меня криво. Проверю еще раз.
Но все равно, на демо сайте они разные http://demo.yupe-project.ru/store/noutbuki

**Comment by yupe** [comment]
Ага там в одном месте TbListView в другом CListView =) Нужно везде сделать TbListView.
Попробую тоже как-то у себя воспроизвести.

**Comment by sabian** [comment]
Думаю дело в кол-ве страниц. Когда их мало, он встает рядом с товаром.
