### ISSUE TITLE
Ошибка постраничной навигации товаров в магазине при включении ajax

### ISSUE THREAD

**Issue by konstantin24121** [yupe/yupe#2104]
При включении ajax List отдает неверный url, заменяя в пути \ на %2F, после чего urlManager не может определить правило для пути. Удалось исправить ошибку дописав метод  в LangUrlManager, заменяющий символы в пути.
```
protected function fixPathSlashes($url)
    {
        return preg_replace('|\%2F|i', '/', $url);
    }
```
и вызвав его в методе
```
public function createUrl($route, $params = [], $ampersand = '&')
    {
        ...
        return $this->fixPathSlashes(parent::createUrl($route, $params, $ampersand));
    }
```
Может существует более грациозный фикс?

**Comment by DarkCs** [comment]
в dev ветке уже есть подобный костыль https://github.com/yupe/yupe/commit/b288de4932ca8ca4db494d6de95bd2130637e54d

**Comment by yupe** [comment]
@konstantin24121 мы пока не придумали =) Есть мысли ?
