### ISSUE TITLE
Сохранение аттрибутов

### ISSUE THREAD

**Issue by StWings** [yupe/yupe#2106]
Не отображатся опции атрибутов при редактировании:
Тип "Выпадающий список"
версия 0.9.7

**Comment by yupe** [comment]
Как можно повторить ?

**Comment by StWings** [comment]
Добавить новый атрибут тип "Выпадающий список"
Внизу добавить значения (как положено 1 значение в строке)
Ну и потом после сохранение повторно попытаться его редактировать, значений уже не будет
https://yadi.sk/i/23AB_2Ici2tXk

**Comment by StWings** [comment]
Варианты товара тоже не работают (атрибут создан)
https://yadi.sk/i/E8Nk7z5ni2tiq
