### ISSUE TITLE
Поиск пунктов меню

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2115]
https://www.youtube.com/watch?v=UP-XEX0cGA8&feature=youtu.be

(не могу понять почему не ищет пункты меню по фразе "решения", при том что другие пункты вроде без проблем находятся (например если ввести "нпа") )

**Comment by sabian** [comment]
У меня нормально ищет по этому слову. Не мог-ли там закрасться пробел? Если его поставить перед фразой, тогда ничего не находит.

**Comment by yupe** [comment]
Может сделать trim при поиске ?

**Comment by DarkCs** [comment]
трим не нужен, поиск идет ровно по тому, что ввели. А если я захочу искать по фразе, в которой есть предлог " в ", окруженный пробелами, а оно мне выдаст все слова с в.

**Comment by yupe** [comment]
Согласен, тогда закрываем.
