### ISSUE TITLE
в \protected\modules\yupe\components\WebModule.php public function getVisualEditor() - неправильно выдает выбранный в бэкэнде редактор (полностью игнорирует выбор)

### ISSUE THREAD

**Issue by dos0** [yupe/yupe#2133]
в \protected\modules\yupe\components\WebModule.php
public function getVisualEditor() - неправильно выдает выбранный в бэкэнде редактор и полностью игнорирует выбор

Не решило проблемы редактура массива:
    /**
     \* @var array - массив редакторов
     */
    public $visualEditors = [
        'redactor' => [
            'class' => 'yupe\widgets\editors\Redactor',
        ],
        'ckeditor' => [
            'class' => 'yupe\widgets\editors\CKEditor',
        ],
        'textarea' => [
            'class' => 'yupe\widgets\editors\Textarea',
        ],
    ];

**Comment by sabian** [comment]
Попробуйте поменять редактор в настройках нужного вам модуля, а не в настройках сайта.

**Comment by yupe** [comment]
@dos0 да @sabian кроме глобальной настройки редактора есть еще настройка редактора в каждом (почти) модуле. Проверьте.

**Comment by dos0** [comment]
Спасибо! 
ПС: Обратил внимание на редактор Ckeditor. Знаю в редакторе есть возможность подключения и использования kcfinder как файлового браузера. Подскажите есть ли предусмотренная возможность активировать kcfinder или надо все подключать самостоятельно?

**Comment by yupe** [comment]
@dos0 нет из коробки такого нет, с радостью примем пулл реквест

**Comment by yupe** [comment]
В версии 0.9.9 добавили загрузку картинок из CKeditor
