### ISSUE TITLE
Рефакторинг \yupe\components\ConfigManager 

### ISSUE THREAD

**Issue by serieznyi** [yupe/yupe#2137]
Хотел бы провести рефакторинг ConfigManager

Хочу поправить 
 - уровни доступа (ConfigManager::cachedSettings является public, но используется только внутри ConfigManager)
 - некорректные имена у методов, не отражающие то, для чего нужен метод (ConfigManager::merge)
 - избыточные комментарии. В принципе если корректно переименовать методы, то можно избавиться от комментариев
- docblocs

Так же думаю покрыть unit тестами данный класс

**Comment by yupe** [comment]
Я за. Ну главное, чтобы это не поломало работу.
 Что скажут @DarkCs @sabian @mikspark  @ApexWire ?

**Comment by sabian** [comment]
:+1:

**Comment by serieznyi** [comment]
Тогда стоит написать пару unit тестов. Как я понял вы их не пишете.

**Comment by yupe** [comment]
@serieznyi очень хочется их писать, но не всегда возможно по разным причинам и код кривой и времени нет, но с ними конечноже будет лучше +)

**Comment by ApexWire** [comment]
За

**Comment by serieznyi** [comment]
index.php
```
$confManager = new yupe\components\ConfigManager();
$confManager->sentEnv(\yupe\components\ConfigManager::ENV_WEB);
```

Есть причины, по которым вы не используете авто определение типа запроса с помощью ?
```
if (PHP_SAPI === 'cli') {
     $this->env = self::ENV_CONSOLE;
}
```

**Comment by yupe** [comment]
@serieznyi нет, думаю, так сложилось исторически.

**Comment by mikspark** [comment]
@serieznyi не уверен, что всегда будет 'cli'

http://php.net/manual/ru/function.php-sapi-name.php

**Comment by mikspark** [comment]
еще мне не нравится путаница с modules -> module, components -> component

**Comment by serieznyi** [comment]
@mikspark Я не совсем понимаю на что вы ссылаетесь в последнем сообщении

**Comment by serieznyi** [comment]
@mikspark  
"не уверен, что всегда будет 'cli'"

Да, я об этом знаю. Я обязательно учту это.

**Comment by mikspark** [comment]
@serieznyi
https://github.com/yupe/yupe/blob/master/protected/modules/yupe/install/yupe.php#L25
https://github.com/yupe/yupe/blob/master/protected/modules/yupe/install/yupe.php#L46
https://github.com/yupe/yupe/blob/master/protected/modules/yupe/install/yupe.php#L45

**Comment by yupe** [comment]
@mikspark так это де разные компоненты ) на уровне приложения и на уровне модуля

**Comment by mikspark** [comment]
@yupe это да, а нельзя и там и там сделать components?

**Comment by yupe** [comment]
@mikspark как разделить тогда глобальные компоненты модуля и его локальные ?

**Comment by mikspark** [comment]
@yupe вторые в ключе module

**Comment by serieznyi** [comment]
@mikspark Это не касается текущей задачи, потому то я и не понял о чем вы

**Comment by serieznyi** [comment]
Почему конфигурационные файлы модулей хранятся в приложении, а не в самом модуле? 
Я имею в виду базовые, а не пользовательские? 
В той же Yii2 это вполне допустимо и описано в самой документации в качестве примера.

**Comment by yupe** [comment]
@serieznyi в приложении хранятся только конфиги активных модулей. В момент активации модуля конфиг копируется в папку приложения и мерджится. В момент отключения модуля конфиг оттуда удаляется.

**Comment by serieznyi** [comment]
@yupe Да. Теперь вижу. Просто не ожидал, что конфиги модулей в install

**Comment by serieznyi** [comment]
Чем отличается код начинающийся [здесь](https://github.com/yupe/yupe/blob/master/protected/modules/yupe/components/ConfigManager.php#L234) от того, который начинается [здесь](https://github.com/yupe/yupe/blob/master/protected/modules/yupe/components/ConfigManager.php#L276)

Мне кажется это одной логикой. Я не прав?

**Comment by serieznyi** [comment]
В силу обстоятельств я не могу закончить рефакторинг. То что успел - отправил в pull-request.

**Comment by yupe** [comment]
Я так понимаю смысла мерджить нет ?

**Comment by serieznyi** [comment]
Мои изменения в https://github.com/yupe/yupe/pull/2140
К сожалению я мало что сделал.
