### ISSUE TITLE
Мелкий фикс по модулю homepage

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2141]
Ребят,
столкнулся с тем что если выбрать для отображения на главной обычную страницу, то она отображается, но есть недочет: если странице задан свой шаблон то всеравно используется вьюха с именем main.tpl

В общем в файле:
themes/default/views/homepage/hp/page.php
дописал:
<?php if ($page->layout): ?>
    <?php $this->layout = "//layouts/{$page->layout}"; ?>
<?php endif; ?>

и все стало как надо.

Внесите пожалуйста правку в последующие релизы.

P.S. Может она потребуется и для других файлов вроде posts.php

**Comment by yupe** [comment]
@tmsk70 поправим, спасибо!
