### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2142]
Не нашел тикет, поэтому задам вопрос здесь.
Ранее мы делали свою сортировку товаров дрэг-дропом, но потом в каком-то из релизов юпи она тоже появилась (только не наша), так вот, в бэкэнде дрэг-дроп работает (перенесенный товар остается там, куда его перетащили), но на фронтэнде ни чего не меняется (юпи 9.8).

Не знаю баг ли это, не доработка или просто дрэг-дроп в текущей реализации сделан для других целей.
Моя идея дрэг-дропа в бэкэнде заключалась в том, чтобы можно было перетащить какой-либо товар наверх и он поднялся бы в списке товаров и на фронтэнде.

**Comment by tmsk70** [comment]
Я уж думал вы все же дрэг дроп сделали малех для других целей))
