### ISSUE TITLE
Let's make yupe modules and components finely decoupled

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2150]
I see that yupe project has many professional mudules and components which may be used in other projects too. But those are tightly coupled into one project. For reusing them devlopers must extract them manually, but it makes getting regular updates almost impossible.

My suggestion is that yupe modules and components should be separated into multiple git repos and be installable via composer. Developers choose only what they need and can get updates very easily. If developer need to modify e.g. `user` module, he just inherits the module thus being sure that updates does not vanish his changes.

**Comment by yupe** [comment]
It will be done in the Yupe2 (Yii2 version).

**Comment by fazliddin** [comment]
Best example may be Sylius.org

**Comment by yupe** [comment]
@fazliddin yes, thanks! http://elcodi.io/ also very cool!

**Comment by fazliddin** [comment]
They both have flexible code architecture but main advantage of Yupe is it has better CMS features.

**Comment by yupe** [comment]
I hope that in the second version, we will improve architecture and cms features +)
