### ISSUE TITLE
Ошибка в виджете комментариев для гостя 

### ISSUE THREAD

**Issue by AleksandrovEugen** [yupe/yupe#2154]
При включенной возможности гостям оставлять комменты на странице, где есть виджет комментов выпадает следующая ошибка:

Действие CCaptchaValidator.action "captcha" задано неверно: действия не найдено в текущем контроллере

Вы используете Yii версии 1.1.16 , Yupe! версия 0.9.6 , версия php 5.5.9-1ubuntu4.11

**Comment by DarkCs** [comment]
Попробуйте, вот это должно было исправить ошибку https://github.com/yupe/yupe/commit/cdc6e5078a620f7fe9d2092a4fca1f8d5bc66495

**Comment by AleksandrovEugen** [comment]
Спасибо, помогло.
