### ISSUE TITLE
Подключение/отключение модулей

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2162]
Штука в следующем:
Отключаю модуль "Комментарии", вместе с ним отключается модуль "Главная страница"
Включаю модуль главной страницы, вместе с ним включается модуль комментариев и, до кучи, модуль блогов.
Немного не пойму зачем они, например, если я делаю сайт визитку и модуль блогов+комментариев мне не нужен, а вот главной страницей управлять требуется.

Юзаю юпи 9.8, в предыдущих версиях такого не замечал (не нужные модули были отключены и удалены).

Если так и должно быть, закрывайте тикет, придется мириться.

**Comment by yupe** [comment]
Сейчас модуль "Главная страница" может отображать или посты из блога или какую-то статичную страницу, соответсвенно модули "блог" и "страницы" необходимы для корректной работы.
