### ISSUE TITLE
Отрефакторить дефолиные картинки товара

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2169]
https://github.com/yupe/yupe/blob/dev/protected/modules/store/models/Product.php#L318
С такой инициализацией поведения не удается использовать модель в консольных приложениях, так как в консоли нет тем.

**Comment by ApexWire** [comment]
переместить defaultImage в папку модуля ( ./store/views/assets/ )

**Comment by yupe** [comment]
И как оттуда паблишить н фронт ?

**Comment by ApexWire** [comment]
угу

**Comment by yupe** [comment]
Ну это не очень гуд +)

**Comment by ApexWire** [comment]
Вариант 2: отключить imageUpload для консольного приложения)

**Comment by yupe** [comment]
Это костыль +) Вообще использование поведений для картинок - это костыль =(

**Comment by ApexWire** [comment]
Вариант 3: создаем файл class ProductConsole extends Product {}
Меняем функцию behaviors() { return [  ]; }

**Comment by mikspark** [comment]
Сделать базовую модель, сделать модель для web и console (или использовать базовую)

**Comment by mikspark** [comment]
Почему нельзя публиковать? Примерно так

`$module->getDefaultImage()`
может возвращать
```
return Yii::app()->getAssetManager()->publish(
    Yii::getPathOfAlias('application.modules.store.assets.image.default-image.png')
);
```
