### ISSUE TITLE
Social + Google

### ISSUE THREAD

**Issue by BuryYa** [yupe/yupe#2177]
Зимой уже была такая тема и она не закрыта.

При попытке залогиниться через Google выдает - 
Не определено свойство "application\modules\social\components\services\Google.email"

**Comment by sabian** [comment]
Такой тикет уже есть https://github.com/yupe/yupe/issues/1799

**Comment by BuryYa** [comment]
ну как бы да. но тот тикет от 11 января, я уже было подумал, что его никто не видел.
Стоит ждать решения?

**Comment by sabian** [comment]
Все открытые тикеты мы видим и их дублирование ни как не ускорит решение задачи.
Исправлять будем все, но назвать конкретных сроков не могу.

**Comment by BuryYa** [comment]
такс, ошибочку вашу порешал.
в Google.php возьмите $this->getAttributes() и будет вам счатье :)
