### ISSUE TITLE
Ошибки в купонах

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#2191]
1. В итоговой сумме оформленного заказа не учитывается скидка введенного купона.

2. Если купону задать параметр "Кол-во на одного пользователя", то при добавлении получаем ошибку: `CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'coupon_code' in 'where clause'.` вот здесь https://github.com/yupe/yupe/blob/dev/protected/modules/coupon/models/Coupon.php#L259

3. Не учитывается ограничение на количество купонов

**Comment by yupe** [comment]
@sabian я вроде починил работу купонов. @DarkCs @ApexWire @mikspark проверьте плз

**Comment by sabian** [comment]
:+1:
