### ISSUE TITLE
Некорректная проверка пути загрузки в FileUploadBehavior

### ISSUE THREAD

**Issue by AleksandrovEugen** [yupe/yupe#2202]
Создал новый модуль file на основе модуля image. Для него задал uploadPath="file" (по имени модуля для однообразия)

При сохранении нового айтема получатся такая интересная ошибка:
file() expects at least 1 parameter, 0 given

Конечно это не критично, но иногда, как в моем случае, значение переменной uploadPath совпало с именем функции php (file(), функция is_callable('file') возвращает true) и код ниже попытался её вызвать. Естественно, аргументов там нет, от чего и ошибка.  

Решение простое - переименовал значение uploadPath в 'files'. Но может в каком-то другом случае могут быть неочевидные ошибки.

 /**
     * @return string path of the upload directory.
     */
    public function getUploadPath()
    {
        return is_callable($this->uploadPath)
            ? call_user_func($this->uploadPath)
            : $this->uploadPath;
    }

**Comment by yupe** [comment]
Боюсь здесь проблематично как-то застраховаться от ввода названий стандартных функций. Или есть какие-то варианты ?
