### ISSUE TITLE
Язык по умолчанию 

### ISSUE THREAD

**Issue by TheBurningRed** [yupe/yupe#2203]
Юпи!/Модули/Юпи!
Языковые настройки

Во время установки выбрал язык по умолчанию Английский (При русском этот баг присутствует и воспроизводится аналогично)
После установки в настройках язык по умолчанию для сайта выбран Русский
При изменении языка по умолчанию на Английский перестанет работать

Выбираем в верхнем меню Английский страница загружается на английском, но при следующей перезагрузке страницы переключается обратно на русский

Судя по всему проблема в LanguageBehavior
После редиректа в данном месте теряется кука и становится обратно ru
пока не разобрался до конца
```php
// язык передан в url, но он равен дефолтному языку
if ($this->getUrlLang() !== null && $this->lang === false) {
    Yii::app()->getRequest()->redirect(Yii::app()->getHomeUrl() . $this->lm->getCleanUrl(Yii::app()->getRequest()->url));
}
```
Время жизни куки с языком стоит  session, но сессия не меняется после редиректа
По всей видимости проблема в пути по которому идет редирект или в компоненте Request.
```php
config/main.php
'session' => ['cookieParams' => ['httponly' => true]],
``` 
но на выходе кука  language имеет httponly  false, в отличии от остальных кукис

Мой проект поддерживает только англ. так что пришлось захардкодить его в методе бихейвиора
```php
public function handleLanguageBehavior($event)
    {
        $this->setLanguage('en');
             /* ... */
    }
```

**Comment by yupe** [comment]
Проблема была в debug-toolbar
