### ISSUE TITLE
Конфиг приложения

### ISSUE THREAD

**Issue by TheBurningRed** [yupe/yupe#2208]
Обнаружил проблему в ConfigManager.
самостоятельно решить не смог
Следуя документации добавил свой конфиг приложения в файл protected/config/project.php
```php
return [
    'components' => [
        'clientScript' => [
            'coreScriptPosition' => CClientScript::POS_END,
            'defaultScriptFilePosition' => CClientScript::POS_END,
            'defaultScriptPosition' => CClientScript::POS_READY,
        ]
    ]
];
```
который затем поступает в ConfigManager вот в это место вторым параметром
```php
//смерджим файл /protected/config/project.php
        return $this->mergeSettings(CMap::mergeArray($settings, require $this->basePath . '/config/project.php'));
```
но CMap его не мержит, на выходе итоге получаем только первый массив, соответственно пользовательские настройки указанные в project.php не работают

**Comment by yupe** [comment]
Секция должна называться "component" без "s" в конце. 
Тогда настройки из project.php мерджатся корректно.
