### ISSUE TITLE
Багрепорт: Jquery is not defined при чистой установке v 0.99, шаблон shop, набор компонентов "Интернет магазин"

### ISSUE THREAD

**Issue by userlond** [yupe/yupe#2246]
Установка командой:
php composer.phar create-project yupe/yupe:dev-dev yupe-project --no-dev --prefer-dist

В мастере установки выбираю компоненты "Интернет магазин" (устанавливается 12 модулей). Тему выбираю shop. 

При загрузке страницы в консоли браузера:
Uncaught ReferenceError: jQuery is not defined
Uncaught ReferenceError: $ is not defined

Собственно потерялся jquery :)

P.S. В backend jquery работает

**Comment by sabian** [comment]
Исправили, теперь должно все работать. И не забывайте при переключении тем очищать кеш и ресурсы.

**Comment by userlond** [comment]
:+1:
