### ISSUE TITLE
Fatal error: require(): Failed opening required 'D:\xampp\htdocs\yupe\public/../vendor/yiisoft/yii/framework/yii.php' (include_path='.;D:\xampp\php\PEAR') in D:\xampp\htdocs\yupe\public\index.php on line 30

### ISSUE THREAD

**Issue by vovochka86** [yupe/yupe#2249]
Ошибка возникла при установке Yupe.
Беглый осмотр показал что в папке vendors не было папки yiisoft со всеми необходимыми файлами и подпапками.
Yupe устанавливался посредством composer.

**Comment by yupe** [comment]
А установка прошла корректно ? Composer отработал ?

**Comment by vovochka86** [comment]
да, отработал

**Comment by yupe** [comment]
Скорее всего, у вас локальная проблема с xampp.
