### ISSUE TITLE
Баг верстки

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2253]
На странице просмотра товара, при ховере на прьевьюшке создается ::before с неуместными размерами, перекрывающими всё вокруг.
![snapshot](https://cloud.githubusercontent.com/assets/15049122/11274224/b6c1ed36-8ee8-11e5-8e7f-e805798be898.JPG)

**Comment by yupe** [comment]
Спасибо пофиксим, ну или примем PR +)

**Comment by syrexby** [comment]
Да я бы отправил, но боюсь, что там этот ::before может действительно быть для чего-то. :) Возможно, там задумывалась некоторая иконка(типа лупы), транзишном поверх превью накатывающаяся.. Иначе не совсем понимаю для чего еще могло это предназначаться. В дизайне, правда, не замечал ничего такого.

**Comment by yupe** [comment]
@sabian @DarkCs что думаете ?

**Comment by sabian** [comment]
Гляну, как освобожусь, если до того времени ни кто не починит.
