### ISSUE TITLE
Вертска блока "похожие товары"

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2256]
Нужно чтобы были горизонтально и работала каруселька

![2015-11-23 17-54-23](https://cloud.githubusercontent.com/assets/668145/11339596/50cca3c4-920b-11e5-906e-aced213ccbb6.png)

**Comment by sabian** [comment]
Это ты сам попортил
https://github.com/yupe/yupe/commit/23b9e25854d191087ac10a6ce60e9361d8f34c2e#diff-18167dd86c12d325adea9d5ef96d4ac1L15

Ты вынес эти классы сюда https://github.com/yupe/yupe/commit/23b9e25854d191087ac10a6ce60e9361d8f34c2e#diff-18167dd86c12d325adea9d5ef96d4ac1R9 но `CListView` добавляет еще один `div` с классом `items`, поэтому все портится.
Верни как было и будет все хорошо.
