### ISSUE TITLE
Закладки "Характеристики" "отзывы" в карточке товара переключаются не статично, область просмотра съезжает

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2264]
не сказал бы что баг, просто не очень удобно)
Неплохо реализовано это в Юлмарте 
http://www.ulmart.ru/goods/3562907#tab-instruction

При изменении закладок не меняется хэш адреса, а при попытке копировать его ( ссылку) копируется с хэшем.

**Comment by mikspark** [comment]
По мне у них как раз странная реализация, люди адреса обычно с адресной строки копируют, а не с кнопок, и с хэшем там только одна вкладка.

**Comment by yupe** [comment]
@mikspark ждем коммит +)))

**Comment by Divan4ik** [comment]
посмотрите примеры:
amazon
ozon 
````
сплошняком без закладок
````

Aliexpress
````
закладки href="javascript:void(0);"
````

wildberries.ru
ulmart.ru
````
ссылки с хешем, но переключение без изменения url
````

wikimart.ru
````
собственная реализация #/anchor=Description
закладки раскрываются мгновенно - если контента много медленно скроллит, что бы заголовок был вверху 
````

enter.ru 
````
что-то вроде bootstrap affix {fixed:top} урлов нет
````
