### ISSUE TITLE
Реализация подсказок на фронте

### ISSUE THREAD

**Issue by ApexWire** [yupe/yupe#2272]
Для реализации подсказок нужно добавить js код:
jQuery(document).ready(function ($) {
    $('.popover-help').popover({trigger: 'hover', delay: 500, html: true});
});

А чтобы подсказки отображались так же как в админке нужно добавить css:
/* POPOVER */
.popover {min-width: 300px;}
.popover-title {white-space: nowrap;}
.popover-content, .popover-content .body {width: 100%;}

**Comment by yupe** [comment]
Ммм.. это же особенности фронтально темы. Или ты про включение этих подсказок в дефолтной теме ?

**Comment by ApexWire** [comment]
Включение подсказок в дефолтную тему.

**Comment by sabian** [comment]
Все прекрасно работает:
```html
<button type="button" class="btn btn-default" data-container="body" data-toggle="popover" data-placement="left" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on left
</button>
```

```html
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="left" title="Tooltip on left">Tooltip on left</button>
```
