### ISSUE TITLE
На главной странице админки модули которых не должно быть

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2277]
Возникла проблема - на главной странице пользователь видит модули, которые для него не доступны (ограничены в rbac):
https://yadi.sk/i/0vVVpALYm3Br8

юпи 9.8
не уверен что это баг, возможно последствия после переноса сайта (проверьте у себя)

**Comment by sabian** [comment]
Тестировал на 0.9.8 и 0.9.9, баг не подтвердился.

Проверьте еще раз правила разделов, которые не должны отображаться. Может где-то стоит галочка и просто не заметили. Можно попробовать на эти разделы включить все, сохранить, а потом отключить.
