### ISSUE TITLE
Фильтр после поиска

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2286]
Делаю поиск по сайту http://demo.yupe-project.ru
Ввел слово - планшет
Получил результат.
Теперь хочу уточнить при помощи фильтра по цене...
Перекидывает на 
http://demo.yupe-project.ru/store/search?price[from]=20000&price[to]=30000
И получаю ошибку 404 - такая страница не найдена...
![002](https://cloud.githubusercontent.com/assets/98164/11792328/96720548-a2b6-11e5-93ae-2fe7367c3f49.jpg)

**Comment by yupe** [comment]
Спасибо, поправим.

**Comment by yupe** [comment]
Должно работать теперь -)

**Comment by loveorigami** [comment]
Да, спасибо. Работает...
Но словил один баг...
Вы форму удалили, а строку оставили
```
Yii::import('application.modules.store.components.AttributeFilter');
```
https://github.com/yupe/yupe/blob/53cf55d01c908b51fed8861b5407bb8ac2e91b02/protected/modules/store/widgets/SearchProductWidget.php#L3

а еще, если поиск не в магазине, то вываливается ошибка...
например в модуле pages
Fatal error: Class 'AttributeFilter' not found in X:\domains\_shop\nene.yii\themes\nene\views\store\widgets\SearchProductWidget\search-product-form.php on line 10

фиксится просто
Yii::import('application.modules.store.components.AttributeFilter');
