### ISSUE TITLE
Пропадают товары при сортировке

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2289]
Yupe 0.9.9 dev
Занес товары в категорию (часть заносил копированием)...
Товар принадлежит нескольким категориям.

![001](https://cloud.githubusercontent.com/assets/98164/11834278/e88413f0-a3db-11e5-83f0-e610e0fdf05e.jpg)

Вид из CategoryController.
Захожу в категорию на сайте - товары присутствуют

![0001](https://cloud.githubusercontent.com/assets/98164/11834140/9b950690-a3da-11e5-8610-563aaa75dc11.jpg)

Далее, не выбирая никаких фильтров, делаю сортировку. Товары пропадают. Выводится только два или 3
![002](https://cloud.githubusercontent.com/assets/98164/11834170/ecbb7d2e-a3da-11e5-87bd-74fc51cabcdf.jpg)
![003](https://cloud.githubusercontent.com/assets/98164/11834169/ecbb0a1a-a3da-11e5-8940-9a2a2e04fa26.jpg)

если закомментировать эту часть "category"
https://github.com/yupe/yupe/blob/dev/protected/modules/store/components/ProductRepository.php#L42

сортирует все хорошо.

Но тогда не работает фильтр по категориям )))

Сортировка же из productController, когда выводятся все товары, работает корректно.

На демке у вас этого бага не наблюдается, из-за того, что в категории всего три товара, или товар занесен в одну категорию...

**Comment by yupe** [comment]
Пофиксим, спасибо =)

**Comment by loveorigami** [comment]
Дополнительная информация )...
- Категория товара (Розы) , по умолчанию, принадлежала ко второму уровню.
![001](https://cloud.githubusercontent.com/assets/98164/11834825/ea96b9cc-a3e0-11e5-8dc8-6c2245a3f003.jpg)

- После того, как я для товара установил категорию первого уровня (Каталог цветов), а Розы отметил, как дополнительную, 
![002](https://cloud.githubusercontent.com/assets/98164/11834875/444e44bc-a3e1-11e5-84d2-52464d1163d9.jpg)
 стало так

![003](https://cloud.githubusercontent.com/assets/98164/11835002/41d37508-a3e2-11e5-84ec-293b4860a8c2.jpg)

Сортировка заработала корректно...

**Comment by loveorigami** [comment]
Хотел было написать, что все нормально, но сортировка заработала только в дочерней категории Розы.

Когда перешел на сайте в родительскую категорию - Каталог цветов, то товары также пропадают.

![004](https://cloud.githubusercontent.com/assets/98164/11835062/bc8da8ea-a3e2-11e5-94f0-ace4f436c684.jpg)


Т.е. можно сделать вывод, что товары пропадают в категории, отмеченной по умолчанию для товара...

**Comment by loveorigami** [comment]
На форуме, кажется, нашли в чем причина
http://yupe.ru/talk/viewtopic.php?f=2&p=12985#p12985
```
Сообщение pasha » Пн дек 14, 2015 7:34 am
Нашел ошибку вот в этом месте:
класс ProductRepository метод getListForCategory
написано:
$criteria->select = 't.*';
$criteria->with = ['categoryRelation' => ['together' => true]];

здесь связь один ко многим и соответственно при таком джойне будут задвоения, а пагинатор соответственно отсекет ему положенные строки и товаров на страницу выведется меньше.
```

**Comment by yupe** [comment]
@loveorigami посмотрите с последними правками ?

**Comment by loveorigami** [comment]
@yupe посмотрел. Сейчас работает все корректно.
Большое спасибо!

**Comment by yupe** [comment]
@loveorigami  Отлично! Спасибо за сообщение!
