### ISSUE TITLE
Не удаляется купон...

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2292]
В корзине можно добавить купон.
Можно его удалить, но на самом деле он не удаляется - нельзя его повторно добавить: пишет, что он уже добавлен.
Если перезагрузить страницу - действительно, он присутствует.

Ошибка кроется в том, что в массиве купонов код с маленькой буквы, а в array_diff заносится значение с большой через strtoupper.

https://github.com/yupe/yupe/blob/dev/protected/modules/coupon/components/CouponManager.php#L85

у себя поменял на mb_strtolower - удаляться начало все корректно и добавляться по новому...

**Comment by sabian** [comment]
Исправили. Проверьте пожалуйста.

**Comment by loveorigami** [comment]
Да, теперь работает )
