### ISSUE TITLE
Product -> category (dev)

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2306]
После рефакторинга в модели продуктов mainCategory на category
https://github.com/yupe/yupe/commit/3761410ab8b2da04f7012260b112ad259a91a816

в списке товаров не отображается название Главной категории
![123](https://cloud.githubusercontent.com/assets/98164/11976818/1eb48a8e-a98d-11e5-8feb-10dc14b73483.jpg)

Видимо - конфликт с этим
https://github.com/yupe/yupe/blob/dev/protected/modules/store/models/Product.php#L88

тут

https://github.com/yupe/yupe/blob/dev/protected/modules/store/models/Product.php#L325

**Comment by yupe** [comment]
Спасибо, поправим!
