### ISSUE TITLE
Группировка атрибутов-чекбоксов

### ISSUE THREAD

**Issue by alextravin** [yupe/yupe#2348]
Не уверен что я прав, но по-моему нет внятной группировки атрибутов-чекбоксов. Например, я надобавлял чекбоксов, которые относятся к одной группе. В итоге все чекбоксы разбросаны по фильтру, отсортированы по айдишкам просто
![bryowd0mlda](https://cloud.githubusercontent.com/assets/8221400/12449019/48342b76-bf8b-11e5-9e3a-5d3b7dadc515.jpg)
Как должно быть: чекбоксы, характеризующие одно и то же свойство товара, сразу группируются
![kvg-nkdlm0i](https://cloud.githubusercontent.com/assets/8221400/12449018/4832fa4e-bf8b-11e5-996d-f44542e28000.jpg)

Может быть надо всего лишь вьюхи копнуть самому хорошенько, и переверстать, не знаю. Сейчас буду копать

**Comment by yupe** [comment]
@alextravin нашли решение ?

**Comment by alextravin** [comment]
Уже не помню. Этот проект сдали уже, получили кэш, заказчик доволен

**Comment by yupe** [comment]
@alextravin и то дело =) Покажите проктик ? =)

**Comment by alextravin** [comment]
kedlar.ru, не судите строго, я не очень талантливый как прогер) 
Проблема кстати с CMenu - активные линки плохо определяет какие подсвечивать надо. В итоге я там ковырнул слегонца, и то еще плохо определяет. Надо тоже допиливать в цмске это дело

**Comment by alextravin** [comment]
жду коммента с вердиктом о том мог бы я попасть джуниором в amylabs

**Comment by ashkrobov** [comment]
Здравствуйте!

Ваше письмо получено. Постараюсь в ближайшее время на него ответить.


С Уважением, Шкробов Александр.
E-mail - shkrobov@yandex.ru
ICQ 404176085

**Comment by yupe** [comment]
Как только будет возможность - возьмем обязательно +)
