### ISSUE TITLE
По сайту проекта

### ISSUE THREAD

**Issue by alextravin** [yupe/yupe#2349]
Не юзер-френдли интерфейс. Адрес http://yupe-project.ru/ не запомнил, всегда пишешь просто yupe.ru. В свою  очередь, с yupe.ru ищешь мучительно ссылку на yupe-project.ru
Ссылка, ведущая на yupe-project.ru, должна быть на виду.

**Comment by yupe** [comment]
Все переехало на http://yupe.ru
