### ISSUE TITLE
Облегчение адаптации скина для пользователей-разработчиков

### ISSUE THREAD

**Issue by alextravin** [yupe/yupe#2350]
В новой теме оформления shop совершенно зря отказались от bootstrap. 
Начинаешь делать свой шаблон- поменял одну вьюшку основную в layouts. Далее весь диз слетел, потому что ты не подгрузил common.css Вместо каких-нибудь бутстраповых .col-md-4  во вьюшках магазина в теме shop прописаны .grid-module-9 , стили к которым хранятся в common.css 
Это неудобно. Используйте в актуальной скачиваемой теме оформления бутстрап, как в старой, и людям, которые используют бутстрап, будет в разы быстрее натянуть свой диз на двиг, за счет совместимости css.
В этом плане старая тема выигрывает у новой симпатичной.
- ускорится разработка на yupe у части юзеров
- ???
- PROFIT

имхо. сам столкнулся.

**Comment by dzhedai** [comment]
Тема shop предназначена для демонстрации возможности работы без компоненты bootstrap. Специально переписывались виджеты для демонстрации работы с компонентами yii
