### ISSUE TITLE
Уведомления о новых комментариях

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2354]
В админке есть такая опция.
Но на почту уведомления не приходят.
Более того, в контроллере не нашел части кода, отвечающего за это...

**Comment by yupe** [comment]
Модуль notify у вас активен ? Вот тут https://github.com/yupe/yupe/blob/master/protected/modules/notify/listeners/NotifyNewCommentListener.php отправка происходит

**Comment by loveorigami** [comment]
Ну это отправка автору комментария, как я понял.
А еще нужно отправить на e-mail, указанный в настройках модуля.
Вот тут https://github.com/yupe/yupe/blob/master/protected/modules/comment/CommentModule.php#L68


Аналогично, как в заказе
https://github.com/yupe/yupe/blob/master/protected/modules/order/controllers/OrderController.php#L58

Включил у себя модуль notify, проверил, все равно не приходит.

**Comment by sabian** [comment]
Ошибка не подтверждается. Уведомления отправляются на эмейл указанный в настройках модуля.
