### ISSUE TITLE
Уровень вложенности в комментарии

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2356]
Было бы очень полезно иметь возможность ограничивать уровень вложенности
maxLevel

Например - в магазине достаточно отзыва и ответа менеджера, чтоб один пост не растягивался на всю страницу в виде переписки...

Или показывать только 2 уровня, а остальное скрывать в спойлер

**Comment by yupe** [comment]
Это же довольно просто сделать на уровне шаблона. Такой вариант не подходит ?

**Comment by loveorigami** [comment]
Согласен.
