### ISSUE TITLE
Проблема с mime-типами и загрузкой файлов

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2358]
Друзья, не пойму что за бага у меня.. может в юпи.
На днях Андрей помог (не сохранялись mime-типы из-за типа данных varchar в базе, поменял на text, вроде стало сохранять, но опять есть проблема):
https://youtu.be/vpDh9D2uY0g

Не пойму, косяк на стороне сервера или я что-то не то делаю..
типы прописываю такие:

image/gif,image/jpeg,image/png,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/zip,application/x-rar,application/x-rar-compressed, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

расширения такие:
gif,jpeg,png,jpg,zip,rar,pdf,doc,docx,xls,xlsx

всё нужно для загрузки самых популярных типов данных..

Буду ооочень благодарен за помощь в тикете ибо наболело..

**Comment by mikspark** [comment]
https://github.com/yupe/yupe/blob/dev/protected/modules/yupe/models/Settings.php#L83

**Comment by tmsk70** [comment]
Огромнейшее спасибо, очень помогли

**Comment by mikspark** [comment]
@yupe может правда value текстом сделать? не мало 255 для значения?

**Comment by tmsk70** [comment]
мне не хватило под разрешения:
gif,jpeg,png,jpg,zip,rar,pdf,doc,docx,xls,xlsx

Кстати, может кто знает, почему один из xls-файлов может не загружаться (он Microsoft Office Excel 97-2003).
Большинству xls/xlsx хватает таких типов для загрузки:
application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

а вот тот не грузится, уже кучу попыток делал:
application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/xls, application/msexcel, application/x-xls, application/x-xls, application/x-dos_ms_excel, application/x-msexcel, application/x-ms-excel, application/x-excel, application/excel, application/softgrid-xls

**Comment by yupe** [comment]
@mikspark TEXT думаю много будет, может просто длину VARCHAR расширим ?
