### ISSUE TITLE
Экранирование кавычек в хлебных крошках.

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2359]
Нужно, наверное, как-то экранировать специальные символы в хлебных крошках, а то получается вот так..
![0](https://cloud.githubusercontent.com/assets/15049122/12725875/d782e9d6-c925-11e5-9c0b-0f54d55edb2e.PNG)

**Comment by yupe** [comment]
https://github.com/yupe/yupe/commit/0883804c04620935efc7c3fea6f98acf3026f5c9#diff-56effe8c6cd2ff00b2cfd629777804f4R146
