### ISSUE TITLE
Связь категорий с группами аттрибутов

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2365]
В версии 9,8 в типах аттрибуты можно было привязать к категории
![0001](https://cloud.githubusercontent.com/assets/98164/12822607/dfc560dc-cb79-11e5-9235-2aa2c0ecdfce.png)
На фронтенде обнаружил один баг (напишу ниже).

Скачал версию 9.9. Зашел в типы, привязки к категориям не обнаружил...

**Comment by loveorigami** [comment]
Собственно, о самом баге...
Итак, есть категория Подарки, к которой привязан тип РАЗМЕР
И категория - цветы с привязанным типом ЦВЕТ

Логично, что находясь в категории Подарков я не должен выбирать среди ЦВЕТА, а только РАЗМЕР.

Сейчас же получается в любой категории выводятся ВСЕ фильтры.
![002](https://cloud.githubusercontent.com/assets/98164/12822813/d0c05410-cb7a-11e5-8e0d-96e69428f35b.png)

**Comment by yupe** [comment]
> Скачал версию 9.9. Зашел в типы, привязки к категориям не обнаружил...

 да, в 0.9.9 убрали это. Реализация была совсем кривая и нигде не использовалось.

>  тип РАЗМЕР
- странный тип ) 
Я бы сделал два типа "Букет" и "Подарок" у каждого из них свой набор атрибутов.

Привязки фильтров к типам/категориям нет, да. 
Пока можно только "ручками" изменить параметры вызова виджета, который формирует фильтр.
По дефолту он выводит все атрибуты - но можно передать списком какие именно выводить.

**Comment by loveorigami** [comment]
Тип РАЗМЕР - это все условно, что в голову пришло ))). Воспроизводил в версии 9,9, надяесь, что там работает вывод типов для каждой категории. А оказалось что этот функционал вообще "выпилили" )))

Я хотел показать, что для категории Букеты на фронтенде должны выводится те типы, которые привязаны к данной категории...

А то получается, в категории букеты наряду с подбором цвета будут выводится скажем, аттрибуты "размер диагонали" и "количества ядер", которые нужны для категории Компьютеры.

>По дефолту он выводит все атрибуты - но можно передать списком какие именно выводить.
Тогда на практическом примере:
На сайте очень много разных категорий.
Есть одна главная - БУКЕТЫ, в которой много подкатегорий (Розы, Ромашки.....)
Для них создан тип - ДЛЯ БУКЕТОВ с аттрибутом - количество цветов

Есть категория СМЕШАННЫЕ БУКЕТЫ, для которой важен аттрибут комплектация (LITE, Standart, PREMIUM)

Так вот, сейчас выводятся все типы в любой категории (и количество цветов, и комплектация)

Если я нахожусь в букетах и выбираю LITE, у меня ничего не выводится... 
Или в смешанных букетах и выбираю 5 цветов.

Пользователь то не знает, что эти типы для разных категорий. Он думает, раз они тут выводятся, значит по ним можно искать...

Вот чтоб его не вводить в заблуждение - и нужно убрать те типы, которые не привязаны к категории.

>По дефолту он выводит все атрибуты - но можно передать списком какие именно выводить.
Применительно к отдельно взятой категории, как можно?
Смотрю на код, не пойму...
https://github.com/yupe/yupe/blob/master/protected/modules/store/widgets/filters/AttributesFilterWidget.php#L6

**Comment by yupe** [comment]
На данный момент это можно сделать только через правку шаблона, вот тут https://github.com/yupe/yupe/blob/master/themes/shop/views/store/product/index.php#L24
'*' - значит будут выведены все атрибуты (это главная страница каталога)
Вам вот здесь - https://github.com/yupe/yupe/blob/master/themes/shop/views/store/category/view.php#L27 (индексная страница категории) вместо "*" нужно указать необходимые атрибуты. Пока можно просто "захардкодить" где-то маппинг "категория" ---> "список атрибутов" и все. Пойдет на время ? =)

**Comment by loveorigami** [comment]
в 9,8, конечно, было лучше... Выбрал тип и для какой категории... дочерние автоматом наследуют родительский. Все наглядно.

А тут придется каждую описывать...
Сейчас они только набивают категории, а их уже более 100. 
Привязку надо делать по id, slug будут менять сеошники
Т.е. получится
```
[
  1 => 'podarki',
   2 => 'buket',
.......
  48 => 'podarki',
.......
  100 => 'buket',
]
```
и править с каждой новой категорией.
так?

**Comment by yupe** [comment]
Скорее так:
`[
    <cat_id> => ['attr_1', 'attr_2'....]
]`

В 0.9.8 вы это реально использовали ? Там все выбранные каегории хранились сериализованными в бд. Ни выборок ничего нельзя было сделать _+)

**Comment by loveorigami** [comment]
Не, не использовал, бо не работало ))).
Об этом собственно, и issue.

Подумал, раз есть привязки, значит они должны как-то работать ))

**Comment by yupe** [comment]
Они вообще для другого делались ) В карточке товара когда вибираете "Тип товара" - категории товара должны были проставится автоматом. Но Ваша задача интересная, стоит подумать как ее решить.

**Comment by loveorigami** [comment]
Вопрос, как мне кажется, насущный для любого магазина...
Например

Холодильники - http://comfy.ua/for-the-kitchen/large-appliances/refrigerator.html
Фены - http://comfy.ua/for-the-kitchen/beauty-and-health/hair-dryer.html

Разные типы аттрибутов и подбор по ним

**Comment by loveorigami** [comment]
![001](https://cloud.githubusercontent.com/assets/98164/12842526/6ca2c366-cc04-11e5-9310-fe5d294389df.jpg)
![002](https://cloud.githubusercontent.com/assets/98164/12842527/6ca4a596-cc04-11e5-8d63-d88da6565ed8.jpg)

**Comment by yupe** [comment]
Т.е. нам по идее достаточно сделать связку "Категория" --> "Группа атрибутов" так ?

**Comment by loveorigami** [comment]
Получается, что да...
И она в 9,8 была ))), как подумалось сперва

**Comment by loveorigami** [comment]
И наверно, с возможностью сортировки... чтобы ТИП ФЕНА был выше, чем Потребляемая мощность...

**Comment by yupe** [comment]
Нет, в 0.9.8 была связка "Типа товара" и категории. Сдесь же нам тип ненужен получается, насколько я понял. Так как в категории "Холодильники" может быть товар с типом "Холодильник" и товар с типом "Сумка холодильник".

**Comment by loveorigami** [comment]
+ лимит ограничений по фильтрам (аттрибут ВЫСОТА в холодильнике). Тут лимит 5, а далее - показать все.

**Comment by yupe** [comment]
что ? =)

**Comment by loveorigami** [comment]
![002](https://cloud.githubusercontent.com/assets/98164/12842815/315265e4-cc06-11e5-8703-1ab531f3d16c.jpg)

Если список очень большой, чтоб не выводить его полностью

**Comment by yupe** [comment]
Это уже детали реализации конкретной темы оформления.

**Comment by loveorigami** [comment]
Да, действительно )))... Тогда остается сортировка на повестке дня )

**Comment by yupe** [comment]
Да, сортировка атрибутов в пределах группы и связь категорий с группами +)

**Comment by Divan4ik** [comment]
Присоединяюсь, Связь категорий с группами атрибутов -  важная штука
