### ISSUE TITLE
Не работает фильтр категорий в связанных товарах

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2366]
Yupe 9-8 - 9.9 (чистая)
В продукте не работает фильтр категорий в связанных товарах
Выбираю категорию, она сбрасывается - фильтрация не происходит
![003](https://cloud.githubusercontent.com/assets/98164/12823169/a30701da-cb7b-11e5-8c8c-d456986c1ab2.png)

**Comment by yupe** [comment]
https://github.com/yupe/yupe/commit/9e5bcbe807c8965699e2268afe732081acf2cd8d#diff-cb826ab42226b583f888e8d037303a83R173
и 

https://github.com/yupe/yupe/commit/9e5bcbe807c8965699e2268afe732081acf2cd8d#diff-2c70ebdf02fd089faa77cf16d77a8224R155
