### ISSUE TITLE
Поиск по имени в гриде продуктов

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2367]
Не работает поиск по имени в гриде продуктов
Напрямую сделал запрос
http://yupe.dev/backend/store/product?Product[name]=yupe

получил

CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous. The SQL statement executed was: SELECT COUNT(DISTINCT `t`.`id`) FROM `yupe_store_product` `t` LEFT OUTER JOIN `yupe_store_category` `category` ON (`t`.`category_id`=`category`.`id`) LEFT OUTER JOIN `yupe_store_product_category` `categoryRelation` ON (`categoryRelation`.`product_id`=`t`.`id`) LEFT OUTER JOIN `yupe_store_category` `categories` ON (`categoryRelation`.`category_id`=`categories`.`id`) WHERE (name LIKE :ycp0). Bound with :ycp0='%yupe%'

**Comment by yupe** [comment]
На текущей версии такой проблемы нет http://www.awesomescreenshot.com/image/968482/84b92c924fa7764dbffa12c5194c0221

**Comment by yupe** [comment]
https://github.com/yupe/yupe/blob/dev/protected/modules/store/models/Product.php#L307 вот тут решение
