### ISSUE TITLE
Модуль Notify

### ISSUE THREAD

**Issue by mikspark** [yupe/yupe#2369]
Компонент здесь https://github.com/yupe/yupe/blob/dev/protected/modules/yupe/components/Notify.php

Модуль здесь https://github.com/yupe/yupe/tree/dev/protected/modules/notify

Конфиг здесь https://github.com/yupe/yupe/blob/dev/protected/modules/user/install/user.php#L41

Порефакторить.

**Comment by yupe** [comment]
@mikspark что с задачей делаем ?

**Comment by mikspark** [comment]
Я порефакторю
