### ISSUE TITLE
Добавление товаров в Блоки контента

### ISSUE THREAD

**Issue by samox1n** [yupe/yupe#2383]
Не вручную с последующей правкой кода, цен и остального, а выбрал товар и добавил. Название, описание и прочее подхватывается автоматически. Если какие-то данные не нужны, например, можно удалить их в коде.

Тема shop

**Comment by yupe** [comment]
Как это должно выглядеть в админке с Вашей точки зрения ?

**Comment by samox1n** [comment]
Блок контента / создание
Тип: товарный блок

Ввести ограничение на кол-во добавляемых товаров, например максимум 5.
Пользователь добавляет любые пять товаров из опубликованных в магазине и публикует блок.

Стили для такого блока и расположенных в нём товаров придётся прописать отдельно.

Если цена меняется в товаре, то и в блоке она меняется тоже, как и всё остальное связанное с этим товаром.

Как-то так.

**Comment by yupe** [comment]
Т.е. это просто некие "Наборы" товаров, которые пользователь через виджеты может встроить в шаблон ?

**Comment by samox1n** [comment]
Да, и видимо так можно сделать в Юпи?

**Comment by yupe** [comment]
Если знаете Yii - можно =)

**Comment by sabian** [comment]
Да, виджет `ProductsFromCategoryWidget`. Создаете служебную директорию, добавляете туда нужные товары, затем указываете эту директорию при вызове виджета.
Шаблоны и стили меняете по своему усмотрению

**Comment by samox1n** [comment]
Спасибо, попробую

**Comment by syrexby** [comment]
Подскажите, а как можно добавить служебную директорию? Через админку?

**Comment by sabian** [comment]
@syrexby Да, это обычная категория, только ставите статус "Черновик" чтобы не отображалась на сайте

**Comment by syrexby** [comment]
Хм, не вышло.
`<?php $this->widget('application.modules.store.widgets.ProductsFromCategoryWidget', ['slug' => 'new']); ?>`
Этот виджет выводит товары только если категория "new" опубликована.

**Comment by sabian** [comment]
Ну так вы создаете категорию, например "Служебная" у нее статус черновик. В ней уже создаете опубликованную категорию "Новинки" и выводите товары из нее

**Comment by sabian** [comment]
@yupe Такое решение устраивает или все же нужно что-то еще реализовать?

**Comment by yupe** [comment]
Думаю этого пока хватит.
