### ISSUE TITLE
Спец.предложение или новинка

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2385]
Друзья,
сейчас в юпи есть галочка "Спец.предложение"
хорошо бы рядом с ним добавить чекбокс "Новинка" и "Популярное", чтобы вешать такие бейджи
https://yadi.sk/i/NXH86LxxotTut

Просто наиболее часто используются: Новинка, Хит, Hot (спец.предложение).

**Comment by Divan4ik** [comment]
Присоединяюсь, для маркетинга всегда важно)

Мы себе сделали миграцию

``` php
class m160330_143617_alter_product_table extends yupe\components\DbMigration
{
	public function safeUp()
	{
		$this->addColumn("{{store_product}}", "is_new", "tinyint not null default '0'");
	}

	public function safeDown()
	{
		$this->dropColumn("{{store_product}}", "is_new");
	}
}
```

и поправили модель Product\шаблон _form\messages ru_Ru\ продублировав is_special на is_new

Но по хорошему, если и разрабатывать функционал, то равняться надо на http://www.ulmart.ru/catalog/DVR?sort=0&viewType=0&rec=true

Вот уж у кого бейджов, так это у них)

**Comment by yupe** [comment]
Что мешает это сделать через динамические атрибуты ? Сделать группу атрибутов типа "Специальные типы" и туда добавить хоть 20 таких признаков ?

**Comment by Divan4ik** [comment]
мешает потрясающая удобность использования :)

``` php
<?php if ($product->isNew()): ?>
       <span class="badge badge__hot">Новинка</span>
<?php endif; ?>
<?php if ($product->isSpecial()): ?>
        <span class="badge badge__spec">Акция!</span>
<?php endif; ?>
```

**Comment by yupe** [comment]
@Divan4ik а написать вот так:
`if($product->attribute('is_super_discount')){....}` ? Так хуже ? )

**Comment by Divan4ik** [comment]
все "щикарно" работает, даже баттхерт испытал из-за внедрения ненужного кода, только вопрос: как лучше всего решить эту проблему?
![detex line magnum 55 mono](https://cloud.githubusercontent.com/assets/3591619/14559918/d1a5e9f4-0314-11e6-8eff-d287f030a1e6.png)

стоит ли вынести такие бейджи-статусы в отдельную группу атрибутов и исключить их в выводе?
или есть другой способ?

**Comment by Divan4ik** [comment]
D'oh! спасибо

**Comment by Divan4ik** [comment]
появился вопрос:

создал в yupe_store_attibute
![screenshot-propaj net 2016-06-23 12-49-50](https://cloud.githubusercontent.com/assets/3591619/16299088/240de784-3941-11e6-9737-27ac40a32135.png)
в \themes\shop\views\store\product\_item.php добавил
``` php
<?php if ($data->attribute('is_super_hot')) : ?>
            <span class="badge badge__hot">Новинка</span>
        <?php endif; ?>
```
перешел на /store/product/index - вижу кракозябли, в логах появляется

>  [Thu Jun 23 13:53:10 2016] [error] [client 217.69.212.124] PHP Fatal error:  Call to a member function isMultipleValues() on a non-object in /var/www/webmaster/data/www/domain.net/protected/modules/store/models/Product.php on line 681

вопрос: Как вывести или проверить атрибут в списке товаров (тизере)?

**Comment by yupe** [comment]
Это на последней версии ?

**Comment by Divan4ik** [comment]
архив yupe-dev.zip от 20.06.2016

**Comment by yupe** [comment]
Атрибут "is_super_hot" какого типа ?

**Comment by Divan4ik** [comment]
чекбокс

**Comment by yupe** [comment]
На локальной версии не повторяется. Судя пошибке, очень похоже на то, что у вас удалился атрибут а его значения у товара остались.

**Comment by Divan4ik** [comment]
сделал 
``` mysql
delete from yupe_store_product_attributevalue where attribute_id = 91;
```
Ошибка осталась. Если убираю блок:
``` php
<?php if ($data->attribute('is_super_hot')) : ?>
        <span class="badge badge__hot">Новинка</span>
<?php endif; ?>
```

то все ок, очень странно

**Comment by Divan4ik** [comment]
``` mysql
SELECT * FROM yupe_store_product_attribute_value WHERE `id` NOT IN (SELECT id FROM `yupe_store_type_attribute`)
```
вернул 0 строк

**Comment by Divan4ik** [comment]
Блин... надо сделать кнопку в админке который выполнит mysql.
``` mysql
DELETE FROM yupe_store_product_attribute_value WHERE `id` NOT IN 
    (SELECT id FROM `yupe_store_attribute`)
```
Специально для слоупоков вроде меня.

**Comment by yupe** [comment]
У вас видимо БД от какой-то старой версии юпи еще, сейчас при удалении атрибута - все подчищается.
