### ISSUE TITLE
Не выводятся flash сообщения в комментариях

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2400]
После добавления комментария не выводятся флеш сообщения. В модуле feedback сообщения выводятся.

Если просмотреть в консоли - то выводится 2 результата
1. Успешное добавление - сообщение в data ['message'] - может поэтому и не выводится?
2. Ошибка, что не заполнены поля имя и e-mail
![0001](https://cloud.githubusercontent.com/assets/98164/13378525/6c73e820-de1a-11e5-8710-3408f53c3d51.jpg)

3. В feedback флеш сообщение находится в data
![0002](https://cloud.githubusercontent.com/assets/98164/13378551/2d750f86-de1b-11e5-973f-ba830003b7d7.jpg)

**Comment by sabian** [comment]
Не подтверждено.
![comments](https://cloud.githubusercontent.com/assets/434141/15270167/4bf90b30-1a1e-11e6-96b4-497a10d41810.png)
