### ISSUE TITLE
В регистрации пользователя информация о логине и пароле

### ISSUE THREAD

**Issue by ilvval** [yupe/yupe#2405]
При регистрации пользователя необходимо отправить сообщение в емайл с информацией логина (при автогенерации "логин для входа" в виде e-mail) и пароля.
Возможно это при успешной активации.

**Comment by tmsk70** [comment]
Ну это как бы логично.
Разве в модуле магазина юпи этого нету? А то я не тестил ни разу))) Только на своих сторонних модулях запиливал такое.

**Comment by yupe** [comment]
При активации аккаунта пароль отправить мы не можем так как в базе он не хранится в открытом виде. При регистрации - просто добавьте вывод пароля в шаблоне письма (переменная $form->password)
