### ISSUE TITLE
доработки и исправления в активации

### ISSUE THREAD

**Issue by ilvval** [yupe/yupe#2406]
скин default (он мне больше нравится почему-то его не сильно продвигаете)
1.При активации нужно не только активировать но и авторизоваться, лишние действия приходится делать пользователю для входа.
2. Текст при активации нужно примерно такое, пользователю не понятно что делать дальше...: 
"Для завершения регистрации на Вашу почту было отправлено письмо с активацией аккаунта! Проверьте почту!"
3. В письме с активацией есть "ссылка" и сама ссылка с возможностью на него нажать, думаю это уже избыточно, в первом случае ссылка понятно, во втором нужно указать, что можно скорировать и вставить в адресную строку.

**Comment by sabian** [comment]
Сделали автоматическую авторизацию пользователя после регистрации (только если не требуется активация аккаунта), остальное дело вкуса и можете поправить в шаблоне своего сайта.
