### ISSUE TITLE
Блок фильтров

### ISSUE THREAD

**Issue by mixxael** [yupe/yupe#2410]
поехала верстка в блоке фильтров после обновления до бета-1
![bug](https://cloud.githubusercontent.com/assets/3533722/13936273/25b6dd2c-efc5-11e5-859e-bcebc8c8997b.png)

**Comment by yupe** [comment]
Поправим, спасибо.

**Comment by yupe** [comment]
Вообще странно, вот тут http://demo.yupe.ru/store такого нет. Скорее всего это у Вас с локальными стилями что-то.
