### ISSUE TITLE
Несколько вариантов атрибутов в списке.

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2415]
Ребят, а можно сделать так, чтобы можно было выбирать для определенного товара несколько пунктов из списка артибута(через ctrl или еще как)? А то сейчас только один и всё на этом...
![image](https://cloud.githubusercontent.com/assets/15049122/14084754/00d4147e-f525-11e5-9571-fc1a82826478.png)

**Comment by yupe** [comment]
Функционал готов. Осталось только протестировать получше.

**Comment by syrexby** [comment]
Люблю вас :heart_eyes: 
Правда, круто справляетесь!

**Comment by yupe** [comment]
@syrexby там еще могут быть баги, но надеюсь, что отловим =)

**Comment by syrexby** [comment]
@yupe Баги - дело поправимое. Главное, что держите марку, дорабатываете постоянно и к сообществу прислушиваетесь. Это дорогого стоит! :+1:
