### ISSUE TITLE
ВАЖНО: Не отсылает письмо для подтверждения регистрации!

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2418]
Сабж.
Пробовал у себя на 0.9.9 и у вас на demo.yupe.ru.
Пользователь, таким образом, создается, а подтвердить регистрацию нельзя, потому и зайти под новым пользователем невозможно.
Также через обратную связь пытался отослать - тоже не получилось.

**Comment by yupe** [comment]
На demo просто не настроена почта, попробуйте на локальном хосте или на своем хостинге.

**Comment by syrexby** [comment]
Хм. Действительно, на локальном отправляется всё. 
Тогда вопрос, почему могут не отправляться письма с хостинга, если с локалки всё ок?
Кроме того, если попробовать отправить нативно,
`var_dump(Yii::app()->mail->send('emailFrom','emailTo','THEME','BODY',true));`
то работает и там и там...
Чем  может быть вызвано такое поведение?

**Comment by yupe** [comment]
Точно назвать причину сложно, необходимо смотреть конфиг. Возможно у вас настроенная отложенная отправка почты (если активен модуль queue) и все письма просто копятся в табличке. (см в админке)

**Comment by syrexby** [comment]
Но почему тогда на локалке работает нормально?
Конфиг одинаковый. Файлы идентичны... Очень странно(

**Comment by yupe** [comment]
@syrexby причина в Вашем хостинге (скорее всего), раз на локалке работает корректно. Необходимо разбираться именно с хостингом.

**Comment by syrexby** [comment]
Нашел проблему. 
В настройках модуля "Пользователи" в поле "Email от имени которого отправлять сообщение" указал email, соответствующий домену. Был указан *@gmail.com и от его имени не отправлялись сообщения.
