### ISSUE TITLE
Вложенность "системных" пунктов меню в админ панели

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2419]
Давно хотел спросить - а почему это так:

![yupe](https://cloud.githubusercontent.com/assets/3591619/14209365/88f0f78c-f82c-11e5-95de-32ad841f454a.png)

а не так:

![yupe 2](https://cloud.githubusercontent.com/assets/3591619/14209373/91616a6e-f82c-11e5-99bc-0d943d219997.png)

второй вариант вроде удобнее :)

**Comment by yupe** [comment]
По историческим причинам +)
