### ISSUE TITLE
Не вызывается getUrl() в новостях и не только.

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2428]
Сабж. 
Заметил, что убраны связи с chemezov.yii-seo и в композере зависимость тоже. Там этот и не только методы были. Забыли или специально? :)
![image](https://cloud.githubusercontent.com/assets/15049122/14441396/4b472ad2-003d-11e6-8ff9-b6e3bba728f9.png)

**Comment by yupe** [comment]
chemezov.yii-seo убрали специально. На какой версии повторяется ?

**Comment by syrexby** [comment]
На последней в dev ветке.

**Comment by yupe** [comment]
У нас нигде не используется CListView, по какому урлу возникает ошибка ?

**Comment by yupe** [comment]
Проверил на свежей версии, в админке и на паблике с новостями все хорошо.

**Comment by syrexby** [comment]
Я слил всё с dev ветки и сделал composer install. Это плохо?

**Comment by syrexby** [comment]
А тут?
https://github.com/yupe/yupe/blob/master/themes/shop/views/news/news/index.php#L12

**Comment by yupe** [comment]
Спасибо. Я проверил в теме default. Здесь поправим, сделаем как в админке.

**Comment by sabian** [comment]
@syrexby Спасибо, что сообщили. Все исправлено.

**Comment by syrexby** [comment]
Ага, вам спасибо)
А еще нашел вот в модели использование этой функции:
https://github.com/yupe/yupe/blob/master/protected/modules/news/models/News.php#L318

**Comment by sabian** [comment]
Этот метод ни где не используется. Удалил.
