### ISSUE TITLE
Блоги: Ошибка отрисовки yupe\widgets\CustomGridView в backend, если пользователь-автор не найден

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2438]
пользователем webmaster(administrator, id = 1) создан блог "Test" и пост "Test". 
в поля `yupe_blog_blog.create_user_id`, `yupe_blog_blog.update_user_id`, `yupe_blog_post.create_user_id`, `yupe_blog_blog.update_user_id` были соответственно занесены 1.
далее пользователь webmaster был удален, создан пользователь admin(administrator, id = 2)

переходим на blog/index и post/index
Итог:
`PHP Fatal error:  Call to a member function getFullName() on a non-object in /vendor/yiisoft/yii/framework/base/CComponent.php(612) : eval()'d code on line 1`

``` php 
[
   'name' => 'create_user_id',
  'type' => 'raw',
  'value' => 'CHtml::link($data->createUser->getFullName(), array("/user/userBackend/view", "id" => $data->createUser->id))',
   'filter' => User::getFullNameList(),
],
```

**Comment by yupe** [comment]
Ошибка интерфейса правильная, а вот как юзера удалили а посты остались - проверим.

**Comment by yupe** [comment]
Ошибка есть и в блоках и постах на поле update_user_id

**Comment by Divan4ik** [comment]
Для тех кто не держит сообществ, а хочет "блог одного человека" или компании на своем сайте, это может стать проблемой)

**Comment by yupe** [comment]
Будет еще больше проблем когда мы исправим - при удалении юзера с id  = 1, все его блоги и посты тоже удалятся +)

**Comment by Divan4ik** [comment]
У меня кстати в практике была похожая ситуация в joomla, там когда удалился пользователь админ - автор сотен тем\материалов авторство присвоилось другому пользователю, к сожалению не заметил алгоритма. Точно помню, что это не был последний добавленный пользователь. Скорее всего последний/первый Админ

**Comment by yupe** [comment]
Да нет, на самом деле, просто будет запрет на удаление юзера если у него есть связанные записи.
