### ISSUE TITLE
Массовое редактирование товаров

### ISSUE THREAD

**Issue by samox1n** [yupe/yupe#2440]
Я думаю вы поняли о чём я, массовое редактирование как в WordPress.

Допустим есть 100 товаров и они не в той категории.

Править вручную очень долго, так как нужно выбрать основную категорию, и затем дополнительную/дополнительные, а там выпадающий список. Море кликов.

Выбрали 100 товаров, нажали редактировать, на этой же странице к примеру справа появился блок с выбором того или иного. Нажали ок, всё поменялось.

**Comment by tmsk70** [comment]
В демке симплы кажется такое есть:
http://simplacms.ru

Оно? 
Если оно, то я сам давно о таком думал, вроде нужная вещь, но на деле оказалось что ей редко пользуются.
Однако когда действительно потребуется поменять категорию, отключить доступность для сотни товаров, тогда - тушите свет.. в ручную =))) но такое редко
