### ISSUE TITLE
zendsearch требует модуль новости

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2443]
Здравствуйте,
при попытке обновить поисковый индекс ругается на то что не установлен модуль "Новости".
Может можно сделать проверку, если модуль не установлен, то пропускать это дело?
Новости не всегда нужны.

**Comment by sabian** [comment]
Это все настраивается через файл конфигурации модуля https://github.com/yupe/yupe/blob/master/protected/modules/zendsearch/install/zendsearch.php
