### ISSUE TITLE
Ошибка при удалении атрибута, когда значение этого атрибута есть у товара(ов)

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2451]
Для воспроизведения бага необходимо иметь товар, тип товара.

1. создаем атрибут TYPE_CHECKBOX_LIST
2. присваиваем к типу
3. Заполняем атрибут в товаре указанного типа.
4. Удаляем атрибут

предлагаю очистку значений атрибута в товарах при удалении самого атрибута.

PHP Fatal error:  Call to a member function isMultipleValues() on a non-object in /var/www/user/data/www/domain.net/protected/modules/store/models/Product.php on line 683, referer: http://domain.net/backend/store/product/update/171

**Comment by yupe** [comment]
Проверим, поправим.

**Comment by yupe** [comment]
На текущей версии не воспроисзводится, атрибут удаляется корректно, товар корректно отображается и в админке и на фронте.
