### ISSUE TITLE
Поиск в меню бэкэнда

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2452]
Здравствуйте,
не под главным админом не виден поиск в навигационном меню бэкэнда:
https://youtu.be/oa9t3IFtawE

**Comment by yupe** [comment]
Поправим. Спасибо!

**Comment by yupe** [comment]
Исправили. Необходимо заново импортировать правила для модуля "Поиск" и переприсвоить права пользователю.

**Comment by tmsk70** [comment]
Коллеги, вы чего творите))) тикеты так быстро закрываются, что я от радости работать не хочу)))

**Comment by yupe** [comment]
Работает?

**Comment by tmsk70** [comment]
Да, все отлично =)
