### ISSUE TITLE
Access to undeclared static property: yupe\helpers\Html::$map

### ISSUE THREAD

**Issue by socialist** [yupe/yupe#2453]
Такая ошибка вывалилась в бекенде **/backend/user/tokens**
php 7.0.5 если что.
>**Access to undeclared static property: yupe\helpers\Html::$map**
**/protected/modules/yupe/helpers/Html.php(129)**

```php
 /**
 * @param $status
 * @param $text
 * @param array $map
 * @return string
 */
public static function label($status, $text, array $map)
{
    if (!isset($map[$status]) || $map[$status] === self::DEF) {
        return static::def($text);
    }

    return static::$map[$status]($text);
}
```

**Comment by yupe** [comment]
@socialist а на какой страничке в юпи ошибка возникает ?

**Comment by socialist** [comment]
http://example.com/backend/user/tokens

Я писал в начале, только без "http://example.com"

**Comment by yupe** [comment]
Да, точно, не заметил, поправим. Если у Вас есть под рукой пхп7 - можете прислать PR, примем с удовольствием +)

**Comment by socialist** [comment]
Готово. Это мой первый PR. Не бить если что :)
