### ISSUE TITLE
Переход на страницу товара из корзины

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2456]
Ведёт по неверному адресу, без категорий
В админке в товарах также.
![image](https://cloud.githubusercontent.com/assets/15049122/15303036/872603ba-1bbe-11e6-8e92-c81c012c1339.png)
![image](https://cloud.githubusercontent.com/assets/15049122/15303215/424d0d3c-1bbf-11e6-92e7-0d20a8e77d73.png)

**Comment by syrexby** [comment]
И еще в комментариях в админке "Тип модели" также ведёт по неправильному пути.

**Comment by yupe** [comment]
Частьчно решено вот тут https://github.com/yupe/yupe/pull/2457
