### ISSUE TITLE
Сбрасывание параметров фильтров при удалении через AJAX

### ISSUE THREAD

**Issue by mr-jelu** [yupe/yupe#2480]
Если установить фильтр, например принадлежность к родителю, и удалить позицию, происходит полный сброс всех фильтров.

Подробно описывал на фворуме: http://talk.yupe.ru/viewtopic.php?f=11&t=1615&p=13608#p13608

Причина сброса фильтров, в том что не устанавливается страница, на которую должен ссылаться скрипт обновления.

Простейшим решением этого неприятного бага, является добавление параметра ссылки в yiiGridView .

```php
class CButtonColumn extends CGridColumn
{
	protected function initDefaultButtons()
	{
		$this->buttons['delete']['click']=<<<EOD
			function() {
				$confirmation
				var th = this,
					afterDelete = $this->afterDelete;
				jQuery('#{$this->grid->id}').yiiGridView('update', {
					type: 'POST',
					url: jQuery(this).attr('href'),$csrf
					success: function(data) {
						jQuery('#{$this->grid->id}').yiiGridView('update', {url: document.location.href });
						afterDelete(th, true, data);
					},
					error: function(XHR) {
						return afterDelete(th, false, XHR);
					}
				});
				return false;
			}
			EOD;

		}
	}
}
```

Но это костыль, который требует исправление ядра Yii, как вариант сделать переопределение класса, описать в нем функцию

**Comment by sabian** [comment]
Дублирует #2482
