### ISSUE TITLE
Редактирование профиля обычным пользвателем

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2481]
Может я не по глазам, а может не реализовано управлением профилем для обычного пользователя (не главного админа):
https://yadi.sk/i/iyua7bU9s7G7W

например, клиент хочет сменить пароль к своему логину, что в принципе нормально
первый клиент за пару лет работы решил сменить пароль, который выдаю им)))

но в доступе отказано, а в выставлении прав именно такого, кажется, нет:
https://yadi.sk/i/p7v91jaNs7G55

**Comment by ashkrobov** [comment]
Здравствуйте!

Ваше письмо получено. Постараюсь в ближайшее время на него ответить.


С Уважением, Шкробов Александр.
E-mail - shkrobov@yandex.ru
ICQ 404176085
