### ISSUE TITLE
namespace application\commands;

### ISSUE THREAD

**Issue by loveorigami** [yupe/yupe#2487]
Хотел написать консольные команды по аналогии с yii2

Создал в protected/commands файл
```
<?php
namespace application\commands;
class TestCommand extends \yupe\components\ConsoleCommand
{
    public function run() {
        echo 111;
    }
}
```
запускаю в консоли yiic test - получаю ошибку
```
Fatal error: Cannot redeclare class application\commands\TestCommand in ....\protected\commands\TestCommand.php on line 12
```
убираю namespace - все работает.

Использовать команды без namespace-ов или это можно как то поправить?

**Comment by yupe** [comment]
Это уже вопрос к самому Yii. Если Yii1.x так позволяет делать - то можно.
p.s. такие вопросы лучше вот тут http://talk.yupe.ru/ обсуждать.
