### ISSUE TITLE
Тайтл страниц в темах

### ISSUE THREAD

**Issue by PushingUp** [yupe/yupe#2489]
Сейчас в темах default и shop имеется неразбериха с тайтлами. Например, в themes/shop/views/layouts/yupe.php для вывода тайтла используется свойство $this->pageTitle

`<title><?= $this->pageTitle;?></title>`

В шаблоне страницы themes/shop/views/page/page/view.php тайтл присваивается свойству $this->title

`$this->title = $model->title;`

В результате в тайтле не оказывается названия страницы. Например, на странице http://demo.yupe.ru/contacts в тайтле вместо "Контакты" пишется "Yupe! - Contact". Аналогично в тайтлах и на главной странице, странице категории, на странице Избранных и т.д., кроме страницы товара.

Также в теме default тоже есть такая проблема + в самих модулях тоже.

Также как пожелание хотелось бы иметь возможность редактировать в админке тайтл на обычных страницах в seo-настройках, так как это сделано на странице продукта и категории продукта.

**Comment by chemezov** [comment]
А потому что не надо было выкидывать компонент seo. =)

**Comment by yupe** [comment]
@chemezov в компоненте много магии, да и автор компонента перестал поддерживать его интеграцию в юпи =) А ошибочки поправим, это все мелочи =)

**Comment by chemezov** [comment]
@yupe можешь привести пример магии? А на счёт поддержки - нового дополнять вроде как нечего (ну по крайней мере у меня нужды не было, запросов на фичи тоже :) ), и багов вроде как тоже не было (по крайней мере issues мне не приходили). Поэтому мне кажется зря выпилили, можно было хотя бы перенести к себе в репозиторий.

**Comment by yupe** [comment]
@chemezov я честно уже не помню, но были какие-то костыли, которые нам приходилось вбивать чтобы сделать какие-то вещи.

**Comment by yupe** [comment]
Ну и сводим к минимуму зависимости от внешних пакетов. Модуль cart на очереди =)
