### ISSUE TITLE
Бренды в фильтре товаров

### ISSUE THREAD

**Issue by samox1n** [yupe/yupe#2491]
Захожу в категорию 1, должны отражаться только те бренды, которые относятся к данной категории. В общем как с атрибутами, только бренды :-)

> При фильтрации внутри категории теперь отображаются только те атрибуты, которые есть у товаров в этой категории.

**Comment by maxim-avramenko** [comment]
которые есть у товаров в этой категории

**Comment by maxim-avramenko** [comment]
которые относятся к данной категории.
