### ISSUE TITLE
Баг с заголовками в 1.0-beta-2

### ISSUE THREAD

**Issue by samox1n** [yupe/yupe#2508]
Даже на демо сайте http://demo.yupe.ru/store/brand/acer
В тайтле бренда видим Yupe! - View Producer

Замечено <s>в брендах, страницах, корзине, профиле пользователя и категориях</s> много где

Правил view.php

Было так
`$this->title = $brand->meta_title ?: $brand->name;`

Стало так
`$this->pagetitle = $brand->meta_title ?: $brand->name;`

Всего то добавил page перед title :-)

**Comment by sabian** [comment]
В dev ветке это уже исправлено.
