### ISSUE TITLE
При удалении модуля Comment удаляется модуль Homepage

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2515]
Добрый день.
При удалении модуля Comment удаляется модуль Homepage.
При возврате Homepage так же ставится и Comment

**Comment by sabian** [comment]
@Divan4ik Все верно. Модуль главной страницы зависит от блогов, которые в свою очередь используют комментарии. Поэтому при отключении комментариев отключается и модуль главной страницы.

**Comment by maxim-avramenko** [comment]
Может не нужно отключать модуль главной страницы при отключении модуля Comment?

**Comment by yupe** [comment]
@maxim-avramenko при отключении модуля - отключаются все модули, которые от него зависят. Здесь единственный вариант - убрать у homepage зависимость от blog, но у нас такое уже было - это не очень удобно.
