### ISSUE TITLE
Ошибка на последней dev-ке

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2518]
Установил свежую yupe(несколько раз) из github'a и попытался добавить товар. 
Получил это
![image](https://cloud.githubusercontent.com/assets/15049122/16660100/ae8d6eb8-4475-11e6-91b1-f89fecffecaf.png)
Логи:
![image](https://cloud.githubusercontent.com/assets/15049122/16660110/bd1477c4-4475-11e6-9653-732d92c53428.png)
![image](https://cloud.githubusercontent.com/assets/15049122/16660116/c3effec4-4475-11e6-8e33-46a9dca60cd5.png)

PHP-7

**Comment by mikspark** [comment]
Это из-за строго режима MySQL

Посмотреть какой режим сейчас глобально или для сессии

```
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
```
Как включить 
http://dev.mysql.com/doc/refman/5.5/en/sql-mode.html#sql-mode-full

```
[mysqld]
...
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE"
```

**Comment by Blacknife** [comment]
Добрый день, прошу прощения, у меня схожая проблема, это тоже из-за режима MySql? При создании категории товара не могу зайти в категорию во frontend.

![2016-07-10_103707](https://cloud.githubusercontent.com/assets/19269803/16712273/f3d2648a-468a-11e6-9888-7ce7535f90ff.jpg)

**Comment by yupe** [comment]
@syrexby @Blacknife какие у вас версии mysql ? Используете OpenServer или что-то подобное ?

**Comment by Blacknife** [comment]
@yupe да, OpenServer, это плохо? MySql версии 5.7

**Comment by yupe** [comment]
Нет, не плохо, просто уточняю. с 5.7 strict режим в mysql включен по умолчанию. Мы проверим и поправим ошибки. Пока просто отключите этот режим.

**Comment by syrexby** [comment]
А в yii нет в конфигах где-то опций для выбора строгого/нестрогого режимов, чтобы корректно формировало? Или я неправильно понял что-то?

**Comment by Blacknife** [comment]
@yupe спасибо, пока решил использовать Mysql 5.6, ошибка пропала!

**Comment by yupe** [comment]
@syrexby это можно изменить стартовым sql-запросом. @Blacknife будем признательны если еще потестите на 5.7 и скажите, где еще возникают ошибки. Так или иначе мы пофиксим все, чтобы на 5.7 все работало из коробки.

**Comment by Blacknife** [comment]
@yupe хорошо, если наткнусь - сообщу! Спасибо ещё раз!

**Comment by yupe** [comment]
@Blacknife @syrexby по идее пофиксил, на 5.7 должно быть все хорошо. Проверьте по возможности.

**Comment by syrexby** [comment]
Обновился.
Теперь вообще в админку не заходит :(
![image](https://cloud.githubusercontent.com/assets/15049122/16736343/3c857d88-4795-11e6-8ae9-27b7c712f0fa.png)

**Comment by syrexby** [comment]
Да, с нуля всё ок, спасибо!

**Comment by yupe** [comment]
@syrexby на пхп 7 и на mysql 5.7 все ок ?

**Comment by Blacknife** [comment]
@yupe только что установил свежую версию через composer: при заходе в раздел "Магазин" если выбрана тема "default" - вываливается ошибка (скриншот), в теме "shop" ошибок нет. OpenServer (MySql 5.7 and PHP7).
![2016-07-15_200805](https://cloud.githubusercontent.com/assets/19269803/16882668/e936cc04-4ac8-11e6-88c2-dfb728ac3b68.png)

**Comment by Blacknife** [comment]
@yupe хмм, странно, установил ещё раз заного, но через git - ошибка пропала, а в чём различие?

**Comment by syrexby** [comment]
@yupe Да, у меня на этих версиях всё отлично теперь. Спасибо!

**Comment by yupe** [comment]
@syrexby супер! Спасибо. Там еще в блогах есть ошибка по этой же причине. Как только поправим - тикет закроем.
