### ISSUE TITLE
Как скрыть незаполненные атрибуты в карточке товара

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2525]
Допустим такую ситуацию:

Есть тип товара  -  пылесос с присвоенными атрибутами. Но в один из пылесосов приходится добавить дополнительный атрибут:

![-samsung-vcc-sc-4520s3b--192992-- -- -- -- --- - -](https://cloud.githubusercontent.com/assets/3591619/16831802/95806e68-49af-11e6-86c9-56994b79dc39.png)
 
Для такой реализации я делаю максимально удовлетворяющий группе товаров тип, а в товарах не заполняю отсутствующие характеристики. Думаю многие со мной согласятся, что делать под каждый товар отдельный тип - очень кропотливая работа.

Собственно и вопрос: Каким способом проверить что атрибут не заполнен? Стоит ли это делать во view фронтенде/виджете?

Спасибо.

**Comment by yupe** [comment]
Если различия существенные - лучше сделать отдельный тип. 
Чтобы проверить заполненность можно сделать вот такое условие:
`if($product->attribute('some-attr'){}`

p.s. лучше подобные вопросы писать на http://talk.yupe.ru/ +)

**Comment by Divan4ik** [comment]
продолжил тут http://talk.yupe.ru/viewtopic.php?f=11&t=1663

**Comment by yupe** [comment]
http://talk.yupe.ru/viewtopic.php?f=11&t=1663&p=13844#p13840
