### ISSUE TITLE
themes must be in web accessible folder

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2526]
Now they are not web accessible, and therefore I need publish every asset via assetManager. It is inconvenient because I have to delete all assets after each change in CSS. I offer either to make theme folder web accessible or add following to conf:
```
'assetManager' => [
     'forceCopy' => defined('YII_DEBUG') && YII_DEBUG ? true : false,
],
```

**Comment by mikspark** [comment]
`linkAssets` also can be used, but it works not at all environments

We need local configs which merged with main configs, but ignored by VCS. 
https://github.com/yupe/yupe/blob/master/protected/config/project.php we have this config file, but it not in gitignore. 

Need to refactor this class https://github.com/yupe/yupe/blob/dev/protected/modules/yupe/components/ConfigManager.php and introduce local configs like in Yii2

or/and something like that https://github.com/vlucas/phpdotenv

**Comment by mikspark** [comment]
@fazliddin 
copy https://github.com/yupe/yupe/blob/dev/protected/config/main-local.php.dist  as main-local.php
