### ISSUE TITLE
How to move project to production server

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2530]
Let me ask one humble question. It is first time I have encountered such problem in my 7 years experience.

So I installed yupe locally and developed my site and pushed it to bitbucket and pulled it into production server and run `composer install`. Here occured two strange things.
1. `config/db.php` was on production server and it held different data than its local version even if this file was in gitignore
2. I corrected params on db.php and opened site in browser and I see new installation page

**Comment by yupe** [comment]
1 config/db.php is created by this component - https://github.com/yupe/yupe/blob/master/protected/modules/yupe/components/Composer.php

2 delete /protected/config/modules/install.php - fixed this bug by last commit

Thanks!

**Comment by fazliddin** [comment]
ok thanks, it works, but there another issue https://github.com/yupe/yupe/issues/2531
