### ISSUE TITLE
After moving project into production server modules became disabled

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2531]
I move same db dump to prod server but it gives:
Виджет "application.modules.contentblock.widgets.ContentBlockWidget" не найден! Подключите модуль "contentblock"!

Виджет "application.modules.callback.widgets.CallbackWidget" не найден! Подключите модуль "callback"!

Виджет "application.modules.news.widgets.LastNewsWidget" не найден! Подключите модуль "news"!

and so on

**Comment by fazliddin** [comment]
i moved via git push & pull. And I see gitignore in config/modules and they were left on local server. What is the solution?

**Comment by yupe** [comment]
You can enable modules by hand in control panel, or you can copy /protected/config/modules from you local machine.

**Comment by fazliddin** [comment]
ok, thank you

**Comment by yupe** [comment]
i hope that help
