### ISSUE TITLE
Сбрасывание фильтров при массовом удалении

### ISSUE THREAD

**Issue by mr-jelu** [yupe/yupe#2536]
До этого я писал про проблему, со сбрасываем фильтров при удалении записей в системе. Ее исправили, но массовое удаление забыли... очень не удобно каждый раз восстанавливать фильтры

Решение проблемы в modules/yupe/widgets/CustomGridView.php (562 строка)

```
public function renderMultiaction()
{
           [...]
                       if (data.result) {
                                 $.fn.yiiGridView.update("'.$this->id.'");
                       } else {
                                alert(data.data);
                      }
          [...]
}
```

если заменить **$.fn.yiiGridView.update("'.$this->id.'");** на **jQuery("#'.$this->id.'").yiiGridView(\'update\',{url: document.location.href });**

проблема со сбросом фильров отпадает... надеюсь это поможет вам сделать систему более удобной для тех кто в ней работает!

**Comment by yupe** [comment]
@mr-jelu исправили, по вашему рецепту, спасибо!
Если будут еще какие-то замеания/предложения - обязательно пишите.
