### ISSUE TITLE
Описание атрибута

### ISSUE THREAD

**Issue by samox1n** [yupe/yupe#2537]
Есть идея добавить в Атрибуты поле Описание, и если оно заполнено, показывать на сайте иконку с вопросительным знаком, по наведения на которую, пользователь бы смог более подробно узнать что за атрибут перед ним. Отличный пример реализации на Яндекс.Маркете.
![8rjteyhgw](https://cloud.githubusercontent.com/assets/1114652/17354662/53dea34a-5953-11e6-8ac8-1b345a7fa459.jpg)

**Comment by yupe** [comment]
Отличное предложение! Попробуем сделать, если сделаете раньше нас - присылайте PR +)

**Comment by samox1n** [comment]
Если бы умел бы :-)

**Comment by yupe** [comment]
Сделали, можете обновиться.

**Comment by samox1n** [comment]
Круто! Спасибо. Буду пробовать :-)
