### ISSUE TITLE
Ошибка редактора

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2539]
http://talk.yupe.ru/viewtopic.php?f=2&t=1670

**Comment by sabian** [comment]
Дело в том, что у нас (не знаю почему) украинский язык обозначается как `uk`, поэтому при загрузке редактора ищется файл переводов `uk.js`, который у них называется - `ua.js` 
https://github.com/yiiext/imperavi-redactor-widget/blob/master/assets/lang/ua.js

**Comment by maxim-avramenko** [comment]
http://userguide.icu-project.org/locale#TOC-The-Locale-Concept
Как подсказывает нам этот документ мы имеем 
1) Language code
2) Country code
.......
Для "Незалежной" значения для переменных будут следующие:
1) Language code = UK (i18n интернационализация)
2) Country code = UA  (локализация l10n ) 

Вариант решения: 
при инициализации imperavi необходимо использовать Country code, а не Language code. Можно попробовать в настройках главного модуля Yupe!, в поле "Список доступных языков через запятую", указывать полностью язык_страна "uk_ua", тогда станет доступна и локализация.

На всякий случай еще табличка с кодами языков и локализаций на примере uk_ua http://www.unicode.org/cldr/charts/latest/supplemental/language_territory_information.html#uk

**Comment by mikspark** [comment]
Сделал так же как с китайским, остальные трогать не стал. По хорошему перевести все языки в таком формате и класс в стилях тоже переименовать.
