### ISSUE TITLE
Показывать кнопку подбора, только если есть атрибуты в поиске

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2540]
Добрый день!

Есть ли возможность в виджете FilterBlockWidget не показывать кнопку submit, а выводить ее в зависимости от содержимого AttributesFilterWidget?

https://github.com/yupe/yupe/blob/dev/themes/shop/views/store/widgets/FilterBlockWidget/filter-block.php#L12
т.е. нет фильтров - нет кнопки.

**Comment by Divan4ik** [comment]
Посмотрите пожалуйста https://github.com/yupe/yupe/pull/2543

**Comment by yupe** [comment]
Готово.
