### ISSUE TITLE
Хорошое улучшение поиска

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2544]
Друзья,
по моему мнению поиск неплох, но его можно сильно улучшить добавив к страницам/новостям/галереям/товарам/категориям поле с названием "Запросы для поиска", дабы туда можно было ввести: айфон, айфон 6с и т.д., 
после чего товар "iphone 6s" начинал бы находиться по таким фразам.

Когда будет производиться поиск по сайту, чтобы он искал еще и по этому полю, а результат выводился только для подключенных модулей вроде:

Найдено товаров: 2
iphone 6s
iphone 5

Найдено страниц: 1
Как мы убивали iPhone 6s

т.е. если нет модуля галереи, в которых тоже могут быть такие поля, то не пишется что "Найдено галерей: 0".

**Comment by tmsk70** [comment]
Конечно, в первую очередь это улучшает магазины.

**Comment by yupe** [comment]
Это похоже на тегирование товаров, типа как постов в блоге. Так ведь?

**Comment by tmsk70** [comment]
Честно, блоги от юпи ни разу не видел в глаза =)

**Comment by yupe** [comment]
https://github.com/yupe/yupe/issues/2239
