### ISSUE TITLE
Электронная коммерция Яндекса

### ISSUE THREAD

**Issue by samox1n** [yupe/yupe#2548]
Не могу подключить, так как Яндекс обязательно требует id или sku товара.
SKU можно указать, но вручную, когда товаров много, сами понимаете.
Можно ли получить id и выводить его на странице товара?

**Comment by yupe** [comment]
$model->id - id - товара 
$model->sku = sku

Вопросы лучше сюда http://talk.yupe.ru/ писать, если что мы сами сделаем тикеты.

**Comment by samox1n** [comment]
Хорошо
Спасибо
