### ISSUE TITLE
Атрибуты

### ISSUE THREAD

**Issue by samox1n** [yupe/yupe#2549]
Суть:
категория1, в ней много других категорий

Например:
телефоны, а в ней телефоны эпл, телефоны самсунг, ...

Атрибуты указаны у всех товаров.

Фильтры с атрибутами выводится в категории телефоны, а вот в категории телефоны эпл, телефоны самсунг, ... почему-то нет.

PS Писал вам на почту, но так и не понял, а возможно и понял, но расстроился что всё не так как вроде бы должно быть следуя логике.

**Comment by yupe** [comment]
Проверим.

**Comment by sabian** [comment]
Потестировал с разной вложенностью категорий. У меня этой проблемы не наблюдается.
