### ISSUE TITLE
Отображение списка товаров

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2550]
http://talk.yupe.ru/viewtopic.php?f=11&t=1671

**Comment by syrexby** [comment]
Вроде бы у себя сделал. Проанализировал запросы и заметил, что в результатах выдаются одинаковые строки, если в categoryRelation есть для товара какие-то записи. То есть, если в categoryRelation для текущего товара есть записи, то оно выводит каждый раз новую строку с этим же товаром, только с джойнами из categoryRelation, поэтому DISTINCT не отрабатывает. Я сделал во всех методах, где выводятся товары из категории, группировку по t.id и вроде настроилось. 

`$criteria->group='t.id';`

тут для админки 
https://github.com/yupe/yupe/blob/master/protected/modules/store/models/Product.php#L328
тут для вывода на фронте если фильтры есть
https://github.com/yupe/yupe/blob/master/protected/modules/store/components/repository/ProductRepository.php#L26
а тут для вывода на фронте если фильтров нет
https://github.com/yupe/yupe/blob/master/protected/modules/store/components/repository/ProductRepository.php#L196

**Comment by yupe** [comment]
@syrexby пофиксили, но немного иначе, если будет возможность - проверьте у себя. Спасибо!
