### ISSUE TITLE
When home page is visited and no language is given via url, then we shouldn't look at cookie

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2553]
Let's assume we have site with ru, en languages and en is default. Then
`http://site.com` - loads en version
`http://site.com/ru` - loads ru version and saves ru in cookie. After visiting ru version if we head to `http://site.com` yupe loads ru version of the content, because it takes lang from cookie and sets it via `Yii::app()->setLanguage()`, but does not redirect to `http://site.com/ru`.

Solution is to set system language and cookie language to default one, if home page is visited and no language is given via url. Here is change for `LanguageBehavior`, it works for me.

```
public function handleLanguageBehavior($event)
    {
        /**
         * if we are at home page and url lang is not given, then default app
         * language must be set system wide.
         */
        if(empty($_GET) && !isset($_SERVER['HTTP_REFERER']) && ($this->lm->getAppLang() != $this->getLang()))
            $this->setLanguage($this->lm->getAppLang());
        else
            $this->setLanguage($this->getLang());

        $this->lang = ($this->lm->getAppLang() === $this->getLang() ? false : $this->getLang());

        // язык передан в url, но он равен дефолтному языку
        if ($this->getUrlLang() !== null && $this->lang === false) {

            Yii::app()->getRequest()->redirect(Yii::app()->getHomeUrl() . $this->lm->getCleanUrl(Yii::app()->getRequest()->url));
        }
    }
```

**Comment by mikspark** [comment]
it works as expected now?

**Comment by fazliddin** [comment]
yes

**Comment by fazliddin** [comment]
Sorry, it must be as following
```
public function handleLanguageBehavior($event)
{
        /**
         * if we are at home page and url lang is not given, then default app
         * language must be set system wide.
         */
        if(empty(Yii::app()->getRequest()->getPathInfo()))
            $this->setLanguage($this->lm->getAppLang());
        else
            $this->setLanguage($this->getLang());

        $this->lang = ($this->lm->getAppLang() === $this->getLang() ? false : $this->getLang());

        // язык передан в url, но он равен дефолтному языку
        if ($this->getUrlLang() !== null && $this->lang === false) {

            Yii::app()->getRequest()->redirect(Yii::app()->getHomeUrl() . $this->lm->getCleanUrl(Yii::app()->getRequest()->url));
        }
}
```
If no route and language is passed via uri, we set default language. For example, `site.ru`, `site.ru?tp=io`. It does not work if urlmanager is not set to path mode.

**Comment by mikspark** [comment]
Default language russian

I have no cookie and visit http://yupe.dev/?r=feedback/contact/index
I see page in russian

I change language to english
I redirected to same page with language param http://yupe.dev/?r=feedback/contact/index&language=en
I close browser and visit page http://yupe.dev/?r=feedback/contact/index
I redirected to same page with language param http://yupe.dev/?r=feedback/contact/index&language=en because i have cookie

Same with any route.

**Comment by tmsk70** [comment]
Что-то не пойму, использовал ваш файл LanguageBehavior.php, но возникла ошибка:

Во время отрисовки виджета (yupe\widgets\YLanguageSelector) произошла ошибка:
В классе yupe\components\urlManager\LangUrlManager и его поведениях не найден метод или замыкание с именем "replaceLangUrl".

**Comment by yupe** [comment]
@mikspark метод replaceLangUrl используется во вьюхах, его стоит заменить.

**Comment by tmsk70** [comment]
А на какой именно можно заменить? Он у меня в languageselector.php использован

**Comment by yupe** [comment]
Надеюсь, нам @mikspark ответит -)

**Comment by tmsk70** [comment]
Окей, тогда подождем ответа.

**Comment by mikspark** [comment]
Поправил виджет, попробуйте еще раз. Я бы его не пропустил, если бы он где-то использовался.

**Comment by tmsk70** [comment]
Залил ваш виджет, теперь такая ошибка:
Не определено свойство "yupe\components\urlManager\LangUrlManager.languages".

konkor70.ru

**Comment by yupe** [comment]
@tmsk70 проверил на последней версии - ошибки нет, очистите весь каталог runtime

**Comment by tmsk70** [comment]
Да у меня тоже вроде последняя версия (вчерашняя).. runtime чистил, странно, с новым виджетом languageselector.php даже в бэкэнд не пускает

**Comment by yupe** [comment]
@tmsk70 так правки  были два часа назад. Вот коммит https://github.com/yupe/yupe/commit/3698bd8272ff05d9890c2e93e056babadac90b25

**Comment by tmsk70** [comment]
Точно, я думал только виджет поправили, обновил модуль юпи и все заработало. 
Спасибо за помощь, большое спасибо!
