### ISSUE TITLE
News model does not flush cache after saving

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2554]

**Comment by yupe** [comment]
What is the reason to flush cache?

**Comment by fazliddin** [comment]
if you change smth in news content, it does not appear on site until you clear cache manually. All other modules clear the cache after save()

**Comment by yupe** [comment]
@fazliddin its on one news page or where ?

**Comment by fazliddin** [comment]
It is about Backend `News` model. I meant deleting the proper cache. For example, `ContentBlock` model has proper cache cleaner:
```
protected function beforeSave()
    {
        if (parent::beforeSave()) {
            Yii::app()->cache->delete("ContentBlock{$this->code}" . Yii::app()->language);

            return true;
        }

        return false;
    }
```
But  `News` model has no  `Yii::app()->cache->delete(`. Actually such cache deleting must be in `afterSave()` method, because `update` or `insert` methods may cause error and thus data is not saved but cache is deleted.
