### ISSUE TITLE
Баг регистрации пользователя

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2556]
Друзья,
1) В последней версии юпи есть бага с регистрацией пользователя:
https://yadi.sk/i/7aEuI_E6veSxG

(временно скопировал модуль user и yupe с предыдущей версии, там все работает)

2) Заметил еще одну багу, письма с запросом подтверждения регистрации приходят от 
Root User root@localhost.localdomain
хотя в настройках модуля пользователей (в графе "Email от имени которого отправлять сообщение")  указано иное

3) При попытке войти только что зарегистрированному пользователю пишет что он ввел не верный логин или пароль, а дело просто в том что он не подтвердил регистрацию по ссылке в письме. И человек человек долго тормозил, не понимая в чем дело. Т.е. нужно бы сообщение - "Вы еще не подтвердили свой e-mail".

**Comment by yupe** [comment]
1 В текущей версии (ветка dev) не повторяется
2 В текущей версии (ветка dev) не повторяется
3 Сомнительно, можно будет использовать для проверки валидностей email и пароля
