### ISSUE TITLE
Вопрос по редактору imperavi

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2560]
Друзья,
а куда потерялось удаление строк у таблиц? Подскажите пожалуйста, как вернуть (чего дописать и в каком файле).

В юпи 9.8 есть удаление строк
https://yadi.sk/i/CDTplbBRwN5Rd

А в юпи 1.0 уже нету
https://yadi.sk/i/oJQm3inswN5X2

**Comment by sabian** [comment]
Исправлено.
Обновите пакеты командой `composer update` или завтра (сборка происходит ночью) скачайте свежую версию с нашего сайта.
