### ISSUE TITLE
NewsModule::getNavigation() returns invalid category list link

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2562]
Clicking to news category link heads to empty list.There should not beparent param and it must be as following.

```
[
                'icon' => 'fa fa-fw fa-folder-open',
                'label' => Yii::t('NewsModule.news', 'News categories'),
                'url' => ['/category/categoryBackend/index'],
 ],
```

**Comment by mikspark** [comment]
Only if mainCategory not set for module

**Comment by sabian** [comment]
This works fine. Please, select main news category in module settings.
![news](https://cloud.githubusercontent.com/assets/434141/19200288/d40bc10a-8cd0-11e6-8d9c-587eaf844db6.png)

**Comment by mikspark** [comment]
https://github.com/yupe/yupe/blob/dev/protected/modules/news/NewsModule.php#L283
```
'url' => ['/category/categoryBackend/index', 'Category[parent_id]' => $this->mainCategory ?: null],
```

**Comment by yupe** [comment]
@mikspark ?

**Comment by yupe** [comment]
@mikspark закрываем или что?
