### ISSUE TITLE
Не устанавливается версия 1.0 при выборе только общих модулей

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#2576]
Только что выкачал через composer свеженькую версию, устанавливаю на OpenServer.

Apache 2.4.
PHP 5.6.

Выбрал пункт "только основные модули" (мог ошибиться в названии, но это тот пункт, который выбирает только 3 модуля: Юпи, Пользователи, Уведомления).
Нажимаю продолжить, вижу список, нажимаю далее, окно закрывается, страница остаётся та же самая (не помню была перезагрузка или нет).

При полном наборе модулей (те, что по умолчанию выделены) установка проходит.

**Comment by chemezov** [comment]
Да, страница перезагружается.

Не хватало модуля Почта. Добавил только его и всё заработало.

**Comment by yupe** [comment]
Поправим, спасибо _)

**Comment by chemezov** [comment]
@yupe на самом деле имеет смысл отделить модуль комментариев от магазина, зачем они там?

**Comment by yupe** [comment]
Комментировать можно товары (простой вариант отзывов) и комментировать можно заказы в панели управления.
