### ISSUE TITLE
Отдельное оформления для категорий магазина, брендов, товаров (свой лэйаут)

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2579]
Возникла потребность для одной из категорий сделать отдельное оформление.
Сейчас такое можно делать для страниц, указывая лайаут в доп.параметрах.

Думаю было бы неплохо иметь аналогичную возможность хотя бы для категорий товаров или брендов, а в идеале может потребоваться и для товара.

**Comment by syrexby** [comment]
Ну ведь просто в контроллере укажите в рендере такую-то вьюшку, если у вас такой-то слаг.. Это если здесь и сейчас нужно :)

**Comment by tmsk70** [comment]
@syrexby не здесь и сейчас, это предложение к функционалу юпи. Андрей попросил завести тикет.
