### ISSUE TITLE
Неожидаемое поведение обрезчика изображений

### ISSUE THREAD

**Issue by chemezov** [yupe/yupe#2581]
Столкнулся с таким "багом":

```
$data->getImageUrl(116, 116, true)
```

Если поменять параметр crop, то картинка будет выводиться старая, обрезанная, пока не удалишь все обрезанные картинки ничего не поменяется.

Вероятно, стоит в название файла вносить ещё и этот параметр, т.к. сейчас в формировании названия участвуют только размер и название файла.

```
116x116_19021cf2961c137d3e9fc3a0b4cc7b88.jpg
```

**Comment by yupe** [comment]
Может сделаете PR =) ?
