### ISSUE TITLE
The fact that half of classes use namespace and half of not is nightmare

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2582]
I removed namsespace from SiteController and here is result:
`Fatal error: Cannot redeclare class SiteController in /var/www/vhosts/clients/protected/controllers/SiteController.php on line 0`

**Comment by yupe** [comment]
What is reason for removing ns from default controller? 
Try change this settings https://github.com/yupe/yupe/blob/master/protected/config/main.php#L40

**Comment by fazliddin** [comment]
What does `'controllerNamespace' => 'application\controllers'` mean? Does this append namespace to all controllers or to only default controller?

**Comment by yupe** [comment]
@fazliddin http://www.yiiframework.com/doc/api/1.1/CWebApplication#controllerNamespace-detail its ns for controllers in protected/controllers only

**Comment by fazliddin** [comment]
thank you for clarifying, yii doc is often incomplete or ambiguous.
