### ISSUE TITLE
Фиксация страницы заказа обратного звонка

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2587]
В модуле callback необходимо фиксировать с какой страницы был заказан звонок (фиксируем полный урл).

**Comment by samox1n** [comment]
Отсюда? http://talk.yupe.ru/viewtopic.php?f=5&t=2103 Отлично :-)
Схоже с [Купить в один клик](https://github.com/yupe/yupe/issues/2509)
Ждём
