### ISSUE TITLE
Увеличение картинок в галерее с подгонкой под высоту экрана

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2589]
В общем не наболело, а просто захотелось.
Поумолчанию картинки в галерее юпи не подстраиваются под экран (т.е. картинка 6000х4000 заполняет весь экран), а делов то на пару минут.
О чем это я:
https://youtu.be/8KMyVYUkmd4

**Comment by sabian** [comment]
Проверяйте, теперь должно быть нормально.

**Comment by tmsk70** [comment]
Всё супер) Отлично!
Ребят, эт не баг, это просто удобство)
