### ISSUE TITLE
Качество загружаемого изображения

### ISSUE THREAD

**Issue by syrexby** [yupe/yupe#2591]
Не понимал почему не меняется качество изображения, если я менял этот параметр:
https://github.com/yupe/yupe/blob/master/protected/modules/yupe/components/behaviors/ImageUploadBehavior.php#L32
Как оказалось, у него задано неверное название и Imagine задавал свои стандартные параметры.
Должно быть 'jpeg_quality' и 'png_compression_level'.

**Comment by yupe** [comment]
@sabian если этот баг смотреть будешь, посмотри еще #2581 Они вроде где-то рядом.
