### ISSUE TITLE
Немного хорошего тона из SEO

### ISSUE THREAD

**Issue by dzhedai** [yupe/yupe#2597]
Предлагаю добавить в.htaccess 
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_URI} !(.*)/$
    RewriteCond %{REQUEST_URI} !^/backend/(.*)$
    RewriteRule ^(.*[^/])$ $1/ [L,R=301]

Для принудительного закрытия дулей страниц со слешом и без

ps понимаю что надо будет перечесать и роутинг при развитии этой идеи)

**Comment by yupe** [comment]
Еще бы для nginx +)

**Comment by maxim-avramenko** [comment]
server {
        listen 80;
        listen [::]:80;
        server_name mydomain.dev;
        rewrite ^([^.]*[^/])$ $1/ permanent;
.......

**Comment by dzhedai** [comment]
По итогам тестирования этого метода, выявились проблемы с корзиной и формированием заказов..
Корзина работает если добавить в исключения, а с заказами недоразобрался

**Comment by maxim-avramenko** [comment]
@dzhedai какой метод вы тестируете что выявились проблемы? И что значит добавить в исключения корзину? В исключения чего именно? С приведенным конфигом для nginx все работает отлично. Вы пользуетесь xdebug? Что он пишет?

**Comment by dzhedai** [comment]
nginx я не трогал, с htaccess были проблемы.
Без тестов на продакшен выкатил, через некоторое время увидел проблемы, в  итоге просто откатил без разбора. Буду позже разбираться почему

Проблема бы в том, что запросы в cart и order аяксом не проходили.

**Comment by maxim-avramenko** [comment]
@dzhedai может попробовать nginx? или это накладно для проекта?

**Comment by maxim-avramenko** [comment]
Выяснил причину подобного поведения.
Как оказалось всему виной js post на url без слеша в конце, происходит 301 редирект на страницу со слешем в конце но post данные при этом не передаются.
Для решения проблемы нужно дописать в js скриптах в url закрывающий слэш и жить становится лучше, жить становится веселей! 👍
