### ISSUE TITLE
Вывод информации для представлений в index

### ISSUE THREAD

**Issue by dzhedai** [yupe/yupe#2599]
Также из серии унификации

Не знаю как правильно сформулировать, но идея следующая.
Есть представление index, как правило туда может выводиться информация  типа заголовок и тд.

Думаю было бы правильно делать кастомный вывод названия модуля, который редактируется из настроек модуля

ps: осадочек редактирования этой части например из кода, все таки пахнет костыльщиной ^_^

![image](https://cloud.githubusercontent.com/assets/15369312/20765576/5e499d1a-b74c-11e6-9039-9b3885c417d0.png)

**Comment by yupe** [comment]
Ммм. Этот заголовок выводить в админке или где?

**Comment by dzhedai** [comment]
В настройке модуля выводить, в админке. Альтернатива для <h1><?= Yii::t('NewsModule.news', 'News') ?></h1>. Условно, менять этот заголовок в файле - не оч правильно

**Comment by yupe** [comment]
@dzhedai а для чего потребовалось менять заголовок в админке?

**Comment by dzhedai** [comment]
Изначально по итогам seo аудита, а потом из общего понимания что это не совсем корректно.
Ну либо глобально надо затащить текстовые вещи в настройку модуля.
Следуя правилу "заказчик в итоге получает готовый результат и может делать что хочет", продукт сводится к тому, что нужны специальные знания или привлечения специалиста

**Comment by yupe** [comment]
Не очень понял как SEO связано с текстом в админке? Можете конкртеный кейс описать?

**Comment by sabian** [comment]
Полагаю речь идет о том, чтобы сеошникам было удобно править заголовки без привлечения программистов

**Comment by yupe** [comment]
@sabian заголоки чего? Названия модуля, которое выводится только в админке? Зачем ?

**Comment by dzhedai** [comment]
@sabian от части прав.
Но заголовок нужен не только для них, у меня по двум ИМ были случаи, когда заказчик не мог найти где поменять заголовок раздела, например заменить стандартный с Новости, на Новости и события. По корп сайту подобное было

**Comment by dzhedai** [comment]
не только в админке, а чтобы вывод можно было редактировать из админки

**Comment by sabian** [comment]
@yupe Они не только в админке https://github.com/yupe/yupe/blob/master/themes/default/views/news/news/index.php#L6

**Comment by dzhedai** [comment]
Кароч. что я думаю. Надо в модуле вывести редактирование подобных вещей в целом
[`https://github.com/yupe/yupe/blob/master/protected/modules/news/messages/ru/news.php`](https://github.com/yupe/yupe/blob/master/protected/modules/news/messages/ru/news.php)

**Comment by yupe** [comment]
@sabian так это же шаблон +) Этот текст правится тремя способами: 
1 В шаблоне
2 Создается блок - вставляется в шаблон - тогда править можно из админки
3 Создать модуль под конкртеный сайт и туда в настройки вынести все заголовки и прочие текста.

**Comment by yupe** [comment]
@dzhedai мм при чем тут переводы? Переводы обязательны к применению только в админке. На фронте можете не использовать их.

**Comment by sabian** [comment]
Так я это понимаю и собственно сам не сторонник переть все подряд в настройки. Я просто уточнял о чем речь.

**Comment by dzhedai** [comment]
1) нужно иметь профильные знания, а это недружелюбно
2) Все что не автономно эт костыль =)
3) Вот мысль об этом то... Может введем какие то правила общие? 

@yupe @sabian тоже не сторонник, но достаточно часто заказчики меняют текст, потом сеошники мнеяют тексты...

**Comment by yupe** [comment]
@dzhedai ну это не реально сделать. На сайте тыщи текстов =) Мы их все не можем вынести в настройки модуля. Для этого есть "блоки", если текст должен быть редактируем из админки - он делается через блок.

**Comment by dzhedai** [comment]
@yupe окей =(
все равно надеюсь, что такой переход когда нить будет

**Comment by sabian** [comment]
Так все уже есть. На стадии создания сайта нужно просто думать где и что будет редактироваться.
Не забывайте, что у нас темы демонстрационные, поэтому мы сделали так.
Используйте блоки контента и будет вам счастье.
