### ISSUE TITLE
For english Yii::t() shows message, not translation

### ISSUE THREAD

**Issue by fazliddin** [yupe/yupe#2603]
All en translation files have empty translation like: 
```
'message' => ''
```
I want to replace message with some code like:
```
'lates' => 'Latest news'
```
But now `Yii::t('NewsModule.news','latest')` shows `latest`, not `Latest news`. Why?

**Comment by sabian** [comment]
Missing `t` in array key `'lates'`

**Comment by fazliddin** [comment]
No, there is no misspelling actually, other languages are working correctly. I just misspelled in github.

**Comment by yupe** [comment]
Check locale code (ru, en, uk etc) and your source and active app languages
More info here http://www.yiiframework.com/doc/guide/1.1/en/topics.i18n

**Comment by fazliddin** [comment]
source is en, default is uz, active is en

**Comment by yupe** [comment]
Source and active are the same?

**Comment by fazliddin** [comment]
yes

**Comment by fazliddin** [comment]
'sourceLanguage' => 'en',

**Comment by yupe** [comment]
Yii::app()->language?

**Comment by fazliddin** [comment]
en

**Comment by yupe** [comment]
Hm...if languages the same - translations will not be performed.

**Comment by fazliddin** [comment]
why? is it in yupe so? or is it default yii behaviour? I begin to remember that there was something like force to translate option

**Comment by yupe** [comment]
You can try use forceTranslation of CPhpMessageSource. Default is false

**Comment by fazliddin** [comment]
Thanks, it works. I was afraid that if I enable this then Yii::t('NewsModule.news','latest') works as expected but all remaining en messages will be displayed as empty since they have no translation. But it worked, because even if force enabled yii returns message instead of translation if translation is empty.

I offer yupe team to use codes as messages like `login.title` or `login-title`, because using english as message requires developer to be fluent in english and use special characters like "User's passwork in incorrect". When typing human language one may easily type extra space or forget quote which is hard to detect.
