### ISSUE TITLE
Проблемы с https

### ISSUE THREAD

**Issue by mikspark** [yupe/yupe#2613]
Выявить все проблемы связанные с работой по https 

- [x] 1. адреса картинок
- [x] 2. sitemap
- [x] 3. gravatar

**Comment by dzhedai** [comment]
А подробнее?

**Comment by yupe** [comment]
@mikspark чего делаем?

**Comment by samox1n** [comment]
У нас после переезда на https всё ок
И с картинками, и с картой сайта

**Comment by yupe** [comment]
https://talk.yupe.ru/viewtopic.php?f=77&t=2091&p=17130#p17109

**Comment by mikspark** [comment]
Проверил, остальное - ок.
