### ISSUE TITLE
Проблемка с деактивацией блоков

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2616]
Здравствуйте, 
деактивация блоков происходит только с очисткой кэша, посмотрите пожалуйста:
https://youtu.be/NgBG7gy_ybc

Если так и должно быть, подскажите как сделать чтобы деактивация происходила сразу.

**Comment by tmsk70** [comment]
Коллеги,
посмотрите пожалуйста, только у меня эта проблема или у всех?
Если только у меня, подскажите куда стоит заглянуть чтобы поправить ее.

https://youtu.be/47D4CzVb8zg

**Comment by yupe** [comment]
На текущей версии проблемы нет. Думаю, что вы обновились "криво". Должны быть сообщения в логах.

**Comment by tmsk70** [comment]
Да вот и не знаю как поступить, ведь полностью менял папки
modules/yupe
modules/contentblock

А в логах вроде ни чего прямого, просто ошибка 500:
37.21.130.106 - - [25/Jan/2017:10:36:38 +0300] "GET /backend/contentblock/contentBlock/create HTTP/1.1" 500 3033 "/backend/contentblock/contentBlock" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

не пойму как поступить

**Comment by yupe** [comment]
Значит есть информация в логах приложения.

**Comment by tmsk70** [comment]
Я удалял его перед этой проблемой и он не появляется, т.е. похоже что всё в порядке..

**Comment by tmsk70** [comment]
в error логе есть такие штуки, но не знаю, относятся ли они к моей проблеме:

[Wed Jan 25 13:04:45.475406 2017] [:error] [pid 9215] [client 37.21.130.106:57957] PHP Fatal error:  Call to a member function getFormattedList() on null in /var/www/root/data/taiga/protected/modules/contentblock/views/contentBlockBackend/_form.php on line 53, referer: http://taigakabel.com/backend/contentblock/contentBlock

**Comment by sabian** [comment]
Модуль category еще надо обновить

**Comment by tmsk70** [comment]
Я вам безмерно благодарен за очень оперативную помощь! Спасибо огромнейшее =)

**Comment by sabian** [comment]
И вам спасибо, что сообщаете об ошибках!

**Comment by tmsk70** [comment]
Так, а если у меня такая ошибка на другом сайте?
Псевдоним "application.modules.category.components.CategoryRepository" неверен. Убедитесь, что он указывает на существующий PHP файл.

хотя действия те же делал (обновил модуль юпи, блоков и категории из dev ветки)

**Comment by tmsk70** [comment]
Друзья.. вчера недоглядел, теперь в модуле page (в бэкэнде) ошибка:
В классе Category и его поведениях не найден метод или замыкание с именем "getFormattedList".

модуль страниц тоже пробовал загрузить новый

**Comment by tmsk70** [comment]
Коллеги, после обновления модулей в панели управления появился пункт "Юпи магазин"
подскажите как его скрыть? Просто обычному пользователю ограничены права и этот пункт ни где не фигурирует.

https://yadi.sk/i/nYIuo53D3AxC9A
