### ISSUE TITLE
Некоторые проблемы с визуальным редактором

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2617]
Здравствуйте, 
ищу помощи с такой проблемкой:
https://youtu.be/kwJuHJ2QOuE

**Comment by tmsk70** [comment]
Тикет можно закрыть, проблема отсутствует если юзать ctrl+v.
Глюк возникает только при вставке через кнопку видео, посему ей лучше не пользоваться.

**Comment by dzhedai** [comment]
К сожалению мы используем вендора 
https://github.com/yiiext/imperavi-redactor-widget
Отпишите пожалуйста туда эту проблему. Если они это исправят - у нас это тоже исправится
