### ISSUE TITLE
Стоимость доставки при оформлении заказа

### ISSUE THREAD

**Issue by yupe** [yupe/yupe#2618]
Доставка не суммируется и не фиксируется

**Comment by sabian** [comment]
У меня все нормально

![order1](https://cloud.githubusercontent.com/assets/434141/23296905/318e0e1c-fa88-11e6-95c0-df5463f2acf9.png)

Может у тебя включена опция "Оплачивать отдельно"? В этом случае да, не суммируется, что верно.

![order2](https://cloud.githubusercontent.com/assets/434141/23296933/52c84124-fa88-11e6-8db7-fc2a4cd4c6d5.png)

**Comment by yupe** [comment]
Точно!
