### ISSUE TITLE
Вырезается атрибут target=_blank 

### ISSUE THREAD

**Issue by sabian** [yupe/yupe#2619]
При сохранении описаний товара вырезается атрибут target=_blank у [ссылок](https://talk.yupe.ru/viewtopic.php?f=2&p=16767). 
Проблема вот [здесь](https://github.com/yupe/yupe/blob/master/protected/modules/store/models/Product.php#L139). Отключение фильтра решает проблему.

**Comment by maxim-avramenko** [comment]
@sabian отключение данного фильтра не решает проблему, а создает вместе с решением еще как минимум 10 :)

**Comment by sabian** [comment]
@maxim-avramenko Возможно я некорректно выразился, но я не предлагал отключать фильтр. Я лишь указал на источник проблемы, сообщив, что дело не в редакторе, а в фильтре, при отключении которого проблема пропадает.
