### ISSUE TITLE
Уходят уведомления об изменении заказа в админке, даже если не ставить галочку

### ISSUE THREAD

**Issue by mikspark** [yupe/yupe#2627]
https://github.com/yupe/yupe/blob/dev/protected/modules/order/controllers/OrderBackendController.php#L121

https://github.com/yupe/yupe/blob/dev/protected/modules/order/models/Order.php#L483

https://github.com/yupe/yupe/blob/dev/protected/modules/order/listeners/OrderListener.php#L13

**Comment by mikspark** [comment]
Если галочку ставлю в Оповестить покупателя о состоянии заказа то ошибка 500 вылезает с текстом

В классе OrderStatus и его поведениях не найден метод или замыкание с именем "getTitle".

**Comment by samox1n** [comment]
Обновился. Не помогло.

Создаю заказ в Инкогнито.
Письмо магазину о новом заказе пришло, А клиенту на почту письмо о заказе не пришло.

Затем вношу правки в заказ, меняю статус, пишу комментарии, сохраняю и получаю письмо на почту магазина с изменениями. Зачем?

Ставлю галочку Оповестить покупателя о состоянии заказа, клиенту приходит письмо, которое должно было прийти в первый раз. То есть ваш заказ №, бла бла бла...

**Comment by sabian** [comment]
Задача была о другом и эта ошибка исправлена, так что не вижу смысла открывать ее заново.

@samox1n У вас в настройках модуля "Заказы" (обратите внимание, именно Заказы, а не Магазин) указан эмейл от имени которого отправлять сообщения? Если нет, то они и не будут уходить. Получать будет только админ.

> Ставлю галочку Оповестить покупателя о состоянии заказа, клиенту приходит письмо, которое должно было прийти в первый раз. То есть ваш заказ №, бла бла бла...
Что вас здесь смущает? Это просто такой шаблон сообщения, сделайте свой и у вас будет другой.

**Comment by samox1n** [comment]
Почта указана.

Почему не сохраняется галочка Оповестить покупателя о состоянии заказа?

Шаблон уже давно поправлен, но фишка в другом:
в оригинале клиент делает заказ, ему приходит письмо Спасибо за заказ, и если в заказ в админке вносятся правки и ставится галочка Оповестить, то клиенту приходит письмо не Спасибо за заказ, а Статус заказа изменён бла бла бла.

**Comment by sabian** [comment]
> Почему не сохраняется галочка Оповестить покупателя о состоянии заказа?

А почему она должна сохраняться? Это разовое действие. Вы поменяли что-то в заказе, например написали комментарий для себя, и не хотите оповещать пользователя, то не ставите галочку. Если сделали ему скидку и хотите об этом сообщить, то ставите галочку.

> если в заказ в админке вносятся правки и ставится галочка Оповестить, то клиенту приходит письмо не Спасибо за заказ, а Статус заказа изменён бла бла бла.

Ну правильно, вы ведь изменили заказ, вот и приходит сообщение о его изменении. Вы же можете и этот шаблон письма поменять.

**Comment by samox1n** [comment]
Ок про сохранение галочки выяснил, спасибо.
А вот письмо после изменения файлов из этого топика приходит всё равно не то, должно поступать orderChangeStatus.php, а поступает newOrderUser.php

**Comment by sabian** [comment]
> А вот письмо после изменения файлов из этого топика приходит всё равно не то, должно поступать orderChangeStatus.php, а поступает newOrderUser.php

Вот только сейчас стало понятно :)
Проверим. Поправим.

**Comment by yupe** [comment]
Приходит таки orderChangeStatus. Проверил.

**Comment by samox1n** [comment]
Хм
Установил актуальную чистую версию на два разных сервера, письмо клиенту поступает только если ставлю галочку Оповестить, и опять newOrderUser.php

**Comment by sabian** [comment]
да, есть ошибка. Будем исправлять

**Comment by samox1n** [comment]
А как так? Я не обновлялся, всё работало, потом бах и перестало

**Comment by sabian** [comment]
это dev-версия и ничего удивительного, что появляются ошибки. Откатитесь назад и все будет работать.

**Comment by samox1n** [comment]
Которая отсюда https://yupe.ru/download по оранжевой кнопке Актуальная версия это dev?

**Comment by sabian** [comment]
Ошибка исправлена
