### ISSUE TITLE
Баг с порядком вывода товаров (работало, поломалось)

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2636]
Ребят, раньше работало, сейчас "поломалось":
https://youtu.be/BwFrBJx5aw0

**Comment by sabian** [comment]
У вас в настройках какой порядок сортировки задан?

![shop-settings](https://cloud.githubusercontent.com/assets/434141/23829627/0262e180-0708-11e7-8bd8-88e58a778c14.png)

**Comment by tmsk70** [comment]
А где вы нашли такие настройки, у меня чуть другие в разделе Магазин->Настройки

![2017-03-12_13-43-10](https://cloud.githubusercontent.com/assets/9645895/23829648/015e79f8-072a-11e7-804c-5974ec9c069e.png)

**Comment by sabian** [comment]
Если вы не обновлялись, то ошибка могла появиться только в результате ваших действий.
Уже давно доступна версия 1.1, где есть возможность задать сортировку.
В текущей версии сортировка работает правильно, поэтому задачу закрываю.
