### ISSUE TITLE
Модуль блогов, загрузка картинок не под главным админом

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2641]
Ребят, была ситуация - не грузились изображения в записи блогов, если авторизовываться не под главным админом.

Может только в моей версии, но скорее везде,
поправили загрузку фото в файле
\protected\modules\blog\controllers\PostBackendController.php
строка 25
добавили 'imageUpload' в правила

Просто при разработке модуля не прописали видимо.

**Comment by sabian** [comment]
Не забывайте также давать пользователям права на работу с изображениями.
