### ISSUE TITLE
Загрузка Yii Booster assets

### ISSUE THREAD

**Issue by OzodAmin** [yupe/yupe#2647]
перепробовал все чтобы Yupe не загружал свои внутренные CSS & JS  файлы. Как можно сделат чтобы они загружалис только в админ панеле.

**Comment by sabian** [comment]
Для вопросов у нас есть форум https://talk.yupe.ru/. Здесь пишут сообщения об ошибках.

Нужно удалить эту строку https://github.com/yupe/yupe/blob/master/themes/default/bootstrap.php#L5 или взять за основу тему shop.
