### ISSUE TITLE
Цену вариантов товара

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2648]
Друзья привет,
столкнулся с тем что потребовались варианты товаров, а далее сразу подумал что в просмотре посетителю не хватает цены варианта.
Пользователю ведь нужно сразу знать сколько стоит тот или иной вариант, а не смотреть изменение цены, после того как выбрал его.

Можно ли вывести цену вариантов? Пример:
https://yadi.sk/i/MkWtrE-03JtksC

**Comment by yupe** [comment]
Можно конечно. Все варианты доступны через текущую модель товара. Можно хоть табличкой вывести, хоть как =) Для вопросов по движку лучше вот сюда https://talk.yupe.ru/ писать.
