### ISSUE TITLE
Shop theme / Notifications / z-index level

### ISSUE THREAD

**Issue by Divan4ik** [yupe/yupe#2649]
Всем привет.

на моем сайте используется стилизация сетки товаров как на сайте http://www.svyaznoy.ru
То есть при :hover добавляется z-index для перекрытия границ.
Если попытаться добавить изменение z-index для любых элементов они начинают перекрывать стандартный notifications

![notifications](https://user-images.githubusercontent.com/3591619/27272006-b26bb6ae-54d0-11e7-8c95-41cdc22ad53b.jpg)

Если добавить z-index родительскому блоку .notifications, то все выглядит прилично вне зависимости от кол-ва возможных оповещений
![notifications](https://user-images.githubusercontent.com/3591619/27272072-02e2c19a-54d1-11e7-980a-66bd214dc5ea.jpg)

**Comment by yupe** [comment]
PR?

**Comment by Divan4ik** [comment]
Сделаю, просто думал мало-ли может задумка была какая)

**Comment by sabian** [comment]
Спасибо!
