### ISSUE TITLE
Возможность заказать товар без выбора варианта

### ISSUE THREAD

**Issue by pa1m0n** [yupe/yupe#2654]
https://demo.yupe.ru/store/noutbuk-lenovo-ideapad-g5030.html
у данного товара два варианта, но можно заказать без выбора варианта и не понятно что человек выбрал.

**Comment by tmsk70** [comment]
Это уже зависит от вашей реализации, можно сделать что по умолчанию будет какой-либо вариант.
По дефолту ни чего не выбрано из допов.
Я сперва тоже думал попросить чтобы из коробки всегда был автоматом выбран первый вариант, но потом поразмыслил и понял что это не всегда нужно, ну а когда нужно, то можно кастомизировать.

**Comment by pa1m0n** [comment]
имхо было бы логичней, что товар нельзя добавить в корзину без выбора варианта

**Comment by tmsk70** [comment]
А если вариант идет как доп к товару, например фотоаппарат и флэш карта, которая не всегда нужно.
Тогда зачем?

**Comment by pa1m0n** [comment]
тоже верно, тогда это приводит к тому что выбор варианта должен быть обязательный или нет

**Comment by tmsk70** [comment]
В админке можно отметить обязательный атрибут или нет.

**Comment by dzhedai** [comment]
Задача не актуальная. Предложенная бизнес логика решается существующими методами. 
Пока задачу закрываю
