### ISSUE TITLE
Сортировка товаров - баг или только у меня так?

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2655]
Коллеги, приветствую, посмотрите пожалуйста ролик:
https://youtu.be/5gp2R24X92M

Не пойму логику работы сортировки или это баг.

**Comment by sabian** [comment]
Сортировка работает, но проблема в том, что в админке товары отображаются по дате изменения и дате создания, и нет ни какой возможности поставить сортировку по порядку.
Предлагаю либо показать в гриде поле Позиция, чтобы можно было отсортировать по нему, либо сделать соответствующую настройку для админки, либо привязаться к текущим настройкам на сайте, чтобы было одинаково везде и не вызывало путаницы.

**Comment by tmsk70** [comment]
Хм, а мне кажется или на старых версиях, когда только ввели сортировку дрэг-дропом, это дело работало, причем корректно, сортировало и по дате (т.е. измененный товар улетал на верх) и по позиции, т.е. мы могли перетащить куда нужно и всё было окей.

Причем я еще задавал тут создавал тикет с вопросом, как быть если хочу перетащить товар на 102 позицию, когда он на второй странице (если выводить по 100 товаров).

**Comment by yupe** [comment]
"либо привязаться к текущим настройкам на сайте, чтобы было одинаково везде и не вызывало путаницы" - думаю такой вариант будет правильным.

**Comment by tmsk70** [comment]
Ребят, а вот у меня частенько порядок товаров меняется так: по дефолту - сортировка по дате изменения (она же добавление товара), плюс дрэг-дропом бывает выстраиваю порядок.

Дайте совет, как можно реализовать себе доработку чтобы поменять позицию у сотого товара, а именно перетащить его по порядку ниже. Сейчас приходится ставить вывод по 15 товаров, идти на шестую страницу, чуть перетаскивать его, потом снова менять число выводимых товаров и снова перетаскивать. =)
Что-то сходу не придумаю. Есть мысль перепилить число выводимых товаров (добавить вывод по 300-500 штук).

**Comment by sabian** [comment]
> Есть мысль перепилить число выводимых товаров (добавить вывод по 300-500 штук).

Там и перепиливать нечего. Есть свойство https://github.com/yupe/yupe/blob/master/protected/modules/yupe/widgets/CustomGridView.php#L73
Можете задать его при вызове виджета или поменять прямо в этой строке
