### ISSUE TITLE
Работа utm - меток в старых версиях

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2662]
Друзья, в старых версиях юпи не открываются url'ы с utm метками, а в новых все окей, вот пример на основной демке юпи:
[https://demo.yupe.ru/?utm_medium=cpc&utm_source=b-context&utm_campaign=direct-b&utm_term=%D0%B4%D1%8D%D0%BD%D0%B0%D1%81%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C&utm_content=%D0%90%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D1%8B+%D0%94%D0%AD%D0%9D%D0%90%D0%A1+%D0%B2+%D0%A2%D0%BE%D0%BC%D1%81%D0%BA%D0%B5](url)

Пример yupe 1.0 и тут, почему-то не срабатывает:
[http://denas70.ru/?utm_medium=cpc&utm_source=b-context&utm_campaign=direct-b&utm_term=%D0%B4%D1%8D%D0%BD%D0%B0%D1%81%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C&utm_content=%D0%90%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D1%8B+%D0%94%D0%AD%D0%9D%D0%90%D0%A1+%D0%B2+%D0%A2%D0%BE%D0%BC%D1%81%D0%BA%D0%B5](url)

А тут пример yupe 1.2 dev - уже работает:
[http://vent-a.ru/?utm_medium=cpc&utm_source=b-context&utm_campaign=direct-b&utm_term=%D0%B4%D1%8D%D0%BD%D0%B0%D1%81%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C&utm_content=%D0%90%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D1%8B+%D0%94%D0%AD%D0%9D%D0%90%D0%A1+%D0%B2+%D0%A2%D0%BE%D0%BC%D1%81%D0%BA%D0%B5](url)

Подскажите пожалуйста, где скорее всего это правится или может просто заменить пару каких-то файлов того же основного модуля yupe?

**Comment by tmsk70** [comment]
Дополнение, такой баг оказывается только для главных страниц.
Еще одна проблема в том что с этим багом не работает поиск.

Пример yupe 1.0 и тут, есть баг с меткой:
[http://denas70.ru/?utm_medium=cpc&utm_source=b-context&utm_campaign=direct-b&utm_term=%D0%B4%D1%8D%D0%BD%D0%B0%D1%81%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C&utm_content=%D0%90%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D1%8B+%D0%94%D0%AD%D0%9D%D0%90%D0%A1+%D0%B2+%D0%A2%D0%BE%D0%BC%D1%81%D0%BA%D0%B5](url)

Пример yupe 1.0 и тут (для страницы) бага уже нет:
[http://denas70.ru/apparaty-denas/?utm_medium=cpc&utm_source=b-context&utm_campaign=direct-b&utm_term=%D0%B4%D1%8D%D0%BD%D0%B0%D1%81%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C&utm_content=%D0%90%D0%BF%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D1%8B+%D0%94%D0%AD%D0%9D%D0%90%D0%A1+%D0%B2+%D0%A2%D0%BE%D0%BC%D1%81%D0%BA%D0%B5](url)

**Comment by yupe** [comment]
Я думаю что это не баг движка а баг конфигурации веб-сервера.

**Comment by tmsk70** [comment]
Ну это про utm метки часто пишут что причина может быть в настройках сервера.
Но штука в том что даже такой запрос не выполняется:

**Comment by yupe** [comment]
Запросы с q перехватывает модуль поиска потому что+)

**Comment by yupe** [comment]
Отключите модуль поиска и попробуйте еще разок +)

**Comment by tmsk70** [comment]
Коллеги, извиняюсь за кипишь, я как косяк всегда =)
Тикет можно  закрывать
