### ISSUE TITLE
Прокручивание страницы к началу при пагинации

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2663]
Друзья,
чтото постоянно забываю сказать о вещи, которая оочень не удобна - аякс пагинация без поднятия страницы к началу.

Представьте посетитель ходит по страницам магазина и постоянно поднимает страницу к началу (особенно за полосу прокрутки когда нет кнопки Наверх).
Предлагаю сделать поднятие страницы при переходе по ее номеру.
Удобно же)

**Comment by yupe** [comment]
Здраво. 
Это вопрос выбранной темы оформления (шаблона). 
Логика программируется на стороне клиента (javascript)

**Comment by tmsk70** [comment]
Ну у себя так и делаем, решил вам предложить чтобы кому-то было сразу =)
