### ISSUE TITLE
Баг с добавлением товара в корзину

### ISSUE THREAD

**Issue by validcom94** [yupe/yupe#2670]
Если, много раз нажимать кнопку Добавить в корзину, то кол-во лежащего товара в корзине может превысить его фактическое наличие(product->quantity). 
Решение: 
Добавить проверку в EShoppingCart::put()
Что то типа такого: 

> public function put( IECartPosition $position, $quantity = 1 ) {
> 		$key = $position->getId();
> 		if ( $this->itemAt( $key ) instanceof IECartPosition ) {
> 			$position    = $this->itemAt( $key );
> 			$oldQuantity = $position->getQuantity();
> 			$quantity    += $oldQuantity;
> 		}
> 		$product = Product::model()->findByPk($position->id);
> 		if (empty($product )) {
> 			Yii::app()->ajax->failure(Yii::t("CartModule.cart", 'Ошибка!'));
> 		}
> 		if ($product->quantity < $quantity) {
> 			return Yii::app()->ajax->failure(Yii::t("CartModule.cart", 'Не хватает товара на складе!'));
> 		}
> 		$this->update( $position, $quantity );
> 		$this->eventManager->fire( CartEvents::CART_ADD_ITEM, new CartEvent( Yii::app()->getUser(), $this ) );
> 	}

**Comment by yupe** [comment]
Спасибо за пример кода! Можете оформить в виде pull request?

**Comment by validcom94** [comment]
Готово

**Comment by dzhedai** [comment]
Задачу закрываю. Приняли подобную реализацию https://github.com/yupe/yupe/pull/2786

**Comment by koma136** [comment]
То что сделала Маша не отменяет данной задачи.
