### ISSUE TITLE
Магазин - баг с инлайн редактированием значений атрибутама не под главным админом

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2673]
Друзья привет,
ранее был баг в работе с атрибутами не под главным админом (его исправили):
https://github.com/yupe/yupe/issues/2635

Сейчас нашел "продолжение" предыдущего - небольшой баг с инлайн редактирование все под тем же не главным админом, вот ролик:
https://youtu.be/W9Z3gkaT_Y0

**Comment by sabian** [comment]
Спасибо! Проверим

**Comment by tmsk70** [comment]
Спасибо что отвечаете, я думал юпи уже "заглох", даже обрадовался когда недавно был закрыт этот тикет [2440](https://github.com/yupe/yupe/issues/2440) =)
