### ISSUE TITLE
Удаление способа доставки и заказы

### ISSUE THREAD

**Issue by tmsk70** [yupe/yupe#2678]
Нашел мелкий баг, если оформить заказ и выбрать один из способов доставки, затем в админке удалить этот способ доставки, то раздел заказов уходит в 500 ошибку (видимо потому что есть заказ у которого не существующий способ доставки - значение null в колонке delivery_id).

**Comment by Adlett** [comment]
Если используется способ доставки, то его нельзя ведь удалять?

**Comment by tmsk70** [comment]
У меня из-за этого была ошибка.
В базе был заказ, у которого был способ доставки, который удалили.

Но, как всегда у меня бывает, за мной нужно проверять =))) Ибо мои проблемы бывают не возникают у других))))
