### ISSUE TITLE
Предлагаю список категорий в вид дерева перевести

### ISSUE THREAD

**Issue by Smarteh** [yupe/yupe#2698]
Считаю что удобнее будет при создании товара категории представлять в виде дерева, как уже реализовано в дополнительных категориях.
![image](https://user-images.githubusercontent.com/17685525/37602411-e886dc44-2bbe-11e8-811b-23569edf3709.png)
Каталог категорий в дереве ИМХО также удобнее. К тому же всем кто связан с торговлей до боли знакомо дерево категорий справочника номенклатуры 1С. : 
![image](https://user-images.githubusercontent.com/17685525/37603615-93934508-2bc1-11e8-88e2-ed9bfd397cea.png)

**Comment by syrexby** [comment]
не по теме:
у вас на сайте http://skladonet.ru проблема с редиректом с www на без www.
А ссылка с www присутствует:
![image](https://user-images.githubusercontent.com/15049122/37604688-9752c548-2ba2-11e8-8f2b-55a1e97f98a3.png)

**Comment by Smarteh** [comment]
Спасибо, поправил

**Comment by dzhedai** [comment]
Задача не актуальная
