### ISSUE TITLE
Не могу установить Юпи

### ISSUE THREAD

**Issue by PCCartem** [yupe/yupe#2726]
$ composer create-project yupe/yupe www --no-dev --prefer-dist
Installing yupe/yupe (1.2)
  - Installing yupe/yupe (1.2): Downloading (100%)         
Created project in www
> yupe\components\Composer::preInstall
Yupe install
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 19 installs, 0 updates, 0 removals
  - Installing wikimedia/composer-merge-plugin (dev-master 0e7f98d): Downloading (100%)         
  - Installing 2amigos/transliterator-helper (dev-master 845254b): Downloading (100%)         
  - Installing ckeditor/ckeditor (4.7.3): Loading from cache
  - Installing clevertech/yii-booster (v4.0.1): Loading from cache
  - Installing imagine/imagine (v0.6.3): Loading from cache
  - Installing itmages/yii-eoauth (1.0.2): Downloading (failed)    Failed to download itmages/yii-eoauth from dist: The "https://api.github.com/repos/itmages/yii-eoauth/zipball/702f8b8b0d4128de1ead9f37b3ff700ef0ef75a9" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing itmages/yii-eoauth (1.0.2): Cloning 702f8b8b0d

                                                                                                 
  [RuntimeException]                                                                             
  Failed to clone https://github.com/itmages/yii-eoauth.git via https, ssh protocols, aborting.  
                                                                                                 
  - https://github.com/itmages/yii-eoauth.git                                                    
    Cloning into '/home/pccartem/webhosts/test.loc/www/vendor/itmages/yii-eoauth'...             
    remote: Invalid username or password.                                                        
    fatal: Authentication failed for 'https://github.com/itmages/yii-eoauth.git/'                
                                                                                                 
  - git@github.com:itmages/yii-eoauth.git                                                        
    Cloning into '/home/pccartem/webhosts/test.loc/www/vendor/itmages/yii-eoauth'...             
    ERROR: Repository not found.                                                                 
    fatal: Could not read from remote repository.                                                
                                                                                                 
    Please make sure you have the correct access rights                                          
    and the repository exists.                                                                   
                                                                                                 

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

Я так понимаю изменился репозиторий в одном из пакетов

**Comment by dzhedai** [comment]
Закрывай таск
