### ISSUE TITLE
Шаблон eauth widget в теме

### ISSUE THREAD

**Issue by AlexGrump** [yupe/yupe#2742]
Сам класс виджета сейчас лежит в `vendor\nodge\yii-eauth\`, понадобилось переписать `vendor\nodge\yii-eauth\views\auth.php`, но что-то я не могу ни как создать правильную структуру папок в теме, а что-то менять в `vendor` не хочется

Вот немного из того что я пробовал и не сработало:
```themes\
- tocco\
-- nodge\
--- eauth\
----widgets\
--- yii-eauth\
----widgets\
-- eauth\
--- widgets\
-- yii-eauth\
--- widgets\

**Comment by koma136** [comment]
pull/2753 должен поправить такую ситуацию
